plugins/eigen/include/plugins/eigen_defs.hpp, tests/common/core_test.inl, tests/common/plugin_test.inl
The global transformation is defined by 
```c++
struct transform3 { 
using point3 = ...
using vector3 = ...
};
```
and the types can be deduced from the transform, in order to keep template parameters few.
It also introduces `cartesian2`, `polar2` and `cylindrical2` structs with callable `operator` to retrieve the local coordinate frame type.
=> feat!: change to transform3 and local2 structs

core/include/tools/planar_intersector.hpp, tests/common/planar_intersection_test.inl, tests/eigen/eigen_planar_intersection.cpp
This PR adds a first planar intersector to the project.
Additionally, it introduces a `intersection_status` enum for flagging the intersection type.
=> feat!: first planar intersector

core/include/core/intersection.hpp, core/include/core/surface.hpp, core/include/core/track.hpp, core/include/geometry/detector.hpp, core/include/tools/concentric_cylinder_intersector.hpp, core/include/tools/cylinder_intersector.hpp, core/include/tools/navigator.hpp, core/include/tools/planar_intersector.hpp, core/include/utils/unbound.hpp, plugins/array/include/plugins/array_defs.hpp, plugins/eigen/include/plugins/eigen_defs.hpp, plugins/smatrix/include/plugins/smatrix_defs.hpp, tests/common/include/tests/common/benchmark_intersect_all.inl, tests/common/include/tests/common/benchmark_intersect_surfaces.inl, tests/common/include/tests/common/test_core.inl, tests/common/include/tests/common/test_cylinder_intersection.inl, tests/common/include/tests/common/test_cylindrical_detector.inl, tests/common/include/tests/common/test_planar_intersection.inl, tests/common/include/tests/common/test_plugin.inl, tests/common/include/tests/common/test_surfaces.hpp, tests/io/include/tests/io/read_csv.hpp
This PR decouples the `context` from the `transform` class, it will allow to implement common contextual containers for different plugins.
It also changes the `intersectors` to run on context-resolved transforms rather than surfaces. It prepares for a follow-up PR which will change the  `surface::transform_type` to `surface::transform_link` .
cc @niermann999 - I have already changed the `smatrix` plugin as well.
=> feat: split off context

core/include/core/surface.hpp, core/include/geometry/detector.hpp, core/include/tools/navigator.hpp, tests/common/include/tests/common/test_cylindrical_detector.inl
This PR removes the `transform` storage from the surface and uses the `transform_type` as a link instead.
It will allow the detector to be templated on the `contextual_container` and hence will give a single `context` entry point.
=> feat: encapsulating transform container of detector

core/include/geometry/detector.hpp, core/include/grids/axis.hpp, core/include/grids/grid2.hpp, core/include/tools/navigator.hpp, core/include/utils/indexing.hpp, tests/unit_tests/core/CMakeLists.txt, tests/unit_tests/core/grids_axis.cpp
This PR introduces basic `axis` types and adds a unit test.
For the moment, a regular closed axis and a circular axis are available, which is sufficient for the TrackML detector.
=> feat: introduce axis

core/include/grids/serializer2.hpp, tests/unit_tests/core/grids_serializer.cpp
This PR introduces a small struct that adds a `serializer` for grids. For the moment, only a jump-serialiser is available.
=> feat: introduce serializer

.gitmodules, core/include/grids/grid2.hpp, core/include/grids/populator.hpp, tests/unit_tests/core/grids_grid2.cpp
This PR adds the possibility to shift a grid by a constant `bare_value`. This feature is needed when creating one memory block of e.g. surfaces, transforms, and then stitch them together.
=> feat: adding grid shift

tests/common/include/tests/common/masks_annulus2.inl
Added static cast to scalar type for the literals in the annulus2 mask test. Unit test for float type should work now.
=> fix float unit test annulus2 mask

core/include/masks/annulus2.hpp, core/include/masks/ring2.hpp
To make sure everything is dealt with at compile time in the type based branching that is done for masks that differentiate between cartesian and polar coordinates.
=> Enforce compile time type condition resolution for masks

core/include/grids/axis.hpp, core/include/grids/grid2.hpp, core/include/grids/serializer2.hpp, io/include/json/json_grids.hpp, tests/common/include/tests/common/test_cylindrical_detector.inl, tests/io/json/write_grid.cpp, tests/unit_tests/core/grids_axis.cpp, tests/unit_tests/core/grids_grid2.cpp, tests/unit_tests/core/grids_serializer.cpp, tests/unit_tests/core/utils_local_object_finder.cpp
This PR changes the grid to have a dynamically sized storage:
- this makes the axes not templated on the number of bins and allows for non-equidistant binning
=> feat: commit changes

core/include/grids/grid2.hpp
This PR improves slightly the timing of the `single_layer_components` test.
=> fix: reserve grid zone vector size

core/include/core/detector.hpp, core/include/masks/annulus2.hpp, core/include/masks/cylinder3.hpp, core/include/masks/rectangle2.hpp, core/include/masks/ring2.hpp, core/include/masks/single3.hpp, core/include/masks/trapezoid2.hpp, core/include/masks/unmasked.hpp, core/include/tools/planar_intersector.hpp, tests/common/include/tests/common/benchmark_intersect_surfaces.inl, tests/common/include/tests/common/benchmark_masks.inl, tests/common/include/tests/common/masks_annulus2.inl, tests/common/include/tests/common/masks_containers.inl, tests/common/include/tests/common/masks_cylinder3.inl, tests/common/include/tests/common/masks_rectangle2.inl, tests/common/include/tests/common/masks_ring2.inl, tests/common/include/tests/common/masks_single3.inl, tests/common/include/tests/common/masks_trapezoid2.inl, tests/common/include/tests/common/masks_unmasked.inl, tests/common/include/tests/common/test_cylinder_intersection.inl, tests/common/include/tests/common/test_planar_intersection.inl, tests/common/include/tests/common/test_single_layer_components.inl, tests/io/include/tests/io/read_csv.hpp
This PR removes the unneccary `template <typename scalar_type, ..>` in favour of the `scalar` shorthand in masks.
Less template, more happy.
=> feat: remove scalar template for masks

core/include/utils/enumerate.hpp, tests/unit_tests/core/utils_enumerate.cpp
Convenience function for single and range enumerator, allows to write common intersection kernel for detector and portal surfaces.
=> feat: add singe and range enumerator

core/include/core/detector.hpp, core/include/core/proto_detector.hpp, core/include/masks/annulus2.hpp, core/include/masks/cylinder3.hpp, core/include/masks/rectangle2.hpp, core/include/masks/ring2.hpp, core/include/masks/single3.hpp, core/include/masks/trapezoid2.hpp
Masks do have their intrinsic local frame definition, hence this could be just handed by the make, will make the intersection kernel easier to program.
=> feat: add default local-type to masks

core/include/core/proto_detector.hpp, core/include/masks/cylinder3.hpp, core/include/tools/concentric_cylinder_intersector.hpp, core/include/tools/cylinder_intersector.hpp, core/include/tools/intersection_kernel.hpp, io/csv/include/io/csv_io.hpp, tests/common/include/tests/common/benchmark_intersect_all.inl, tests/common/include/tests/common/tools_intersection_kernel.inl
This PR changes the example to use the former `proto_detector`.
It will result into a slower `intersect_all` test as it evokes the unrolling for different surfaces.
=> feat: change to proto detector

apps/common/include/apps/common/display_volumes_rz.inl, core/include/core/detector.hpp, core/include/core/transform_store.hpp, io/csv/include/io/csv_io.hpp, tests/common/include/tests/common/benchmark_find_volume.inl, tests/common/include/tests/common/benchmark_intersect_all.inl, tests/common/include/tests/common/core_detector.inl, tests/common/include/tests/common/core_transform_store.inl, tests/common/include/tests/common/io_read_detector.inl, tests/common/include/tests/common/tools_intersection_kernel.inl, tests/common/include/tests/common/tools_line_stepper.inl, tests/common/include/tests/common/tools_navigator.inl, tests/common/include/tests/common/tools_propagator.inl
This PR changes the detector to template types to prepare later usage with `vecmem`.
@krasznaa @stephenswat @niermann999 - Is that along the lines you discussed?
There are a few more classes that might need this update then:
- `axis`
- `grid`
Also, I am using a tuple for typing the bounds, not sure what your plans are with tuples (if any), we might have to write a custom class for this I suppose.
=> feat: changing detector to templated date-types

core/include/tools/navigator.hpp, core/include/utils/enumerate.hpp, tests/unit_tests/core/utils_enumerate.cpp
This PR fixes a small problem with template deduction in the `enumerate(...)` function.
=> fix: incorrect template deduction in clang

core/include/core/detector.hpp, core/include/core/transform_store.hpp, core/include/core/volume_connector.hpp, core/include/tools/bin_association.hpp, core/include/tools/intersection_kernel.hpp, core/include/tools/navigator.hpp, core/include/tools/planar_intersector.hpp, core/include/utils/enumerate.hpp, io/csv/include/io/csv_io.hpp, tests/common/include/tests/common/benchmark_intersect_all.inl, tests/common/include/tests/common/core_detector.inl, tests/common/include/tests/common/tools_navigator.inl, tests/unit_tests/core/utils_enumerate.cpp
First step to single storage geometry:
- A single large transform store is owned by detector
- Iterator based access to detector data with the help of nested classes (volume, constituents): The volumes pass a transform index range to initialize the iterator. This avoids having to hold a detector instance pointer in the volume/constituents by which the data is accessed
- Removes what seems to be a bug in the csv reader, where transforms are now only stored, if they have a valid mask
=> feat: move transform storage to detector level

core/include/core/detector.hpp, core/include/core/volume_connector.hpp, core/include/tools/bin_association.hpp, core/include/tools/navigator.hpp, io/csv/include/io/csv_io.hpp, tests/common/include/tests/common/benchmark_intersect_all.inl
This PR continues the work of and builds upon #82 to also move the masks to detector level:
- The surface and portal links now point to masks in the big containers
- The masks are accessed through the detector as opposed to the constituents class. 
- A mask container of the appropriate type (surface/portal) is filled for each volume in the detector io and then unrolled again to fill the detectors containers.
=> ref: move masks to detector level

apps/common/include/apps/common/display_bin_association.inl, apps/common/include/apps/common/display_layers.inl
Adapt the matplot++ display to new geometry interface in preparation of the navigation debugging. Will be updated, when PR #86 is merged.
=> fix: adapt display to new interface

core/include/core/detector.hpp, core/include/core/transform_store.hpp, core/include/core/volume_connector.hpp, core/include/tools/bin_association.hpp, core/include/tools/navigator.hpp, io/csv/include/io/csv_io.hpp, tests/common/include/tests/common/benchmark_intersect_all.inl, tests/common/include/tests/common/core_detector.inl, tests/common/include/tests/common/core_transform_store.inl, tests/common/include/tests/common/tools_navigator.inl
This PR pools the surface and portal surface containers on detector level, leaving no dynamically allocated memory in the volumes, except for their string names.  As in the previous PRs, the volumes reference their surfaces by index range now and the actual data is provided by the detector interface. To avoid depency problems when updating links while adding components to the detector, all components are now added in one go, sorted by mask type.
=> ref: move surfaces to det

core/include/core/detector.hpp, core/include/core/volume_connector.hpp, core/include/tools/bin_association.hpp, core/include/tools/navigator.hpp, io/csv/include/io/csv_io.hpp, tests/common/include/tests/common/benchmark_intersect_all.inl, tests/common/include/tests/common/core_detector.inl
This PR uses templating to make the interfaces of the volume and detector classes more generic and to reduce code duplication between surfaces and portals. It comes at the cost of a more verbose member function call
=> ref: homogenize detector and volume interface

core/include/core/detector.hpp, core/include/core/index_geometry.hpp, core/include/core/mask_store.hpp, core/include/core/surface_base.hpp, core/include/core/volume_connector.hpp, core/include/masks/annulus2.hpp, core/include/masks/cylinder3.hpp, core/include/masks/rectangle2.hpp, core/include/masks/ring2.hpp, core/include/masks/trapezoid2.hpp, core/include/tools/bin_association.hpp, core/include/tools/intersection_kernel.hpp, core/include/tools/navigator.hpp, core/include/utils/generators.hpp, io/csv/include/io/csv_io.hpp, tests/common/include/tests/common/benchmark_intersect_all.inl, tests/common/include/tests/common/core_detector.inl, tests/common/include/tests/common/core_mask_store.inl, tests/common/include/tests/common/tools_intersection_kernel.inl, tests/unit_tests/CMakeLists.txt, tests/unit_tests/array/array_mask_store.cpp, tests/unit_tests/eigen/eigen_mask_store.cpp, tests/unit_tests/smatrix/smatrix_mask_store.cpp, tests/unit_tests/vc/vc_array_mask_store.cpp
Add a mask store for different mask types defined by the geometry, similar to the transform store. Thereby also defining a global interface for mask containers. Based on #108, which has to be merged first. Adds constructors to the masks, so that they can be constructed inplace when they are inserted into containers.
Some precautions were taken with intersection unrolling when different link types are present in the same container: Links must only be returned for their respective type
=> feat: implement mask store

core/include/masks/trapezoid2.hpp, tests/common/include/tests/common/masks_trapezoid2.inl
Small change that caches the expensive floating point division in the is_inside function of the trapezoid mask. Seems to make vtune happier than my CPU  actually
=> feat: speedup trapezoid masks boundary check

core/include/core/mask_store.hpp
This should fix the error seen by @beomki-yeo in #117. It is rebased on top of that one.
The reason for the error is that clang complains that `std::vector` is not a `template <template>` because it has multiple template arguments. `template <template...>` does the trick.
I'm able to build fully on macOS with this branch.
=> fix: clang template template fix

.github/workflows/builds.yml
Until the algebra-plugins commits are fixed, skip the benchmark step in the CI
=> fix: skip benchmark step

core/include/core/intersection.hpp, core/include/utils/ray_gun.hpp, tests/common/include/tests/common/benchmark_intersect_all.inl, tests/common/include/tests/common/test_geometry_scan.inl, tests/unit_tests/CMakeLists.txt, tests/unit_tests/array/array_geometry_scan.cpp, tests/unit_tests/eigen/eigen_geometry_scan.cpp, tests/unit_tests/smatrix/smatrix_geometry_scan.cpp, tests/unit_tests/vc/vc_array_geometry_scan.cpp
Adds unittests that check the geometry linking consistency by shooting rays through the geometry and recording the volume portal trace. The ```ray_gun.hpp``` only records intersection paths in the direction of the ray (e_along) and checks The ray scan unittest check whether the intersection path and the volume inidces match, i.e. form a consisten chain. Only for ray origin 0 for now.
=> feat: scan geometry linking by ray scan

.github/workflows/builds.yml, core/include/geometry/surface_base.hpp, tests/common/include/tests/common/benchmark_find_volume.inl, tests/common/include/tests/common/benchmark_intersect_all.inl, tests/common/include/tests/common/io_read_detector.inl, tests/common/include/tests/common/read_geometry.hpp, tests/common/include/tests/common/test_geometry_navigation.inl, tests/common/include/tests/common/test_geometry_scan.inl, tests/common/include/tests/common/test_toy_geometry.inl, tests/common/include/tests/common/tools_navigator.inl, tests/common/include/tests/common/tools_propagator.inl, tests/unit_tests/CMakeLists.txt, tests/unit_tests/array/array_toy_geometry.cpp, tests/unit_tests/eigen/eigen_toy_geometry.cpp, tests/unit_tests/smatrix/smatrix_toy_geometry.cpp, tests/unit_tests/vc/vc_array_toy_geometry.cpp
Make a toy geometry available, that contains three volumes and a few surfaces.
Contains
- a beampipe (r = 27mm, half_z = 500mm)
- a first layer (r_min = 27mm, r_max = 38mm, half_z = 500mm) with 224  rectangular (half_x = 8.4mm, half_y = 36mm) modules at r = 32mm
- an empty layer (r_min = 38mm, r_max = 64mm, half_z = 500mm)
- a second layer (r_min = 64mm, r_max = 80mm, half_z = 500mm) with 448
rectangular (half_x = 8.4mm, half_y = 36mm) modules at r = 72mm.
returns a tuple containing the geometry objects collections: [volumes,
surfaces, transforms, disc masks (neg/pos portals), cylinder masks
(inner/outer portals), rectangle masks (modules)]
=> feat: toy geometry

CMakeLists.txt, extern/algebra-plugins/CMakeLists.txt, extern/thrust/CMakeLists.txt, extern/thrust/README.md
This PR updates to the (currently) latest version of [algebra-plugins](https://github.com/acts-project/algebra-plugins), for the benefit of #134 and #143.
It also introduces a recipe for "building" [Thrust](https://github.com/NVIDIA/thrust) as part of the project. In the same way in which all of the other externals are handled.
Note that I'm still a bit unsure what is meant to be **the** way of using Thrust with its own CMake configuration. :frowning: In this PR's setup the `Thrust::Thrust` target becomes available to use. So that might be all that we need. But according to
https://github.com/NVIDIA/thrust/blob/main/thrust/cmake/README.md
, one is not supposed to use that target directly. Rather, one should add code like the following for every target (library/executable/etc.) that wants …
=> Externals Update, main branch (2021.11.02.)

CMakeLists.txt, README.md, cmake/detray-config.cmake.in, cmake/detray-functions.cmake, extern/algebra-plugins/CMakeLists.txt, extern/benchmark/CMakeLists.txt, extern/dfelibs/CMakeLists.txt, extern/googletest/CMakeLists.txt, extern/matplotplusplus/CMakeLists.txt, extern/thrust/CMakeLists.txt, extern/vecmem/CMakeLists.txt, plugins/algebra/array/include/detray/plugins/algebra/array_definitions.hpp, plugins/algebra/eigen/CMakeLists.txt, plugins/algebra/smatrix/CMakeLists.txt, plugins/algebra/vc/CMakeLists.txt, plugins/algebra/vc/include/detray/plugins/algebra/vc_array_definitions.hpp, tests/unit_tests/core/CMakeLists.txt
This PR is a step-sibling of https://github.com/acts-project/algebra-plugins/pull/37.
Just as in https://github.com/acts-project/algebra-plugins/pull/37, I added "advanced" cache variables for setting up where the individual externals could be downloaded from.
- At the same time updated the build to [Algebra Plugins v0.3.0](https://github.com/acts-project/algebra-plugins/releases/tag/v0.3.0) and [VecMem v0.6.0](https://github.com/acts-project/vecmem/releases/tag/v0.6.0);
- With the new [Algebra Plugins](https://github.com/acts-project/algebra-plugins) version I could also simplify the array and vc plugin definitions a little bit.
As @beomki-yeo pointed out in https://github.com/acts-project/detray/pull/134#issuecomment-961672010, and as I pondered about it in #144, we can't simply use …
=> Externals and CMake Updates, main branch (2021.11.05.)

core/include/detray/core/transform_store.hpp, tests/unit_tests/cuda/transform_store_cuda_kernel.cu, tests/unit_tests/cuda/transform_store_cuda_kernel.hpp
This PR adds template parameter for `transform_store_data`
By doing this, `transform_store` constructor with `transform_store_data` doesn't require cuda macro anymore. (The current constructor requires cuda macro to avoid ambiguity from the constructor with `vecmem::memory_resource`)
=> templating transform_store_data 

core/include/detray/core/transform_store.hpp, tests/unit_tests/cuda/transform_store_cuda_kernel.cu, tests/unit_tests/cuda/transform_store_cuda_kernel.hpp
As been discuss with @krasznaa  in #150, I think it is OK for `foo_data` to take `foo` as template parameter. Let's make all classes (except mask_store with parameter pack) have unified format:)..
=> rollback the transform store

core/include/detray/definitions/detail/accessor.hpp, core/include/detray/tools/single_type_navigator.hpp, tests/common/include/tests/common/check_geometry_navigation.inl, tests/common/include/tests/common/tools_single_type_navigator.inl
This PR introduces tests for random direction navigation that runs along straight lines. It works with the single_type_navigator/toy_geometry setup:
- the directions are 100x100 rays in theta and phi steps
- the navigation state can be printed automatically by an inspector
- the indices of the objects the navigator steps onto can be recorded with a dedicated inspector
Every navigation run is checked against the intersection trace produced by the ray gun.
A few minor fixed have been made to the ```single_type_navigator.hpp``` to make its navigation status more consistent
=> feat: run random direction navigation on toy geometry

core/include/detray/core/mask_store.hpp, tests/unit_tests/cuda/mask_store_cuda_kernel.cu, tests/unit_tests/cuda/mask_store_cuda_kernel.hpp, tests/unit_tests/cuda/tuple_test_cuda_kernel.cu, tests/unit_tests/cuda/tuple_test_cuda_kernel.hpp
Some changes were made to make `mask_store_data` directly take `mask_store` as an template parameter.
This should be useful when writing `detector_data` class.
Before:
```c++
template <template <typename...> class tuple_type, typename... mask_types>
struct mask_store_data {};
```
After:
```c++
template <typename mask_store_t>
struct mask_store_data {};
```
=> Refactor `mask_store_data`

core/include/detray/utils/enumerate.hpp
Simplified the constructor of detray::iterator_range. This was necessary because CUDA (11.4) is not able to generate correct code with the previous implementation. Which only happens to show up in a full debug build (`cmake -DCMAKE_BUILD_TYPE=Debug ../detray`) during the `detray_test_array_transform_store_cuda` test.
When trying to run said test in the current main branch, I see the following:
```
[bash][Legolas]:build > ./test-bin/detray_test_array_transform_store_cuda 
Running main() from /data/ssd-1tb/projects/detray/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from transform_store_cuda
[ RUN      ] transform_store_cuda.transform_store
CUDAassert: an illegal memory …
```
=> Iterator Range Simplification, main branch (2021.11.26.)

core/CMakeLists.txt, core/include/detray/grids/axis.hpp, core/include/detray/grids/grid2.hpp, core/include/detray/tools/grid_array_helper.hpp, extern/vecmem/CMakeLists.txt, tests/unit_tests/cuda/grids_grid2_cuda.cpp, tests/unit_tests/cuda/grids_grid2_cuda_kernel.cu, tests/unit_tests/cuda/grids_grid2_cuda_kernel.hpp
In detector class, there was `vector_type<grid>`, a.k.a surfaces_finder, which is commented out now.
Since `grid` already contains `vector_type` within it, we can not utilize the vecmem interface.
So I may propose using `array_type<grid, N>`, which I added a very simple unit test for it.
The problem is that the number of surfaces finders should get into the template argument. and this will lead us to define detector-specific struct which contains (hard-coded...) the number of surfaces finders, etc.
I strongly understand that it will mess up a few things indeed... but thinking of better alternatives is beyond my knowledge honestly :(
People who is going to review this can suggest alternatives or opinions on this.
=> Add an unit test for array of grid

core/include/detray/core/detector.hpp
I suspect we don't have to generalize the name map and serializer type for detector class.
=> Refactor template parameter for detector

core/include/detray/core/detector.hpp, io/csv/include/detray/io/csv_io.hpp, tests/common/include/tests/common/benchmark_find_volume.inl, tests/common/include/tests/common/benchmark_intersect_all.inl, tests/common/include/tests/common/core_detector.inl, tests/common/include/tests/common/io_read_detector.inl, tests/common/include/tests/common/tools/create_toy_geometry.hpp, tests/common/include/tests/common/tools/detector_registry.hpp, tests/common/include/tests/common/tools/read_geometry.hpp, tests/unit_tests/cuda/detector_cuda_kernel.cu, tests/unit_tests/cuda/detector_cuda_kernel.hpp
This PR adds `surfaces_finder` into `detector`. (It is written on top of #172)
Instead passing the number of grids directly to the detector,  `detector_registry` struct which contains `enum` class for each detector is passed.
There are couple of things to be polished but early comments are welcomed
=> Add surface finder to detector class

core/include/detray/core/detector.hpp, core/include/detray/core/intersection.hpp, core/include/detray/geometry/volume.hpp, core/include/detray/tools/intersection_kernel.hpp, core/include/detray/tools/navigator.hpp, io/csv/include/detray/io/csv_io.hpp, tests/common/include/tests/common/benchmark_intersect_all.inl, tests/common/include/tests/common/check_geometry_linking.inl, tests/common/include/tests/common/check_geometry_navigation.inl, tests/common/include/tests/common/check_geometry_scan.inl, tests/common/include/tests/common/core_detector.inl, tests/common/include/tests/common/geometry_volume.inl, tests/common/include/tests/common/test_toy_geometry.inl, tests/common/include/tests/common/tools/create_toy_geometry.hpp, tests/common/include/tests/common/tools/ray_gun.hpp, tests/common/include/tests/common/tools/ray_scan_utils.hpp, tests/common/include/tests/common/tools_navigator.inl
This PR extends the toy geometry to a more realistic setup: two endcaps with three layers respectively as default. Every endcap layer consists of two rings of modules. To fit the endcap diameter, the barrel region is extended up to four layers per default. The space between the module layers is filled with gap volumes to enable navigation. The unittests are adapted to the new geometry. Within the boundaries of the available tml parameters, the number of layers can be freely configured, the minimal geometry is the beampipe.
Debugging tools were extended when needed, mostly additional output.
=> feat: Extend toy geometry

core/include/detray/core/detector.hpp, core/include/detray/core/surfaces_finder.hpp, core/include/detray/geometry/surface_base.hpp, core/include/detray/geometry/volume.hpp, tests/common/include/tests/common/test_toy_geometry.inl, tests/common/include/tests/common/tools/create_toy_geometry.hpp, tests/common/include/tests/common/tools/detector_registry.hpp, tests/common/include/tests/common/tools_navigator.inl, tests/unit_tests/cuda/detector_cuda.cpp, tests/unit_tests/cuda/detector_cuda_kernel.cu, tests/unit_tests/cuda/detector_cuda_kernel.hpp
This PR fills the surfaces_finder in toy geometry. 
I haven't figure out the best binning size of grids in surface finder, but this can be done while working on local navigation in the follow-up PRs.
Still needs to add more unit tests for this including cuda.
=> add surfaces to surface_grid

core/include/detray/grids/axis.hpp
This is something that should have been done...  
There was a dumb `boundaries` member variable in `regular` and `circular` axis. 
This PR removes it by specializing the `axis_data` for different types of axis.
=> Specialization of axis_data for different types of axis

core/include/detray/definitions/detail/accessor.hpp, tests/unit_tests/core/CMakeLists.txt, tests/unit_tests/core/tuple_accessor.cpp
This PR fixes a bug in `detail::tuple_size<thrust::tuple<T...>>` whose value is fixed to 10. 
I also added a unit test for this.
=> Fix a bug in tuple size accessor

core/include/detray/definitions/detail/accessor.hpp
I guess this should be better because `thrust::make_tuple` is obviously different from `std::make_tuple`
=> Specialize make tuple for thrust and std

core/include/detray/core/detector.hpp, core/include/detray/core/mask_store.hpp, core/include/detray/core/type_registry.hpp, core/include/detray/definitions/detail/accessor.hpp, core/include/detray/geometry/surface.hpp, core/include/detray/geometry/volume_connector.hpp, core/include/detray/tools/bin_association.hpp, core/include/detray/tools/intersection_kernel.hpp, core/include/detray/tools/volume_graph.hpp, core/include/detray/utils/generators.hpp, core/include/detray/utils/indexing.hpp, tests/common/include/tests/common/test_toy_geometry.inl, tests/common/include/tests/common/tools_intersection_kernel.inl, tests/common/include/tests/common/tools_track.inl, tests/unit_tests/cuda/mask_store_cuda.cpp, tests/unit_tests/cuda/mask_store_cuda_kernel.cu, tests/unit_tests/cuda/mask_store_cuda_kernel.hpp
Introduce a dedicated class to deal with indexing that needs to resolve type. This way the ```mask_store``` does not need to use a ```pair``` or ```tuple``` for ranged links. Also, since the surface finder infrastructure will mimic that of the masks, it will enforce more prudence in building those links
=> feat: typed indices

core/include/detray/core/surfaces_finder.hpp, core/include/detray/grids/axis.hpp, core/include/detray/grids/grid2.hpp, core/include/detray/grids/populator.hpp, tests/unit_tests/cuda/grids_grid2_cuda.cpp, tests/unit_tests/cuda/grids_grid2_cuda_kernel.cu, tests/unit_tests/cuda/grids_grid2_cuda_kernel.hpp, tests/unit_tests/cuda/mask_store_cuda.cpp, tests/unit_tests/cuda/surfaces_finder_cuda.cpp, tests/unit_tests/cuda/tuple_test_cuda.cpp
Made it possible to access constant `detray::grid2` data on a device.
I had to introduce a bunch of "const data types" to make this happen, and tweak the various `get_data(...)` functions.
- I'm fairly happy with what I did in `axis.hpp` and `populator.hpp`. Those things should not change much while improving the const correctness of all the other types.
- I'm however not all too happy with `grid2.hpp` yet. As discussed in our meeting today, I ended up creating all of the following types:
* `grid2_view`
* `const_grid2_view`
* `grid2_data`
* `const_grid2_data`
* `grid2_buffer`
- In the future we should think about merging the "const" and "non-const" types, implementing their behaviour through some clever templating.
I modified the `grid2_attach_populator` test to exercise this constant …
=> Grid2 Const Correctness, main branch (2022.02.28.)

.github/workflows/builds.yml, core/include/detray/core/detector.hpp, core/include/detray/definitions/detail/accessor.hpp, core/include/detray/definitions/units.hpp, core/include/detray/tools/base_stepper.hpp, core/include/detray/tools/intersection_kernel.hpp, core/include/detray/tools/line_stepper.hpp, core/include/detray/tools/navigator.hpp, core/include/detray/tools/propagator.hpp, core/include/detray/tools/rk_stepper.hpp, tests/benchmarks/cuda/benchmark_propagator_cuda.cpp, tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.cu, tests/common/include/tests/common/check_geometry_navigation.inl, tests/common/include/tests/common/tools/inspectors.hpp, tests/common/include/tests/common/tools_line_stepper.inl, tests/common/include/tests/common/tools_navigator.inl, tests/common/include/tests/common/tools_propagator.inl, tests/common/include/tests/common/tools_rk_stepper.inl, tests/unit_tests/cuda/navigator_cuda.cpp, tests/unit_tests/cuda/navigator_cuda_kernel.cu, tests/unit_tests/cuda/propagator_cuda.cpp, tests/unit_tests/cuda/rk_stepper_cuda.cpp, tests/unit_tests/cuda/rk_stepper_cuda_kernel.cu, tests/unit_tests/cuda/rk_stepper_cuda_kernel.hpp
In this PR, the ```navigator``` and the ```stepper```s are adapted to use a fully ```trust_level``` based communication. The navigator's intersection cache is updated according to different trust levels, which are set by a stepper (or in general actor):
- ```no_trust```: full (re-)initialization of the volume ([discard everything] and intersect every surface in that volume). Needed at least in ```init()``` call of the navigator or when entering a new volume.
- ```high_trust```: The track state was probably only altered a little, so that we can still trust that the intersections in the cache are still ordered. In this case, we only update our current target.
- ```fair_trust```: The track state was altered a lot: Re-evaluate all present intersections and re-sort them. Then disregard all …
=> exp: trust based navigation

core/include/detray/tools/line_stepper.hpp, tests/unit_tests/cuda/navigator_cuda.cpp, tests/unit_tests/cuda/navigator_cuda_kernel.cu, tests/unit_tests/cuda/navigator_cuda_kernel.hpp
Currently, cuda navigator test is running in the infinite loop.
I fixed it by replacing `stepper::state::set_pos()` with `stepper::step()`
=> Fix a bug in cuda navigator

core/include/detray/propagator/rk_stepper.hpp
Using a reference to the B-field caused undefined behavior in the host-side rk-stepper test when using the array plugin. Using pointers works, but I don't really know what the lifetimes of the stepper and the B-field are supposed to be, so lets keep it as it was and copy the B-field, until we know what the B-field access will look like eventually.
=> fix: b field access

core/CMakeLists.txt, core/include/detray/propagator/aborters.hpp, core/include/detray/propagator/base_stepper.hpp, core/include/detray/propagator/line_stepper.hpp, core/include/detray/propagator/propagator.hpp, core/include/detray/propagator/rk_stepper.hpp, tests/common/include/tests/common/tools_propagator.inl, tests/common/include/tests/common/tools_stepper.inl, tests/unit_tests/cuda/propagator_cuda.cpp, tests/unit_tests/cuda/propagator_cuda_kernel.cu, tests/unit_tests/cuda/propagator_cuda_kernel.hpp, tests/unit_tests/cuda/rk_stepper_cuda.cpp, tests/unit_tests/cuda/rk_stepper_cuda_kernel.cu, tests/unit_tests/cuda/rk_stepper_cuda_kernel.hpp
Adds a ```pathlimit_aborter``` as an actor in the ```actor_chain``` and removes the ```path_limit``` checking from the steppers. Also updates the CUDA stepper and propagator unittests to use constrained stepping. The detray and CUDA propagator tests are furthermore extended to use a ```pathlimit_aborter```, although with a limit that should not prevent the propagation of the entire toy detector.
=> feat: add pathlimit aborter

core/CMakeLists.txt, core/include/detray/definitions/track_parameterization.hpp, core/include/detray/propagator/base_stepper.hpp, core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp, core/include/detray/propagator/track.hpp, core/include/detray/utils/algebra_helpers.hpp, extern/algebra-plugins/CMakeLists.txt, plugins/algebra/array/include/detray/plugins/algebra/array_definitions.hpp, plugins/algebra/eigen/include/detray/plugins/algebra/eigen_definitions.hpp, plugins/algebra/smatrix/include/detray/plugins/algebra/smatrix_definitions.hpp, plugins/algebra/vc/include/detray/plugins/algebra/vc_array_definitions.hpp, tests/common/include/tests/common/tools/helix_gun.hpp, tests/common/include/tests/common/tools_propagator.inl, tests/common/include/tests/common/tools_stepper.inl, tests/unit_tests/cuda/propagator_cuda.cpp, tests/unit_tests/cuda/propagator_cuda_kernel.cu, tests/unit_tests/cuda/propagator_cuda_kernel.hpp
This PR adds covariance transport in RK stepper. The unit test compares the RK jacobian and analytical jacobian under the assumption of uniform magnetic field. The PR also depends on acts-project/algebra-plugins#61
I could not figure out a good error tolerance expression between two jacobians, therefore, I just set it as `(path_length * epsilon)` but we will need to find out better expression...
References: DOI:10.1007/978-3-030-65771-0 and ATL-SOFT-PUB-2009-002
Now depends on #245 
~~Also found an issue (acts-project/vecmem#175) with `matrix<double,8,8>` type in device-to-host copy~~ << It was just my bad. It does work well after replacing `vecmem::cuda::copy` with `vecmem::copy`
Unit test has been updated. However, when I increased the number of test tracks with `theta_steps` and …
=> Add covariance transport in RK stepper

core/CMakeLists.txt, core/include/detray/grids/axis.hpp, core/include/detray/grids/grid2.hpp, core/include/detray/utils/type_traits.hpp, tests/unit_tests/cuda/grids_grid2_cuda.cpp
Made it possible to use non-const grid2 data with a const_grid2_view. Which can make life a lot easier for passing non-const objects to functions that "only" need a const view of the data.
I bumped into this while working with the [traccc](https://github.com/acts-project/traccc) code, and trying to update it to be "more const correct".
I copied the `is_same_nc` trait from [vecmem](https://github.com/acts-project/vecmem) to do this for `traccc::axis_data` in the same way in which this auto-conversion is set up for `vecmem::data::vector_view` and friends.
Finally I updated the CUDA test to exercise this auto-conversion explicitly. Though I guess it should also be added to a host-only test... :thinking:
=> Grid2 Const Conversion, main branch (2022.04.27.)

core/include/detray/grids/grid2.hpp, tests/unit_tests/cuda/grids_grid2_cuda_kernel.cu
Made the `grid2::bin` functions return correct types in "every situation". The constant versions of these functions in device code were not returning the correct types so far. Resulting in the following warning (in this case from CUDA/nvcc) when the constant versions of these functions got called:
```
/home/krasznaa/ATLAS/projects/detray/detray/core/include/detray/grids/grid2.hpp(180): warning #430-D: returning reference to local temporary
detected during instantiation of "const auto &detray::grid2<populator_t, axis_p0_t, axis_p1_t, serializer_t, vector_t, jagged_vector_t, array_t, tuple_t, value_t, kSORT, kDIM>::bin(detray::dindex, detray::dindex) const [with populator_t=detray::attach_populator, axis_p0_t=detray::axis::circular, axis_p1_t=detray::axis::regular, …
```
=> Grid2 Const Correctness, main branch (2022.04.28.)

CMakeLists.txt
Updated the project version to `0.8`.
I only noticed while creating a new VecMem tag that the project version in this repo was not kept up to date with the releases/tags made in the repository. :frowning:
It's not a tragedy, but let's keep this version updated in the future. :wink:
=> Project Version Update, main branch (2022.05.03.)

core/include/detray/grids/grid2.hpp
Can we add this additional `host_resource` to grid2_buffer? 
It will allow for the buffer to be constructed with `device resource`. Otherwise, it wouldn't be possible since `jagged_vector_buffer` always needs a host accessible memory resource.
pinging @krasznaa
=> Add host accessible memory resource to grid2 buffer

tests/benchmarks/cuda/CMakeLists.txt, tests/unit_tests/cuda/CMakeLists.txt
Updated Detray's CMake requirement to 3.18. It is needed for C++17 support in the CUDA code, as described in:
https://cmake.org/cmake/help/latest/prop_tgt/CUDA_STANDARD.html
As we found with @niermann999, using an older CMake version like 3.17 will silently set the CUDA build to C\+\+14, leading to mysterious build failures. :frowning:
I could've set the requirement just for the subdirectories that deal with CUDA. But I thought it would probably not be worth complicating the code like that. Hopefully every user is okay with using CMake 3.18+, even if they're not using CUDA...
=> CMake Requirement Update, main branch (2022.06.10.)

core/include/detray/propagator/aborters.hpp, core/include/detray/propagator/actor_chain.hpp, core/include/detray/propagator/base_actor.hpp, core/include/detray/propagator/base_stepper.hpp, core/include/detray/propagator/navigation_policies.hpp, tests/common/include/tests/common/tools/inspectors.hpp, tests/common/include/tests/common/tools_actor_chain.inl, tests/common/include/tests/common/tools_guided_navigator.inl, tests/common/include/tests/common/tools_propagator.inl, tests/unit_tests/cuda/propagator_cuda.cpp, tests/unit_tests/cuda/propagator_cuda_kernel.cu, tests/unit_tests/cuda/propagator_cuda_kernel.hpp
Adds a call of chained actors to the ```actor_chain``` test as an example
=> feat: add example of chained actors

core/include/detray/intersection/detail/trajectories.hpp, core/include/detray/intersection/intersection.hpp, core/include/detray/propagator/aborters.hpp, core/include/detray/propagator/base_stepper.hpp, core/include/detray/propagator/navigation_policies.hpp, core/include/detray/propagator/navigator.hpp, core/include/detray/propagator/propagator.hpp, tests/common/include/tests/common/check_geometry_linking.inl, tests/common/include/tests/common/check_geometry_navigation.inl, tests/common/include/tests/common/test_telescope_detector.inl, tests/common/include/tests/common/tools/create_toy_geometry.hpp, tests/common/include/tests/common/tools/inspectors.hpp, tests/common/include/tests/common/tools/particle_gun.hpp, tests/common/include/tests/common/tools/ray_scan_utils.hpp, tests/common/include/tests/common/tools_guided_navigator.inl, tests/common/include/tests/common/tools_navigator.inl, tests/common/include/tests/common/tools_propagator.inl, tests/common/include/tests/common/tools_stepper.inl, tests/unit_tests/cuda/navigator_cuda.cpp, tests/unit_tests/cuda/propagator_cuda.cpp, tests/unit_tests/cuda/propagator_cuda_kernel.hpp
Restructured the navigator
- 'high trust' only checks current candidate then escalates trust level
- intersection distances are sorted using std::abs
- more constness in a lot of places
- propagation unittest does not set stepper constraints in test using B-field in z-direction anymore
- additional call to actor chain after navigator init() to catch early aborter actions
- adds an overstep tolerance to the ray trajectory
- adds new helix based navigation test (still fails for larger number of test tracks)
- some renaming to distinguish between a parametrized trajectory (e.g. ray/helix) and a track state as used in the propagation
- the overlap in the toy geometry endcap modules is temporarily solved by shrinking the modules
=> fix: navigation issues

core/include/detray/intersection/cylinder_intersector.hpp, core/include/detray/intersection/intersection.hpp, core/include/detray/intersection/line_intersector.hpp, core/include/detray/intersection/plane_intersector.hpp, core/include/detray/materials/material_rod.hpp, core/include/detray/materials/material_slab.hpp, tests/common/include/tests/common/materials.inl, tests/common/include/tests/common/tools_cylinder_intersection.inl, tests/common/include/tests/common/tools_line_intersection.inl, tests/common/include/tests/common/tools_planar_intersection.inl
This PR adds the incidence angle calculation in `plane_intersector` and `cylinder_intersector`. It is used in the calculation of interaction length of `material_slab`. (Similar functionality already exists in ACTS as `pathCorrection` function)
For `line_intersector` with `material_rod`, the incidence angle is not required as the interaction length is simply given by `2 * sqrt(R^2 - d^2)`.
=> Incidence angle and interaction length

core/include/detray/intersection/line_intersector.hpp, tests/common/include/tests/common/tools_line_intersection.inl
Added a sign to line intersection as ACTS does. This is required when we recover the global position from local-to-global transform.
negative sign is given when the track intersects the line in the right side, and vice versa.
=> Add sign to line intersection

CMakeLists.txt, extern/covfie/CMakeLists.txt, extern/covfie/README.md, tests/unit_tests/CMakeLists.txt, tests/unit_tests/covfie/CMakeLists.txt, tests/unit_tests/covfie/constant_field.cpp
This pull requests serves as the first step towards integrating covfie into detray. To that end, it adds covfie as a fetched dependency in the detray build system, so that the necessary source code is automatically downloaded and integrated into detray's CMake configuration. On top of that, we also add a very simple test application which shows that the code compiles correctly, and gives some hints on how it can be used.
=> Integrate covfie into the build system and add tests

CMakeLists.txt, extern/covfie/CMakeLists.txt
By request of @krasznaa, this commit makes three changes:
1. Updates covfie to version 0.3.0;
2. Silences warnings about missing compiler features;
3. Allow use of existing covfie installations.
=> Change CMake logic for integrating covfie

extern/actsvg/CMakeLists.txt, extern/algebra-plugins/CMakeLists.txt, extern/benchmark/CMakeLists.txt, extern/covfie/CMakeLists.txt, extern/dfelibs/CMakeLists.txt, extern/googletest/CMakeLists.txt, extern/thrust/CMakeLists.txt, extern/vecmem/CMakeLists.txt
Explicitly set the [CMP0135 policy](https://cmake.org/cmake/help/latest/policy/CMP0135.html). This is to silence the following new warning that showed up when using CMake 3.24.
```
CMake Warning (dev) at /atlas/software/cmake/3.24.1/x86_64-ubuntu2004-gcc9-opt/share/cmake-3.24/Modules/FetchContent.cmake:1264 (message):                                                                        
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is                              
not set.  The policy's OLD behavior will be used.  When using a URL                                    
download, the timestamps of extracted files should preferably be that of                               
the time of extraction, otherwise code that depends on the extracted …
```
=> CMake 3.24 Compatibility, main branch (2022.09.13.)

CMakeLists.txt
Made the code set up the `detray::Thrust` target under all circumstances.
If [Thrust](https://github.com/NVIDIA/thrust) is provided by the project that is building Detray "as a part of itself", we still need to create the `detray::Thrust` target. (At that point the `thrust_create_target(...)` function needs to be provided by the "parent project".)
This is in preparation of [traccc](https://github.com/acts-project/traccc) making use of [Thrust](https://github.com/NVIDIA/thrust) as well.
=> Thrust Setup Update, main branch (2022.09.13.)

core/include/detray/utils/ranges/iota.hpp, tests/common/include/tests/common/tools/track_generators.hpp
This should fix the clang deprecation warning about std::iterator inheritance. The required typedefs are set by hand for the track generator and iota views, the same way as for the other views
=> ref: Remove std::iterator inheritance as it is deprecated in c++17

tests/common/include/tests/common/tools/simulator.hpp
Currently the `event_writer` is performed before the `parameter_resetter` which updates the free track parameters.
Since the hit object is constructed from the free track parameters (see the codes below), `event_writer` should be called after the `parameter_resetter`
https://github.com/acts-project/detray/blob/6e896b15dadbb89c1052075ceab0dd354347d9aa/tests/common/include/tests/common/tools/event_writer.hpp#L86-L98
=> Move event writer to the end of actor chain

CMakeLists.txt, extern/nlohmann_json/CMakeLists.txt, extern/nlohmann_json/README.md, io/CMakeLists.txt, io/json/CMakeLists.txt, io/json/include/detray/io/json_algebra_io.hpp, io/json/include/detray/io/json_defs.hpp, io/json/include/detray/io/json_geometry_io.hpp, io/json/include/detray/io/json_grids_io.hpp, io/json/include/detray/io/json_io.hpp, io/json/include/detray/io/json_material_io.hpp, io/json/include/detray/io/json_utilities_io.hpp, io/payload/CMakeLists.txt, io/payload/include/detray/io/io_payload.hpp, tests/unit_tests/CMakeLists.txt, tests/unit_tests/io/CMakeLists.txt, tests/unit_tests/io/io_json_payload.cpp
This PR adds the necessary infrastructure to load detectors geometries from ACTS/Core to detray.
It adds the `nlohmann` library, and and io layer for payload objects that contain all the information that will allow us to construct the `detray::detector` representing an `Acts::Experimental::Detector` object to the same detail.
It will be followed by a PR adding the actual construction code which then will be templated into the `algebra-plugin` and `vecmem` backend.
=> feat: json detector io

tests/common/include/tests/common/material_interaction.inl, utils/include/detray/simulation/event_writer.hpp, utils/include/detray/simulation/measurement_smearer.hpp, utils/include/detray/simulation/random_scatterer.hpp, utils/include/detray/simulation/simulator.hpp
Currently, the random sequence  of simulator is not reproducible which makes it hard to debug the traccc kalman filtering.
In this PR, I made the random sequence reproducible for every run.
=> Fix the Seed of Simulator

core/include/detray/core/detector.hpp, core/include/detray/definitions/geometry.hpp, core/include/detray/definitions/grid_axis.hpp, core/include/detray/geometry/detector_volume.hpp, core/include/detray/geometry/surface.hpp, core/include/detray/surface_finders/grid/detail/axis_binning.hpp, core/include/detray/surface_finders/grid/detail/axis_bounds.hpp, io/json/include/detray/io/json_geometry_io.hpp, io/json/include/detray/io/json_grids_io.hpp, io/payload/include/detray/io/io_payload.hpp, tests/common/include/tests/common/core_detector.inl, tests/common/include/tests/common/geometry_volume.inl, tests/common/include/tests/common/path_correction.inl, tests/unit_tests/io/io_json_payload.cpp, utils/include/detray/detectors/create_telescope_detector.hpp, utils/include/detray/detectors/create_toy_geometry.hpp
Makes the type enums of axes, surfaces and volumes accessible from headers in the definition folder. Also add an enum for the volume shape, which is used to determine how to interpret the values in the volume bounds array.
It uses the detray internal enums for e.g. the axis labels directly in the json/io payloads and adds the id for the surface type, which needs to be supplied from the outside.
=> ref: move geometry and axis enums to definitions

core/CMakeLists.txt, core/include/detray/core/detail/multi_store.hpp, core/include/detray/core/detail/single_store.hpp, core/include/detray/core/detector.hpp, core/include/detray/geometry/detector_volume.hpp, core/include/detray/masks/masks.hpp, core/include/detray/tools/grid_builder.hpp, core/include/detray/tools/surface_factory.hpp, core/include/detray/tools/surface_factory_interface.hpp, core/include/detray/tools/volume_builder.hpp, core/include/detray/tools/volume_builder_interface.hpp, core/include/detray/utils/ranges/single.hpp, tests/common/include/tests/common/core_detector.inl, tests/common/include/tests/common/grid_grid_builder.inl, utils/include/detray/detectors/detector_metadata.hpp
Adds a basic factory class that will produce surfaces with their masks, set  their links and add them to a given collection of geometry data containers. It can handle portal, sensitive and passive surfaces, but still needs a wrapper to be mapped to the detector mask types. Material needs to be added in a dedicated material volume builder in a later PR.
=> feat: surface factories

core/include/detray/propagator/constrained_step.hpp
Add static cast to step direction to silence compiler warning when compiling c++ 20
=> fix: static_cast step direction to avoid compiler warning

extern/algebra-plugins/CMakeLists.txt
Update algebra-plugins to version 0.17.0 to pull in the fixed assert, which should allow to run the ```cmath``` plugin in the ```line``` unittest again, and the clean up of implicit conversions, which is needed to pass #372 through the CI
=> Update algebra-plugins to version 0.17.0

core/include/detray/core/detail/container_views.hpp, core/include/detray/core/detail/single_store.hpp, core/include/detray/core/detail/tuple_container.hpp
This adds a ```const``` specilization for the ```is_device_view``` trait and restores the constructors in the ```single_store``` class
=> fix: add const specialization for is_device_view trait

tests/common/include/tests/common/check_simulation.inl, tests/simulation/run_simulation.cpp, utils/include/detray/simulation/simulator.hpp, utils/include/detray/simulation/track_generators.hpp
The random track generator didn't work in `simulator` class because its `track_generator` could not have copy constructor. I changed it to the reference to make it work
=> Change random track generator member variable to the reference

core/include/detray/propagator/navigator.hpp, core/include/detray/propagator/propagator.hpp, tests/benchmarks/cuda/benchmark_propagator_cuda.cpp, tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.cu, tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.hpp, tests/common/include/tests/common/tools_propagator.inl, utils/include/detray/simulation/event_writer.hpp
This PR adds `propagate_sync` function to synchronize the actor operations on the sensitive surfaces. The motivation is to reduce the thread divergence in the actor operations on the sensitive surface which can be inefficient for combinatorial kalman filtering. 
But there is also a price to pay for this; there will be another thread divergence where the threads that already reached the sensitive surface need to wait for the others which are still propagating. And it will get worse in the case that a constraint step size is small.
The benchmark result with `benchmark_propagator` shows ~10 % improvement though, which is not bad.  We will need to investigate how the performance changes in the various setups.
```
----------------------------------------------------------------------
Benchmark …
```
=> Add `propagate_sync` function for thread synchornization

core/include/detray/propagator/actors/aborters.hpp, core/include/detray/propagator/rk_stepper.ipp
Removed the `printf(...)` statements that prevent using the code making those calls in SYCL kernels. Currently any modern oneAPI version, as long as you try to compile "not only" for an NVIDIA backend, would fail like:
```
[ 68%] Building SYCL object device/sycl/CMakeFiles/traccc_sycl.dir/src/fitting/fitting_algorithm.sycl.o
In file included from /data/ssd-1tb/projects/traccc/traccc/device/sycl/src/fitting/fitting_algorithm.sycl:17:
In file included from /data/ssd-1tb/projects/traccc/build/_deps/detray-src/core/include/detray/propagator/rk_stepper.hpp:113:
/data/ssd-1tb/projects/traccc/build/_deps/detray-src/core/include/detray/propagator/rk_stepper.ipp:244:69: error: SYCL kernel cannot call a variadic function
printf("Stepper: step size is too small. will break. \n");
^
... …
```
=> Remove Problematic printf-s, main branch (2023.02.24.)

core/include/detray/propagator/propagator.hpp, tests/common/include/tests/common/check_simulation.inl, utils/include/detray/simulation/random_scatterer.hpp, utils/include/detray/simulation/simulator.hpp
If an actor changes the track state after initial navigation, re-navigation is needed. This PR adds an additional call to the navigator after the actor chain runs and modifies the random_scatterer, so that it reduces the trust level to request the navigator to update the current candidate.
=> ref: additional navigation call after random scattering

core/include/detray/masks/masks.hpp, core/include/detray/masks/unbounded.hpp, tests/common/include/tests/common/masks_unbounded.inl, tests/common/include/tests/common/masks_unmasked.inl, tests/common/include/tests/common/tools_planar_intersection.inl, tests/unit_tests/cpu/array/CMakeLists.txt, tests/unit_tests/cpu/array/array_unbounded.cpp, tests/unit_tests/cpu/eigen/CMakeLists.txt, tests/unit_tests/cpu/eigen/eigen_unbounded.cpp, tests/unit_tests/cpu/smatrix/CMakeLists.txt, tests/unit_tests/cpu/smatrix/smatrix_unbounded.cpp, tests/unit_tests/cpu/vc/CMakeLists.txt, tests/unit_tests/cpu/vc/vc_array_unbounded.cpp, utils/include/detray/detectors/detector_metadata.hpp
Introduces an unbounded shape that takes all necessary definitions, e.g. ```local_frame``` or ```intersector```, from the shape type it wraps, but replaces the ```check_bounds``` so that it always returns ```true```.
=> feat: re-introduce unbounded mask

core/include/detray/masks/masks.hpp, tests/common/include/tests/common/check_simulation.inl, tests/common/include/tests/common/line_stepper.inl, tests/common/include/tests/common/material_interaction.inl, tests/common/include/tests/common/test_telescope_detector.inl, tests/common/include/tests/common/tools_guided_navigator.inl, utils/include/detray/detectors/create_telescope_detector.hpp, utils/include/detray/detectors/detector_metadata.hpp
This adds a template to the telescope geometry that defines the module surface shape. The mask has to be passed to the ```create_telescope_detector``` function directly.
=> ref: generalize telescope to switch module shape

core/include/detray/intersection/cylinder_intersector.hpp, core/include/detray/propagator/actors/aborters.hpp, core/include/detray/propagator/rk_stepper.hpp, tests/common/include/tests/common/path_correction.inl, tests/common/include/tests/common/tools/inspectors.hpp, tests/common/include/tests/common/tools_guided_navigator.inl, utils/include/detray/detectors/create_telescope_detector.hpp
Switch the pathcorrection unittest to use the telescope detector. With the portals around the test surface and the target aborter, propagation is now possible without a special actor.
=> ref: pathcorrection unittest runs on telescope detector

core/include/detray/propagator/actors/parameter_resetter.hpp, core/include/detray/propagator/actors/parameter_transporter.hpp
This is for the CKF developmet in traccc
=> Set surface link in `parameter_transporter` instead of  `parameter_resetter`

core/include/detray/definitions/detail/algorithms.hpp, core/include/detray/utils/sort.hpp, tests/unit_tests/core/utils_sort.cpp
@niermann999 and myself were profiling the propagation kernels in detray and discovered significant overhead originating from calls to Thrust functions in device code. In particular, a call to `thrust::sort` was performing a sorting algorithm with non-constant spatial overhead, meaning it had to allocate memory on the device side, which is quite slow. This commit changes the sorting to use a hand-rolled implementation of selection sort. Note that it also changes the use of insertion sort to selection sort elsewhere, as insertion sort has an average of O(n<sup>2</sup>) swaps (which access global memory) compared to the average of O(n) swaps that selection sort requires.
=> perf: Remove Thrust calls inside kernels

cmake/detray-config.cmake.in
This is a twin of https://github.com/acts-project/algebra-plugins/pull/96, fixing the issue described in https://github.com/acts-project/algebra-plugins/issues/36, and helping with https://github.com/acts-project/traccc/pull/364.
See https://github.com/acts-project/algebra-plugins/pull/96 for an explanation of this change.
=> CMake Export Fix, main branch (2023.03.24.)

io/json/CMakeLists.txt
This was a real pain in the ass to find and fix for acts-project/traccc#364, but as it turns out `nlohmann_json` is not actually a valid target, and the library has been exporting its targets in a dedicated namespace since version 3.2. CMake expectedly handles this poorly and translates it to a `-lnlohmann_json` flag if the target is not available, leading to compilation errors. This commit applies the namespace to resolve this issue.
=> Refer to `nlohmann_json` target by namespace

tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
Google Benchmark has this cute feature where you can give it user-defined counters and it will print additional information to the command line. This commit adds a counter for the number of tracks processed, so it will tell us the propagation throughput as well as the raw runtime statistics.
Example output is as follows:
```
--------------------------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations UserCounters...
--------------------------------------------------------------------------------------
CUDA unsync propagation/8      6457762 ns      6443469 ns           97 TracksPropagated=9.93254k/s
CUDA unsync propagation/16     6121909 ns      6106323 ns          114 TracksPropagated=41.9238k/s
CUDA unsync …
```
=> feat: Add throughput to propagation benchmarks

core/CMakeLists.txt, core/include/detray/propagator/propagator.hpp, core/include/detray/utils/axis_rotation.hpp, core/include/detray/utils/unit_vectors.hpp, tests/common/include/tests/common/axis_rotation.inl, tests/common/include/tests/common/utils_unit_vectors.inl, tests/unit_tests/cpu/array/CMakeLists.txt, tests/unit_tests/cpu/array/array_unit_vectors.cpp, tests/unit_tests/cpu/eigen/CMakeLists.txt, tests/unit_tests/cpu/eigen/eigen_unit_vectors.cpp, tests/unit_tests/cpu/smatrix/CMakeLists.txt, tests/unit_tests/cpu/smatrix/smatrix_unit_vectors.cpp, tests/unit_tests/cpu/vc/CMakeLists.txt, tests/unit_tests/cpu/vc/vc_array_unit_vectors.cpp, utils/include/detray/simulation/random_scatterer.hpp
Copied from `UnitVectors.hpp` of ACTS core.
Update: I found that the curvilinear vector used in `random_scatterer` was not normlized and made wrong results. After fixing it, the `check_simulation` didn't pass the unit test, which was because the navigator was not updated after the first call of actors. So I added `update()` after the `run_actors()` of `propagate()` function
=> Add make_curvilinear_unit_vector function and fix some bugs

tests/scripts/run_benchmarks.sh
Specified the versions of the used Python packages explicitly for the benchmark. Took the versions from the last CI job that was successful. (https://github.com/acts-project/detray/actions/runs/4597364526/jobs/8119958557)
=> CI Benchmark Fix, main branch (2023.03.04.)

core/include/detray/materials/detail/density_effect_data.hpp, core/include/detray/materials/detail/relativistic_quantities.hpp, tests/common/include/tests/common/material_interaction.inl, tests/common/include/tests/common/materials.inl
Here are some bug fix/improvement in energy loss
1. Set the default value of density effect data to zero (With epsilon it is hard to declare a material without density effect data because of `unit::eV` multiplication to `m_I` )
2. Multiply 1000 to plasma energy
=> Improve energy loss

core/include/detray/core/detector.hpp, core/include/detray/geometry/detector_volume.hpp, core/include/detray/propagator/navigator.hpp, core/include/detray/surface_finders/brute_force_finder.hpp, core/include/detray/surface_finders/grid/grid.hpp, core/include/detray/tools/volume_builder.hpp, utils/include/detray/detectors/create_telescope_detector.hpp
As a first try, until the grids are available, sets the number to an arbitrary value that works for the current testing detectors. Obviously, this is just a hotfix and will be corrected in the future.
=> ref: Reduce size of navigator memory alloc

core/include/detray/core/detector.hpp, tests/common/include/tests/common/check_simulation.inl, utils/include/detray/simulation/event_writer.hpp
This PR uses the detray geometry barcode as geometry_id in the csv event writer instead of the surface index.
=> ref: use barcode in event writer

core/include/detray/coordinates/cartesian2.hpp, core/include/detray/coordinates/coordinate_base.hpp, core/include/detray/coordinates/cylindrical2.hpp, core/include/detray/coordinates/line2.hpp, core/include/detray/coordinates/polar2.hpp, core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/line_stepper.hpp, core/include/detray/propagator/rk_stepper.hpp, tests/common/include/tests/common/covariance_transport.inl
I found that ACTS has fully implemented path correction that I wrote in #425 (yeah there was no missing term)
Its implementation is also better than my implementation in detray so I refactored it.
There is no change in the algorithm while the interface of `coordinate_base` is way better now
The covariance transport test for polar, cylinder, and line will follow in the next PR
=> Refactor the path correction and support line coordinate as well

tests/common/include/tests/common/tools/intersectors/helix_cylinder_intersector.hpp, tests/common/include/tests/common/tools/intersectors/helix_line_intersector.hpp, tests/common/include/tests/common/tools/intersectors/helix_plane_intersector.hpp
I don't think we need multiplier (or safety factor I guess?) in the path length of helix intersector as long as CI is OK
=> Remove multipliers in path length of helix intersector

core/include/detray/coordinates/cartesian2.hpp, core/include/detray/coordinates/coordinate_base.hpp, core/include/detray/coordinates/cylindrical2.hpp, core/include/detray/coordinates/line2.hpp, core/include/detray/coordinates/polar2.hpp
This PR is taken from #457. I just wanted to fix a bug in line coordinate quickly :p
=> Add transform3 type definitions and fix a bug in line coordinate

core/include/detray/materials/predefined_materials.hpp
I prefer having the explicit multiplier because I want to leave the numbers from the PDG intact.
=> Explicit multiplier of two for atomic number of diatomic molecules

core/include/detray/intersection/detail/trajectories.hpp, core/include/detray/tracks/bound_track_parameters.hpp, core/include/detray/tracks/detail/track_helper.hpp, core/include/detray/tracks/free_track_parameters.hpp, tests/common/include/tests/common/tools/intersectors/helix_cylinder_intersector.hpp, tests/unit_tests/cpu/tools_helix_trajectory.cpp
The motivation for this PR is to construct a ray with `free_vector` (Required for CKF). The constructors for both ray and helix also refactored  consistently
Also I removed the inheritance of free_track_parameter in helix class. I thought it is pretty weird that we are calling the free track parameter constructor which creates a covariance matrix
=> refactor ray and helix

tests/common/include/tests/common/tools/intersectors/helix_cylinder_intersector.hpp, tests/common/include/tests/common/tools/intersectors/helix_plane_intersector.hpp, tests/unit_tests/cpu/covariance_transport.cpp
This PR refactors covariance transport test to include the other mask types.
The test itself remains the same - deploy the surfaces over the loop and do the propagation for one loop and check that we get the same covariance matrix.
The major change is that the first surface is fixed to be the rectangle regardless of the tested mask type. Otherwise it is hard to propagate the exact one loop for cylinder or line types.
=> Refactor covariance transport test and Add more cases

core/include/detray/utils/ranges.hpp, core/include/detray/utils/ranges/pointer.hpp, tests/unit_tests/core/utils_ranges.cpp, tests/unit_tests/device/cuda/utils_ranges_cuda.cpp, tests/unit_tests/device/cuda/utils_ranges_cuda_kernel.cu, tests/unit_tests/device/cuda/utils_ranges_cuda_kernel.hpp
Implement an iterator view that acts like 'single' https://en.cppreference.com/w/cpp/ranges/single_view but does not take ownership of the value. This is used in grids that can hold only one element per bin (like for example the volume grid) but still need to be compatible with the same interfaces as grids that hold iterable collections of data per bin. Previously, I used the ```single``` view for this, but this resulted in a dangling reference and also meant, the grid would copy the value in the bin at every lookup.
=> grid: non-owning single view

core/include/detray/utils/ranges.hpp, core/include/detray/utils/ranges/join.hpp, core/include/detray/utils/ranges/static_join.hpp, tests/unit_tests/core/utils_ranges.cpp, tests/unit_tests/device/cuda/utils_ranges_cuda.cpp, tests/unit_tests/device/cuda/utils_ranges_cuda_kernel.cu, tests/unit_tests/device/cuda/utils_ranges_cuda_kernel.hpp
Implement a join iterator that operates on a range of inner iterators. The previous join iterator, which could only hold a number of inner iterators that was defined at compile-time, has been renamed to 'static_join'. This join iterator is used to iterate over bins that contain a collection of data as if it were one bin and can hence emulate the behavior of the final grid implementation, while making it possible to keep the navigation untouched. Since all bins can be checked with this iterator in the same search call, all surfaces in the volume are tested, as before, and no changes in the navigation logic will occur by #456
=> grid: join view

core/include/detray/core/detector.hpp, core/include/detray/geometry/detail/volume_descriptor.hpp, core/include/detray/geometry/detector_volume.hpp, core/include/detray/tools/bin_fillers.hpp, core/include/detray/tools/grid_builder.hpp, core/include/detray/tools/volume_builder.hpp, core/include/detray/tools/volume_builder_interface.hpp, tests/common/include/tests/common/test_toy_detector.hpp, tests/unit_tests/cpu/core_detector.cpp, tests/unit_tests/cpu/grid_grid_builder.cpp, utils/include/detray/detectors/create_telescope_detector.hpp, utils/include/detray/detectors/create_toy_geometry.hpp
Adds transforms to the volumes, so that rotations and translations of the volume can be properly included when switching to grid local coordinates for the axes lookup during local navigation. The volume transforms are the first to be added to the transform store respectively and are non contextual (don't need alignment) like the portal transforms that follow immediately after. The volume transforms are also added by a few new methods (```add_volume_placement```) to the volume builders.
Since the transform indices change with the extra transforms in the transform store, the unittests have been adapted. Furthermore, the index updates in the grid filling for the toy detector was simplified/corrected (e.g. ```global_to_local``` in the bin filler can now use proper transform) and the volume …
=> feat: volume placement transforms

io/include/detray/io/common/geometry_writer.hpp
After adding the placement transforms to the volumes, fetch them and write them to file in the geometry writer.
=> fix: write volume transform to file

core/include/detray/geometry/detail/volume_kernels.hpp, core/include/detray/geometry/detector_volume.hpp
Move the kernels used in the detector volume class to their own file.
=> ref: move volume kernels to own file

core/include/detray/propagator/navigator.hpp
Removes the ```if constexpr``` code from the navigator and puts it into the ```run_inspector``` method of the navigation state
=> ref: navigator inspector calls

.github/workflows/builds.yml, .github/workflows/checks.yml
As it stands, an arbitrary number of CI jobs can be running for a given pull request, which means that sometimes the CI will be running for a commit that has been superceded by several newer commits. Adding a concurrency group to the CI jobs allows GitHub to automatically cancel old jobs if a new commit is pushed that makes the run obsolete.
=> Add concurrency group for CI jobs

core/include/detray/geometry/surface.hpp, core/include/detray/intersection/concentric_cylinder_intersector.hpp, core/include/detray/intersection/cylinder_intersector.hpp, core/include/detray/intersection/cylinder_portal_intersector.hpp, core/include/detray/intersection/intersection.hpp, core/include/detray/intersection/intersection_kernel.hpp, core/include/detray/intersection/line_intersector.hpp, core/include/detray/intersection/plane_intersector.hpp, core/include/detray/propagator/actors/aborters.hpp, core/include/detray/propagator/actors/parameter_resetter.hpp, core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/actors/pointwise_material_interactor.hpp, core/include/detray/propagator/navigator.hpp, core/include/detray/utils/inspectors.hpp, tests/common/include/tests/common/tools/intersectors/helix_cylinder_intersector.hpp, tests/common/include/tests/common/tools/intersectors/helix_line_intersector.hpp, tests/common/include/tests/common/tools/intersectors/helix_plane_intersector.hpp, tests/common/include/tests/common/tools/particle_gun.hpp, tests/common/include/tests/common/tools/ray_scan_utils.hpp, tests/unit_tests/cpu/check_geometry_navigation.cpp, tests/unit_tests/cpu/tools_guided_navigator.cpp, tests/unit_tests/cpu/tools_intersection_kernel.cpp, tests/unit_tests/cpu/tools_navigator.cpp, utils/include/detray/simulation/event_writer.hpp, utils/include/detray/simulation/random_scatterer.hpp
Use the surface interface in the navigation state directly to simplify some client code. Also removes the ```_object_index``` from the navigator state, which allowed to get rid of the ```set_sate``` method. Updates the names of the navigation state members
=> ref: surface interface in navigation state

core/include/detray/intersection/detail/trajectories.hpp, tests/unit_tests/cpu/check_geometry_scan.cpp, tests/unit_tests/cpu/check_simulation.cpp, tests/unit_tests/cpu/line_stepper.cpp, tests/unit_tests/cpu/material_interaction.cpp, tests/unit_tests/cpu/test_telescope_detector.cpp, tests/unit_tests/cpu/tools_guided_navigator.cpp, tests/unit_tests/io/io_json_detector_writer.cpp, tutorials/src/cpu/detector/build_predefined_detectors.cpp, utils/include/detray/detectors/create_telescope_detector.hpp
Adds a config structure to the telescope geometry, which reduces the number of overloaded ```create_telescope_detector``` functions and allows more flexible configuration of the detector. The functionality of the telescope detector stays the same.
=> ref: telescope detector config

core/include/detray/tools/cuboid_portal_generator.hpp, core/include/detray/tools/grid_builder.hpp, core/include/detray/tools/material_builder.hpp, core/include/detray/tools/material_factory.hpp, core/include/detray/tools/surface_factory.hpp, core/include/detray/tools/surface_factory_interface.hpp, core/include/detray/tools/volume_builder.hpp, core/include/detray/tools/volume_builder_interface.hpp, tests/unit_tests/cpu/CMakeLists.txt, tests/unit_tests/cpu/grid_grid_builder.cpp, tests/unit_tests/cpu/tools_material_builder.cpp, tutorials/include/detray/tutorial/square_surface_generator.hpp
This PR adds a material builder and factory for homogeneous material slabs or material rods per surface. The surface factory interface is complemented by a decorator that the material factory extends, so that the material data can be added after the surface data has already been read in. It is then handed to the material builder, which either constructs material rods or slabs (depending on the type id it is given), adds them to the detector material store and updates the surface material links accordingly.
A unit and integration test for the material factory and builder were added, too.
=> feat: material builders

core/include/detray/core/detector.hpp, core/include/detray/materials/predefined_materials.hpp, core/include/detray/tools/detector_builder.hpp, core/include/detray/tools/material_builder.hpp, core/include/detray/tools/material_factory.hpp, io/include/detray/io/common/detail/detector_components_io.hpp, io/include/detray/io/common/detail/utils.hpp, io/include/detray/io/common/detector_reader.hpp, io/include/detray/io/common/geometry_reader.hpp, io/include/detray/io/common/geometry_writer.hpp, io/include/detray/io/common/homogeneous_material_reader.hpp, io/include/detray/io/common/homogeneous_material_writer.hpp, io/include/detray/io/common/io_interface.hpp, io/include/detray/io/common/payloads.hpp, io/include/detray/io/json/json_geometry_io.hpp, io/include/detray/io/json/json_header_io.hpp, io/include/detray/io/json/json_material_io.hpp, io/include/detray/io/json/json_reader.hpp, io/include/detray/io/json/json_serializers.hpp, tests/common/include/tests/common/test_toy_detector.hpp, tests/unit_tests/cpu/materials.cpp, tests/unit_tests/io/io_json_detector_reader.cpp, tests/unit_tests/io/io_json_payload.cpp, tutorials/src/cpu/detector/detector_to_dot.cpp, tutorials/src/cpu/detector/read_detector_from_file.cpp
Adds the material reader and connects it to the geometry reader by providing
the read_detector function, which corresponds to the write_detector function.
Since the detector builder works volume-by-volume, and the material building 
functionality is decorated onto the individual volume builders, the material
io payloads had to be adapted to be read/written by volume, too.
In order to know which reader to register for a given file, the file header has
to be inspected. The header now contains a common part, that is e.g. used to 
check if the file version is compatible with the running detray version, as well
as a subheader that is specific to every file. Currently the subheaders contain
some statistics about the file contant that can be used in the future to validate     
the data or help …
=> feat: detector and material reader

tests/common/include/tests/common/tools/ray_scan_utils.hpp
Cover two more error conditions in the intersection trace with more expressive error messages. The internal ```record``` type had to be switched to use pointers due to construction inside ```try``` block
=> fix: more expressive error message for ray scan

tests/unit_tests/cpu/CMakeLists.txt, tests/unit_tests/cpu/check_geometry_navigation.cpp, tests/unit_tests/cpu/check_geometry_scan.cpp, tests/unit_tests/cpu/test_wire_chamber.cpp, tests/unit_tests/cpu/tools_navigator.cpp, utils/include/detray/detectors/create_toy_geometry.hpp, utils/include/detray/detectors/create_wire_chamber.hpp, utils/include/detray/detectors/detector_helper.hpp
Very simple drift chamber to test navigation and KF with wires; no physical walls, no gas, no field wires but only the sense wires with alternating stereo angle. 
A test with propagation will follow in the same PR.
Vertex detectors can also be added in the future if there is a need.
`check_geometry_navigation` does not work well for `float` precision, so I decreased the number of trajectories. 
Please note that the test is passed with 10 x 10 helices with `double` precision - I guess the failure with `float` might be from (1) the precision difference between stepper and particle gun or(and) (2) different tolerance setup in trajectory and mask which it is hard for me to track down..  but not sure yet
=> Add a Simple Drift Chamber

core/include/detray/surface_finders/grid/detail/axis_binning.hpp, tests/unit_tests/io/io_json_detector_reader.cpp, tests/unit_tests/io/io_json_detector_writer.cpp
Fix a bug in axis binning which causes the compilation failure in detector I/O with `default_metadata`
=> Fix a bug in axis binning

core/include/detray/materials/interaction.hpp, core/include/detray/materials/material_rod.hpp
It seems nan value is produced from log function when there is no interaction (0 segment length)
=> Handle no interaction case

io/include/detray/io/common/detail/definitions.hpp, io/include/detray/io/common/geometry_reader.hpp, io/include/detray/io/common/geometry_writer.hpp, io/include/detray/io/common/grid_writer.hpp, io/include/detray/io/common/homogeneous_material_reader.hpp, io/include/detray/io/common/homogeneous_material_writer.hpp, io/include/detray/io/common/io_interface.hpp, io/include/detray/io/common/payloads.hpp, io/include/detray/io/json/json_common_io.hpp, io/include/detray/io/json/json_geometry_io.hpp, io/include/detray/io/json/json_grids_io.hpp, io/include/detray/io/json/json_material_io.hpp, io/include/detray/io/json/json_serializers.hpp, tests/unit_tests/io/io_json_payload.cpp
Cleans up the IO payloads (in particular the payloads for the links are put into a single place) and switches the grid writer to write the payloads by volume, which will be needed in order to fill the grid builders. Also removes some old payloads from the grids
=> ref: grid payloads cleanup

io/include/detray/io/common/detail/file_handle.hpp, io/include/detray/io/json/json_algebra_io.hpp, io/include/detray/io/json/json_common_io.hpp, io/include/detray/io/json/json_geometry_io.hpp, io/include/detray/io/json/json_grids_io.hpp, io/include/detray/io/json/json_material_io.hpp, io/include/detray/io/json/json_reader.hpp
Removing the global variables and Add `inline` attributes to global functions to avoid multiple definitino
=> Avoid multiple definitions

tests/unit_tests/cpu/tools_navigator.cpp, utils/include/detray/detectors/create_wire_chamber.hpp
In the current wire chamber, there are small gaps between the azimuthal angle of last wire and 2 * pi. The PR makes the geometry cover full of [0, 2pi].  It seems one wire is added for every layer
=> Cover all azimuthal angle of wire chamber

core/include/detray/geometry/detail/surface_kernels.hpp, core/include/detray/geometry/surface.hpp, tests/unit_tests/cpu/geometry_surface.cpp
PR adds measurement dimension surface function
It's not a serious issue but portal/passive surface types are supposed to be defined with zero measurement dimension
(i.e. defined disc_portal as `ring2D<plane_intersector, 0u>`)
=> Add measurement dimension surface function

utils/include/detray/detectors/create_toy_geometry.hpp
Fixed a bug where trapezoids in the toy detector would be flipped incorrectly (see image). The side with the smaller length now faces towards the center.
**Before**
**After**
=> bug: fixed trapezoid flipping

core/include/detray/propagator/navigator.hpp, tests/benchmarks/cpu/intersect_all.cpp, tests/benchmarks/cpu/intersect_surfaces.cpp, tests/benchmarks/cuda/benchmark_propagator_cuda.cpp, tests/common/include/tests/common/test_base/propagator_test.hpp, tests/common/include/tests/common/tools/intersectors/helix_cylinder_intersector.hpp, tests/common/include/tests/common/tools/particle_gun.hpp, tests/unit_tests/cpu/tools_particle_gun.cpp, tests/unit_tests/cpu/tools_propagator.cpp, tests/unit_tests/cpu/tools_stepper.cpp, tests/unit_tests/cpu/tools_track_generators.cpp, tests/unit_tests/device/cuda/navigator_cuda.cpp, tests/unit_tests/svgtools/intersections.cpp, tests/validation/include/detray/validation/detail/navigation_check_helper.hpp, tests/validation/src/toy_detector_validation.cpp, tests/validation/src/wire_chamber_validation.cpp, tutorials/src/cpu/detector/detector_ray_scan.cpp, tutorials/src/cpu/propagation/navigation_inspection.cpp, tutorials/src/device/cuda/propagation.cpp, utils/include/detray/simulation/event_generator/random_track_generator.hpp, utils/include/detray/simulation/event_generator/uniform_track_generator.hpp
Enable regular steps in eta for ```uniform_track_generator``` (this is needed for the material scans). The stepping for theta/eta has been adjusted, so that it becomes symmetric for positive and negative eta. Theta and eta ranges are inclusive, but clamped to (0, pi) and [-0.001 * num_max, 0.001 * num_max], respectively.
In order to facilitate the more complex configuration, the config structs of the track generators are used in more places and the possibility to pass complicated configurations to the parametrized constructors has been limited to the most common case.
Edit: Due to some failures in the helix scan tests because of the altered track directions, I set the mask tolerance for portals to zero and reduced the convergence tolerance for the Newton cylinder intersector (it fails to …
=> feat: regular eta steps for uniform track generator

extern/covfie/CMakeLists.txt, extern/googletest/CMakeLists.txt, extern/vecmem/CMakeLists.txt
Updated some externals for (better) Windows/CMake compatibility.
- The updated VecMem version provides SYCL support on Windows with CMake 3.27+;
- The updated GoogleTest version avoids a warning with CMake 3.27+;
- The updated Covfie version removes GCC specific hardcodes that prevented a build on Windows.
This is all in a prelude for things to come... 👻
=> External Updates, main branch (2023.10.09.)

core/include/detray/surface_finders/brute_force_finder.hpp, core/include/detray/tools/cuboid_portal_generator.hpp, core/include/detray/tools/detector_builder.hpp, core/include/detray/tools/material_builder.hpp, core/include/detray/tools/material_factory.hpp, core/include/detray/tools/surface_factory.hpp, core/include/detray/tools/surface_factory_interface.hpp, core/include/detray/tools/volume_builder.hpp, core/include/detray/tools/volume_builder_interface.hpp, core/include/detray/utils/type_registry.hpp, io/include/detray/io/common/detail/utils.hpp, io/include/detray/io/common/detector_reader.hpp, io/include/detray/io/common/detector_writer.hpp, io/include/detray/io/common/geometry_reader.hpp, io/include/detray/io/common/homogeneous_material_reader.hpp, io/include/detray/io/common/homogeneous_material_writer.hpp, io/include/detray/io/common/payloads.hpp, io/include/detray/io/json/json_material_io.hpp, io/include/detray/io/json/json_reader.hpp, tests/unit_tests/cpu/core_detector.cpp, tests/unit_tests/cpu/grid_grid_builder.cpp, tests/unit_tests/cpu/tools_material_builder.cpp, tests/unit_tests/io/io_json_detector_reader.cpp, tests/unit_tests/io/io_json_payload.cpp, tutorials/include/detray/tutorial/square_surface_generator.hpp, tutorials/src/cpu/detector/do_it_yourself_detector.cpp, tutorials/src/cpu/detector/read_detector_from_file.cpp, tutorials/src/cpu/detector/track_geometry_changes.cpp, utils/include/detray/detectors/create_telescope_detector.hpp
Various fixes and refactoring:
- Remove some template arguments from the surface factories and pass information as runtime parameters instead.
- Collaps the various ways to add surfaces to one `add_surfaces` method
- Improved comments
- Similar to the `surface_factory`, explicitly preserve ordering of material data by adding indices to the payloads and direct placing in the container. Can alternatively also be passed without explicit ordering (if surface index is invalid)
- clear the placement vector in the telescope creation to add surface only once
- correctly initialize material rod vector in IO, so that wire chamber can be built correctly
- Added a write-read-write round trip with file comparison for all inbuilt detectors
=> ref: Simplify surface factories and add unique payload link

core/include/detray/materials/interaction.hpp, core/include/detray/materials/material_rod.hpp, core/include/detray/materials/material_slab.hpp, tests/validation/CMakeLists.txt, tests/validation/include/detray/validation/detector_material_scan.hpp, tests/validation/python/plot_material_scan.py, tests/validation/python/pyplot_factory.py, tests/validation/python/run_material_validation.py, tests/validation/src/CMakeLists.txt, tests/validation/src/material_validation.cpp
Add material scan and corresponding plotting tools. The material scanner is added to the validations suite and can shoot rays in uniform eta steps through a detector and record the total encountered material for each ray. The material is recorded either per radiation or interaction length and as total thickness of the material vs. ray path length through the material.
In a second tool (implemented in python), the resulting material budget can be plotted automatically, either as 2D eta-phi map or as a histogram against eta. The plotting functionality has been abstracted into a `plot_factory` to be reusable in other workflows.
The chain can be run with the following commands:
```
> ./bin/detray_material_validation --geometry_file toy_detector_geometry.json --material_file …
```
=> feat: material scanner

tests/unit_tests/cpu/core_detector.cpp, tests/unit_tests/cpu/tools_material_builder.cpp
Switch the CI to 'RelWithDebInfo' to trigger asserts in tests and fix the asserts in the detector building code by filling a few sensitive surfaces
=> fix: asserts in detector building

tutorials/CMakeLists.txt, tutorials/src/device/cuda/CMakeLists.txt, tutorials/src/device/cuda/detector_construction.cpp, tutorials/src/device/cuda/propagation.cpp, tutorials/src/device/cuda/propagation.hpp, tutorials/src/device/cuda/propagation_kernel.cu, utils/include/detray/detectors/bfield.hpp
Silencing the covfie warnings for the tutorial the same way as for the unittests. Also switches the propagation tutorial to use an inhomogeneous bfield (the ODD solenoid field).
=> fix: warnings in propagation tutorial and switch tutorial to inhomogeneous field

tests/unit_tests/io/io_json_detector_reader.cpp, tests/validation/include/detray/validation/detector_helix_scan.hpp, tests/validation/include/detray/validation/detector_ray_scan.hpp, tests/validation/python/plot_helpers.py, tests/validation/python/plot_material_scan.py, tests/validation/python/plot_ray_scan.py, tests/validation/python/pyplot_factory.py, tests/validation/python/run_ray_scan_validation.py, tests/validation/src/detector_validation.cpp, tests/validation/src/material_validation.cpp
Add functionality to output the positions of the ray surface intersections, as well as python tools to plot them in an xy - and an rz view. The data can both be plotted for the ray and the helix scan, which needs to be turned on by the ```--write_scan_data``` option.
=> feat: implement plotting of ray scan positions in python

core/include/detray/geometry/surface.hpp, core/include/detray/utils/consistency_checker.hpp, io/include/detray/io/common/payloads.hpp, io/include/detray/io/json/json_geometry_io.hpp, tests/validation/python/json_schemas/geometry.py, tests/validation/python/json_schemas/homogeneous_material.py, tests/validation/python/json_schemas/surface_grids.py, tests/validation/python/run_file_checker.py
Add schemas for the json data files and provide an executable to read an check json files:
```
python tests/validation/python/run_file_checking.py --geometry_file filename
```
Implemented: geometry, homogeneous material, surface grids
Edit: Also added a few fixes in the payloads and the detector checker
=> feat: json schemas for data files

core/include/detray/surface_finders/brute_force_finder.hpp, core/include/detray/tools/detector_builder.hpp, core/include/detray/tools/material_factory.hpp, core/include/detray/tools/telescope_generator.hpp, tests/unit_tests/cpu/material_interaction.cpp, tests/unit_tests/io/io_json_detector_reader.cpp, utils/include/detray/detectors/create_telescope_detector.hpp, utils/include/detray/detectors/telescope_metadata.hpp
Reimplement the telescope detector creation using the `detector_builder`. The creation of the telescope modules has been moved into a dedicated surface factory and for the portals the `cuboid_portal_generator` is used.
=> ref: use detector builder for telescope detector

extern/actsvg/CMakeLists.txt
The CMake list for extern/actsvg missed the `actsvg::web` module to be built.
=> fix: cmake list

tests/unit_tests/io/CMakeLists.txt
Made the I/O reader and writer tests run in different directories, to stop them from interfering with each other.
As discussed [on Mattermost](https://mattermost.web.cern.ch/acts/pl/iwbwb6xfajr9fdgrnt1i8ptyjy), the recent CI failures are because of
- https://github.com/acts-project/detray/blob/main/tests/unit_tests/io/io_json_detector_reader.cpp and;
- https://github.com/acts-project/detray/blob/main/tests/unit_tests/io/io_json_detector_writer.cpp
using the same filenames during their execution. Allowing them to overwrite each others' files. Or even just making them fail with the following:
```
[bash][atspot01]:build > ./bin/detray_test_io_reader 
Running main() from /home/krasznaa/ATLAS/projects/detray/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 4 tests …
```
=> Test Fix(es), main branch (2023.10.31.)

extern/thrust/CMakeLists.txt
While testing the build of the project on macOS with Xcode 15.0.1 (`Apple clang version 15.0.0`), I came across the following warnings/errors:
```
[ 80%] Building CXX object tests/unit_tests/core/CMakeFiles/detray_test_core.dir/thrust_tuple.cpp.o
In file included from /Users/krasznaa/ATLAS/projects/detray/detray/tests/unit_tests/core/thrust_tuple.cpp:9:
In file included from /Users/krasznaa/ATLAS/projects/detray/build/_deps/thrust-src/thrust/tuple.h:34:
In file included from /Users/krasznaa/ATLAS/projects/detray/build/_deps/thrust-src/thrust/detail/tuple.inl:19:
/Users/krasznaa/ATLAS/projects/detray/build/_deps/thrust-src/thrust/detail/type_traits.h:147:10: error: builtin __has_trivial_constructor is deprecated; use __is_trivially_constructible instead [-Werror,-Wdeprecated-builtins]
|| …
```
=> Thrust Warning Suppression, main branch (2023.10.30.)

core/include/detray/definitions/indexing.hpp, core/include/detray/geometry/detector_volume.hpp, core/include/detray/geometry/surface.hpp, core/include/detray/intersection/detail/trajectories.hpp, core/include/detray/masks/annulus2D.hpp, core/include/detray/masks/unmasked.hpp, core/include/detray/materials/material.hpp, core/include/detray/propagator/navigator.hpp, core/include/detray/tools/bounding_volume.hpp, core/include/detray/tools/surface_factory.hpp, core/include/detray/tools/surface_factory_interface.hpp, core/include/detray/utils/consistency_checker.hpp, core/include/detray/utils/inspectors.hpp, core/include/detray/utils/invalid_values.hpp, plugins/svgtools/include/detray/plugins/svgtools/utils/link_utils.hpp, tests/common/include/tests/common/tools/hash_tree.hpp, tests/unit_tests/core/utils_invalid_values.cpp, tests/unit_tests/cpu/coordinate_cylindrical2.cpp, tests/unit_tests/cpu/core_detector.cpp, tests/unit_tests/cpu/masks_unmasked.cpp, tests/unit_tests/cpu/test_core.cpp, tests/unit_tests/cpu/tools_helix_intersectors.cpp, tests/unit_tests/cpu/tools_navigator.cpp
Remove the use of inifity and replace it with detray invalid value (which is numeric max)
=> ref: remove the use of infinitiy

core/include/detray/core/detail/multi_store.hpp, io/include/detray/io/common/detail/grid_writer.hpp, io/include/detray/io/common/detail/type_traits.hpp, io/include/detray/io/common/detector_writer.hpp, io/include/detray/io/common/homogeneous_material_writer.hpp, io/include/detray/io/common/material_map_writer.hpp, io/include/detray/io/common/surface_grid_writer.hpp, io/include/detray/io/json/json_writer.hpp, tests/unit_tests/io/io_json_detector_writer.cpp
This implements the material maps writing. It splits the common writer functionality for the grids in a common helper class that is inherited by the `surface_grid_writer` and the new `material_map_writer`. The `material_map_writer` uses the `grid_payload` with a `material_slab_payload` as value type.
=> feat: material maps writer

core/include/detray/core/detector_metadata.hpp
Remove volume material grid types as we don't use them and they cause warnings when compiled with surface local positions that are only 2D
=> fix: remove volume material types from default metadata

core/include/detray/core/detector.hpp, core/include/detray/geometry/detail/surface_kernels.hpp, core/include/detray/geometry/detector_volume.hpp, core/include/detray/geometry/surface.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/detector.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/information_section.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/portal.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/volume.hpp, plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp, plugins/svgtools/include/detray/plugins/svgtools/styling/colors.hpp, plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp, tests/unit_tests/svgtools/detectors.cpp, tests/unit_tests/svgtools/grids.cpp, tests/unit_tests/svgtools/groups.cpp, tests/unit_tests/svgtools/intersections.cpp, tests/unit_tests/svgtools/surfaces.cpp, tests/unit_tests/svgtools/trajectories.cpp, tests/unit_tests/svgtools/volumes.cpp, tests/unit_tests/svgtools/web.cpp, tests/validation/include/detray/validation/detail/svg_display.hpp, tests/validation/include/detray/validation/detector_helix_scan.hpp, tests/validation/include/detray/validation/detector_ray_scan.hpp, tests/validation/include/detray/validation/helix_navigation.hpp, tests/validation/include/detray/validation/straight_line_navigation.hpp, tests/validation/src/detector_display.cpp
This uses the actsvg proto classes for the detector and detector volumes as a prerequisite to transforming layer volumes into sheets. Also streamlines the styling and svg id naming a bit.
=> ref: Use proto detector and proto volumes in svgtools illustrator

core/include/detray/definitions/indexing.hpp, core/include/detray/surface_finders/grid/axis.hpp, core/include/detray/surface_finders/grid/detail/axis_binning.hpp, core/include/detray/surface_finders/grid/detail/axis_bounds.hpp, core/include/detray/surface_finders/grid/detail/axis_helpers.hpp, core/include/detray/surface_finders/grid/detail/bin_view.hpp, core/include/detray/surface_finders/grid/detail/serializer_impl.hpp, core/include/detray/surface_finders/grid/grid.hpp, core/include/detray/tools/bin_association.hpp, core/include/detray/utils/ranges.hpp, core/include/detray/utils/ranges/cartesian_product.hpp, core/include/detray/utils/ranges/iota.hpp, core/include/detray/utils/ranges/join.hpp, core/include/detray/utils/ranges/pick.hpp, core/include/detray/utils/ranges/static_join.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/volume.hpp, tests/unit_tests/core/utils_ranges.cpp, tests/unit_tests/cpu/grid_axis.cpp, tests/unit_tests/cpu/grid_grid.cpp, tests/unit_tests/cpu/grid_grid_collection.cpp, tests/unit_tests/cpu/grid_serializer.cpp, tests/unit_tests/device/cuda/utils_ranges_cuda.cpp, tests/unit_tests/device/cuda/utils_ranges_cuda_kernel.cu, tests/unit_tests/device/cuda/utils_ranges_cuda_kernel.hpp, tests/validation/src/detector_display.cpp
Implement the neighborhood lookup on the grids using in-place iteration (no memory allocations for a result vector):
- lookup of the index ranges on the axes that correspond to the search position plus a search window around it
- generate an index sequence for every local bin axis range
- in order to index every bin in the search area, calculate the cartesian product of all of the index sequences
- map the cartesian product to global bin indices
- fetch the bin, which is itself a range
- join all of the bin ranges into a single iteration
Except for the first and the last step, everything else is handled by the new ```bin_view``` class, which can also be used in other contexts than local navigation to iterate through the bins in a neighborhood of a grid.
For the phi axes, which have …
=> feat: grid search

core/include/detray/tools/telescope_generator.hpp
Wiires aligned along the pilot track are not very useful for its study. Let's rotate 90 degree
=> Rotate telescope wires 90 degree around xy plane vector

core/include/detray/core/detector.hpp, core/include/detray/geometry/detail/volume_descriptor.hpp, core/include/detray/geometry/detector_volume.hpp, core/include/detray/materials/interaction.hpp, core/include/detray/propagator/actors/pointwise_material_interactor.hpp, core/include/detray/propagator/base_stepper.hpp, core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp, tests/unit_tests/cpu/energy_loss.cpp, tests/unit_tests/cpu/geometry_volume.cpp, tests/unit_tests/cpu/material_interaction.cpp, tests/unit_tests/cpu/tools_stepper.cpp, utils/include/detray/detectors/create_telescope_detector.hpp, utils/include/detray/simulation/random_scatterer.hpp
This PR adds a volume material in the volume descriptor and integrate it with Runge Kutta stepper for continuous energy loss.
I am not sure if we really need to link it to the material store because we might not need any grid structure in a volume. At least I don't see any use cases.
Futhermore, it is just a raw material, neither rod nor slab so doesn't go well material store.
Anyway this doesn't perturb any existing codes nor degrading performance as the default volume material is vacuum.
=> Add a volume material

core/include/detray/propagator/base_stepper.hpp, core/include/detray/propagator/line_stepper.hpp, core/include/detray/propagator/navigation_policies.hpp, core/include/detray/propagator/navigator.hpp, core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp, core/include/detray/utils/inspectors.hpp, io/include/detray/io/common/geometry_reader.hpp, io/include/detray/io/common/payloads.hpp, io/include/detray/io/json/json_geometry_io.hpp, tests/common/include/tests/common/tools/particle_gun.hpp, tests/unit_tests/cpu/tools_propagator.cpp, tests/unit_tests/cpu/tools_track_generators.cpp, tests/validation/include/detray/validation/detail/svg_display.hpp, tests/validation/include/detray/validation/helix_navigation.hpp, tests/validation/include/detray/validation/straight_line_navigation.hpp, tests/validation/src/detector_display.cpp, tests/validation/src/detector_validation.cpp, tests/validation/src/telescope_detector_validation.cpp, tests/validation/src/toy_detector_validation.cpp, tests/validation/src/wire_chamber_validation.cpp, utils/include/detray/simulation/event_generator/random_track_generator.hpp, utils/include/detray/simulation/event_generator/uniform_track_generator.hpp
This PR adds a RK stepper specific navigation policy that kicks in when the stepper adjusts the step size, anticipating that this means the track direction changed considerably from a straight line. It also adds a stepper print inspector, so that information about when and how the step size gets adjusted becomes available.
Further fixes include:
- enable the navigator to make a volume switch when its hits a portal and the cache is not exhausted. This is needed for backward navigation or when the track bends back into the detector
- enable the track state generators to generate p_T instead of total momentum
- stop recording truth intersections with the particle gun after the track is outside of the detector
- make the volume grid IO optional
- swap the cylinder type in the geometry IO …
=> ref: Add rk stepper policy and a few fixes

core/include/detray/intersection/detail/trajectories.hpp
Spotted a bug in drdt term in helix jacobian. This PR fixes the first term of the following equation ([Reference](https://www.sciencedirect.com/science/article/pii/S0168900206013143)):
It was supposed to calculate H * H^T but the current code is doing wrong definitely
=> Fix a bug in helix jacobian

core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp
Just an implentation of field gradient component in rk stepper covariance transport.
Equation (18) of http://cds.cern.ch/record/1114177/files/ATL-SOFT-PUB-2009-002.pdf
The improvment will be tested in #610 
-------------------------------------------------------
Update
Below graph shows the relative difference beween jacobian evaluated by detray::propagator and numerical differentiation. Jacobian is defined as derivative of bound parameter at the final surface with respect to the bound parameter at the initial surface.
Geometry setting: two rectangle surfaces (telescope geometry) which went thru random rotation, tilt, and spacing.
Track setting: 10 GeV particles in random direction
Field setting: inhomogenenous bfield in detray data directory. Bfield setup was hacked to use field …
=> Use field gradients in covariance transport

core/include/detray/coordinates/coordinate_base.hpp, core/include/detray/geometry/detail/surface_kernels.hpp, core/include/detray/geometry/surface.hpp, core/include/detray/materials/detail/relativistic_quantities.hpp, core/include/detray/materials/interaction.hpp, core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/line_stepper.hpp, core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp, tests/unit_tests/cpu/covariance_transport.cpp
Based on #612 
For an extra precision when there is a non-vacuum volume material.
Without this term, d(qop)/dloc0, d(qop)/dloc1, d(qop)/dphi, d(qop)/dtheta is always zero.
=> Use d(qop)/ds in jacobian calculation

core/include/detray/materials/detail/relativistic_quantities.hpp
They are covered by `derive_stopping_power` in `interaction.hpp` (I guess)
=> Remove the unused functions

core/include/detray/intersection/detail/trajectories.hpp
To make sure that the direction of helix is always normalized (A part of #610)
=> Normalize direction of helix

.github/workflows/builds.yml, .gitlab-ci.yml, data/detray_data_get_files.sh, extern/covfie/CMakeLists.txt, tests/unit_tests/device/cuda/propagator_cuda_kernel.hpp, tutorials/src/device/cuda/propagation.hpp, utils/include/detray/detectors/bfield.hpp
I believe the trilinear interpolation should be used instead of the nearest neighbor (NN) method. The interpolation is what Geant4 and Acts are using with RKN method - If we want to use the NN method, we need to prove that it doesn't harm the performanc first. 
Meanwhile this will require updating the magic io header of the covfie file in `detray/data`
=> Use bfield interpolation rather than NN

core/include/detray/definitions/qualifiers.hpp
As proposed by @krasznaa in https://github.com/acts-project/vecmem/pull/261, extend the __host__ and __device__ macros for HIP.
=> Make __host__ and __device__ function checks work with HIP

core/include/detray/propagator/rk_stepper.ipp
I don't recall how the factor of 2 was added here.
[The original reference](https://iopscience.iop.org/article/10.1088/1748-0221/4/04/P04001) or ACTS does not have the factor of 2
=> Remove the factor of 2 in compraing error tolerance

tests/unit_tests/cpu/tools_helix_trajectory.cpp, tests/validation/root/covariance_validation.C, tests/validation/root/jacobian_comparison.C, tests/validation/root/rk_tolerance_comparison.C, tests/validation/shell/run_jacobian_validation.sh, tests/validation/src/CMakeLists.txt, tests/validation/src/jacobian_validation.cpp
Updates
1. The unit test runs with a couple of sanity checks - if all tracks reach the final surface or the average of d(qop)/d(qop) makes sense.
2. All-in-one script is also added, which will simulate 1000 tracks and produces bunch of pdf plots (reproduction of [the reference](https://iopscience.iop.org/article/10.1088/1748-0221/4/04/P04016/meta) introduced below). 
```
cd ${DETRAY_HOME}/tests/validation/shell
bash run_jacobian_validation.sh -d ${BUILD_DIR}/bin
```
The script works on both float and double precision
---------------------------------------------------------------
This PR reproduces the plots of [Transport of covariance matrices in the inhomogeneous magnetic field of the ATLAS experiment by the application of a semi-analytical method …
=> Add a numerical differentiation test for validating error propagation

core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp
Changes
0. Obtain `qop` recursively as well as `k` (`dtds`)
1. ~~Normalize the direction of all four stages of RKN step~~ It seems the normalization actually doesn't help at all
2. Calculate d(qop_n)/d(qop_1) (n=1,2,3,4) correctly in the calculation of d(k_n)/d(qop_1), where k_n = qop_n ( t_n X B(r_n))
3. Change dL -> dqop for better readibility
4. The sign of `step_direction` in the calculation of `nextE` is removed which seems to be unnecessary. `eloss` already includes the sign from the step size of `h`
5. Rename a couple of functions to match its purpose.
6. Comment as much as possible with a reference 
The first two changes boost the precision of `d(theta)/d(qop)` of jacobian a couple of orders
=> Rework RKN stepper

core/include/detray/coordinates/cylindrical2.hpp, core/include/detray/tools/grid_factory.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp, tests/unit_tests/cpu/material_maps.cpp
Remove r-dependency from 2D cylinder grids, since it might lead to projection effects in the local navigation
=> ref: remove radius from 2D cylinder grid

core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp
Organize the covariance transport of rk stepper so people can at least try to understand the equation.
While doing so, I added more terms coming from chain rules for better precision - but no particular changes in the final result the added terms are very small
=> Rework covariance transport of rk stepper

.gitlab-ci.yml, tests/unit_tests/device/cuda/navigator_cuda.cpp, tests/unit_tests/device/cuda/navigator_cuda_kernel.cu, tests/unit_tests/device/cuda/navigator_cuda_kernel.hpp
The CUDA navigator test is failing in single precision, which has not been picked up by the CI. Turns out the test does not configure the grids correctly, which can lead to the track hitting empty bins even in straight line navigation.
Also sets the CI CUDA test to single precision.
=> fix: Add grid config to CUDA navigation unittest

core/include/detray/propagator/rk_stepper.ipp
The PR multiplies 1/6 to the local error estimate of RK stepper to follow the original form of local error estimate.
Reference: https://iopscience.iop.org/article/10.1088/1748-0221/4/04/P04001
1/6 has been taken out on purpose because it is not an important factor in determining the next step size. But I prefer to have it in the full expression.
=> Multiply 1/6 to the local error estimate of RK stepper

core/include/detray/core/detector_metadata.hpp, core/include/detray/surface_finders/grid/detail/axis.hpp, core/include/detray/surface_finders/grid/detail/bin_storage.hpp, core/include/detray/surface_finders/grid/detail/grid_bins.hpp, core/include/detray/tools/detector_builder.hpp, core/include/detray/tools/grid_builder.hpp, core/include/detray/tools/grid_factory.hpp, core/include/detray/tools/telescope_generator.hpp, core/include/detray/utils/ranges/join.hpp, io/include/detray/io/common/detector_reader.hpp, io/include/detray/io/common/grid_reader.hpp, io/include/detray/io/json/json_reader.hpp, tests/benchmarks/cpu/grid.cpp, tests/unit_tests/cpu/grid_grid_builder.cpp, tests/unit_tests/device/cuda/sf_finders_grid_cuda.cpp, utils/include/detray/detectors/create_toy_geometry.hpp, utils/include/detray/detectors/create_wire_chamber.hpp
Add the respective options to the grid builder and grid factory to build grids with dynamic bin capacities. Also switches the default metadata to grids with dynamic bin capacity. If a compile-time capacity is given to the detector reader, it will try to build a grid with ```static_array``` bins, otherwise it will build ``` dynamic_array``` bins. 
Does not yet provide an interface to explicitly set the bin offsets, which will be needed in the future for the indexed material grids.
=> feat: dynamic capacity grid building

core/include/detray/propagator/base_stepper.hpp, core/include/detray/propagator/constrained_step.hpp, core/include/detray/propagator/line_stepper.hpp, core/include/detray/propagator/navigation_config.hpp, core/include/detray/propagator/navigator.hpp, core/include/detray/propagator/propagation_config.hpp, core/include/detray/propagator/propagator.hpp, core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp, core/include/detray/propagator/stepping_config.hpp, core/include/detray/utils/inspectors.hpp, tests/benchmarks/cuda/benchmark_propagator_cuda.cpp, tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.cu, tests/common/include/tests/common/test_base/fixture_base.hpp, tests/common/include/tests/common/test_base/propagator_test.hpp, tests/unit_tests/cpu/tools_navigator.cpp, tests/unit_tests/cpu/tools_propagator.cpp, tests/unit_tests/device/cuda/navigator_cuda.cpp, tests/unit_tests/device/cuda/navigator_cuda_kernel.cu, tests/unit_tests/device/cuda/navigator_cuda_kernel.hpp, tests/unit_tests/device/cuda/propagator_cuda_kernel.cu, tests/unit_tests/device/sycl/propagator_kernel.sycl, tests/validation/include/detray/validation/helix_navigation.hpp, tests/validation/include/detray/validation/straight_line_navigation.hpp, tests/validation/src/jacobian_validation.cpp, tutorials/src/device/cuda/propagation_kernel.cu
Following the design of traccc, this splits the propagation config from the implementation and adds the step size contraints and path limit to the config
=> ref: Move the propgation config into own header

core/include/detray/propagator/propagation_config.hpp, core/include/detray/propagator/propagator.hpp, tests/benchmarks/cuda/benchmark_propagator_cuda.cpp, tests/benchmarks/cuda/benchmark_propagator_cuda_kernel.cu, tests/common/include/tests/common/test_base/fixture_base.hpp, tests/common/include/tests/common/test_base/propagator_test.hpp, tests/unit_tests/cpu/tools_propagator.cpp, tests/unit_tests/device/cuda/propagator_cuda_kernel.cu, tests/unit_tests/device/sycl/propagator_kernel.sycl, tests/validation/include/detray/validation/helix_navigation.hpp, tests/validation/include/detray/validation/straight_line_navigation.hpp, tests/validation/src/detector_validation.cpp, tests/validation/src/jacobian_validation.cpp, tests/validation/src/toy_detector_validation.cpp, tests/validation/src/wire_chamber_validation.cpp, tutorials/src/device/cuda/propagation_kernel.cu
Make the navigation and stepper configs members instead of inheriting. It seems CUDA does not handle object slicing correctly.
=> fix: navigation and stepper config as members

core/include/detray/core/detail/surface_lookup.hpp, tests/common/include/tests/common/test_toy_detector.hpp, utils/include/detray/detectors/create_toy_geometry.hpp
Equips the toy detector with some test source links on the sensitive surfaces to test the surface lookup
=> fix: and test source link default search

core/include/detray/propagator/rk_stepper.ipp
Continuation of #652, somehow missed these functions (I think because other things were not compiling at the time).
=> Add dgdqop and d2qopdsdqop to HOST_DEVICE definitions

core/include/detray/materials/material.hpp
It is the same unit with `(N_A * u)` but provides better readability 
Atomic mass is defined in g/mol in the data sheet
=> Use gram per mol for A

core/include/detray/builders/material_map_builder.hpp, core/include/detray/builders/telescope_generator.hpp, core/include/detray/core/detector_metadata.hpp, core/include/detray/geometry/shapes/line.hpp, io/include/detray/io/common/detail/type_info.hpp, tests/benchmarks/cpu/masks.cpp, tests/integration_tests/cpu/propagator/covariance_transport.cpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp, tests/unit_tests/cpu/geometry/masks/line.cpp, tests/unit_tests/cpu/material/materials.cpp, tests/unit_tests/cpu/navigation/intersection/helix_intersector.cpp, tests/unit_tests/cpu/navigation/intersection/line_intersector.cpp, tests/unit_tests/cpu/propagator/covariance_transport.cpp, tests/unit_tests/cpu/utils/bounding_volume.cpp, tests/unit_tests/svgtools/masks.cpp, utils/include/detray/detectors/create_telescope_detector.hpp, utils/include/detray/detectors/telescope_metadata.hpp
Adds a typedef for the line shapes and add them with a few other missing masks to the benchmark
=> feat: Add missing masks to benchmark

core/include/detray/builders/homogeneous_material_factory.hpp, core/include/detray/builders/material_map_factory.hpp, tests/unit_tests/cpu/builders/grid_builder.cpp
Removes a few warnings that pop up with gcc 13, except for one that comes from the rms method in utils/statistics.hpp, which seems to go away, if the function is no longer inlined.
=> fix: Remove gcc 13 warnings

core/include/detray/utils/consistency_checker.hpp, io/include/detray/io/frontend/detector_reader.hpp, io/include/detray/io/frontend/detector_reader_config.hpp, tests/include/detray/test/detector_consistency.hpp, tests/include/detray/test/toy_detector_test.hpp, tests/integration_tests/io/io_json_detector_roundtrip.cpp, tests/unit_tests/cpu/detectors/telescope_detector.cpp, tests/unit_tests/cpu/detectors/wire_chamber.cpp
Make verbosity of detector consistency checker configurable. Default is "not verbose"
=> ref: Make verbosity of detector consistency checker configurable

tests/integration_tests/cpu/propagator/jacobian_validation.cpp, tests/validation/root/rk_tolerance_comparison.C
Removing my personal add-on to Ridders' which turned out to be pretty unuseful.
Also fixing the initial displacement for local position in jacobian validation
=> Revert the RIdders algorithm back to original form

extern/thrust/CMakeLists.txt, extern/vecmem/CMakeLists.txt
Updated the project to [Thrust 2.1.0](https://github.com/NVIDIA/thrust/releases/tag/2.1.0) and [VecMem 1.4.0](https://github.com/acts-project/vecmem/releases/tag/v1.4.0). Mainly to be able to build the project without errors and warnings coming from those projects, with:
- oneAPI 2024.0.1 +
- CUDA 12.4 +
- ROCm 6.0.2.
(Actually, the code currently crashes Intel's `icpx` compiler. But that is something that I'll sort out with them...)
=> External Updates, main branch (2024.03.14.)

core/include/detray/core/detail/multi_store.hpp, core/include/detray/core/detail/tuple_container.hpp, core/include/detray/core/detector.hpp, core/include/detray/utils/grid/detail/bin_storage.hpp, core/include/detray/utils/grid/grid_collection.hpp, tests/benchmarks/cuda/benchmark_propagator_cuda.cpp, tests/integration_tests/cpu/propagator/propagator.cpp, tests/unit_tests/cpu/core/detector.cpp, tests/unit_tests/cpu/simulation/particle_gun.cpp, utils/include/detray/detectors/create_toy_geometry.hpp
This is to allow us moving `detray::detector` objects around. 🤔 Copying them remains forbidden, but moving such objects can come in handy in some cases.
While @niermann999 pointing out that she's working on completely re-writing the toy geometry generation did make me give up on any larger changes in the existing code, I still had to cherry-pick one of my earlier written fixes into this PR. Otherwise the project just would not build for me with Clang. 😦
Updated the unit tests that I thought would be most appropriate for this, to now also test moving `detray::detector` objects. (Changed the existing unit testing code for this a bit, to be able to re-use the existing "content checks" using lambdas.)
=> Detector Move (Assignment), main branch (2024.03.18.)

core/include/detray/builders/detector_builder.hpp, core/include/detray/builders/homogeneous_volume_material_builder.hpp, core/include/detray/builders/volume_builder.hpp, core/include/detray/builders/volume_builder_interface.hpp, core/include/detray/materials/material.hpp, core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp, tests/integration_tests/cpu/detectors/telescope_detector_navigation.cpp, tests/integration_tests/cpu/material/material_interaction.cpp, tests/integration_tests/cpu/propagator/guided_navigator.cpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp, tests/integration_tests/io/io_json_detector_roundtrip.cpp, tests/tools/src/generate_telescope_detector.cpp, tests/unit_tests/cpu/CMakeLists.txt, tests/unit_tests/cpu/builders/homogeneous_material_builder.cpp, tests/unit_tests/cpu/builders/homogeneous_volume_material_builder.cpp, tests/unit_tests/cpu/detectors/telescope_detector.cpp, tests/unit_tests/cpu/propagator/covariance_transport.cpp, tests/unit_tests/io/io_json_detector_writer.cpp, tutorials/src/cpu/detector/build_predefined_detectors.cpp, utils/include/detray/detectors/build_telescope_detector.hpp
Adds a volume builder for homogeneous volume material and a corresponding unittest. Also renaming to ```build_telescope_detector```, since it is already switched to the builder infrastructure
=> feat: Add homogeneous volume material builder

core/include/detray/builders/cylinder_portal_generator.hpp, core/include/detray/builders/homogeneous_material_builder.hpp, core/include/detray/builders/homogeneous_material_generator.hpp, core/include/detray/builders/surface_factory.hpp, core/include/detray/builders/volume_builder.hpp, tests/include/detray/test/toy_detector_test_new.hpp, tests/integration_tests/cpu/builders/material_map_builder.cpp, tests/unit_tests/io/io_json_detector_writer.cpp, utils/include/detray/detectors/build_telescope_detector.hpp, utils/include/detray/detectors/build_toy_detector.hpp, utils/include/detray/detectors/factories/barrel_generator.hpp, utils/include/detray/detectors/factories/endcap_generator.hpp
Adds a homogeneous material generator that adds a predefined type of material to passive, sensitive or portals surfaces, depending on the configuration. This is used to add material to the new toy detector and is also used now in the telescope geometry instead of the homogeneous material factory.
=> ref: Add homogeneous material to new toy detector and switch the teselscope detector to new material generation

.github/workflows/builds.yml, .gitignore, .gitlab-ci.yml, CMakeLists.txt, CMakePresets.json, cmake/detray-compiler-options-cpp.cmake, cmake/detray-compiler-options-cuda.cmake, cmake/detray-compiler-options-sycl.cmake
In order to make fixes similar to https://github.com/acts-project/algebra-plugins/pull/115 for [oneAPI 2024.1.0](https://www.intel.com/content/www/us/en/developer/articles/release-notes/intel-oneapi-dpc-c-compiler-release-notes.html), I wanted to make it more convenient (for me personally...) to build Detray with [VSCode](https://code.visualstudio.com/). And hence this PR...
- I switched the project to handle `-Werror` options in the same way as [vecmem](https://github.com/acts-project/vecmem) and [traccc](https://github.com/acts-project/traccc) do since a while. I.e. not to activate errors for warnings just in Debug builds, but to activate them using a dedicated CMake cache variable (`DETRAY_FAIL_ON_WARNINGS`).
- Introduced some (not entirely exhaustive) set of CMake presets, to make it …
=> CMake Updates, main branch (2024.04.12.)

extern/algebra-plugins/CMakeLists.txt, tests/benchmarks/cuda/CMakeLists.txt
This PR allows the vectorization in the detray benchmark with the following tag` "-march=native" "-ftree-vectorize"`
It seems `-ftree-vectorize` is still required for `RelWithDebInfo` build type.
The detray benchmark test (`detray_benchmark_cuda_array`) was done in the LBL server which is less noisy.
Even though It is still subtle a bit, the CPU benchmark seems faster with the matrix multiplication optimization in acts-project/algebra-plugins#116. (All tests were done with `float` precision)
<details>
<summary>Click for the previous benchmarks</summary>
As expected, there was not impact on GPU benchmark 
The speedup with the double precision is more obvious:
</details>
The benchmark was done with better statistics (averged over 10 iterations)
The google sheets does not allow the …
=> Update algebra-plugins and Vectorize the benchmark

core/include/detray/propagator/actors/parameter_resetter.hpp, core/include/detray/propagator/actors/parameter_transporter.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp
Trigger parameter transport to sensitive surfaces and any other surface that carries material. Also fixes a bug in the svg grid display that came up
=> ref: Allow parameter transport to any surface with material

core/include/detray/utils/consistency_checker.hpp
Remove check for vacuum material for material maps
=> fix: Allow vacuum in material maps

extern/actsvg/CMakeLists.txt, plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/portal.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/surface_grid.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/surface_material.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/volume.hpp, plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp, plugins/svgtools/include/detray/plugins/svgtools/styling/colors.hpp, plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp, tests/tools/src/detector_display.cpp, tests/unit_tests/svgtools/CMakeLists.txt, tests/unit_tests/svgtools/grids.cpp, tests/unit_tests/svgtools/groups.cpp, tests/unit_tests/svgtools/material.cpp, tests/unit_tests/svgtools/surfaces.cpp
Adds material a maps display to detray svgtools. The material maps will be drawn with the detray_detector_display tool alongside their surfaces, if a material maps file was provided. Three different color maps are currently available, but need to be set in c++ for now.
Also, fixes the proto surface type, so that passive surfaces can be drawn in a different color than sensitive surfaces, e.g. the toy detector beampipe is now grey.
=> feat: Add material map display to svgtools

core/include/detray/geometry/coordinates/concentric_cylindrical2D.hpp, core/include/detray/geometry/surface.hpp, core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp, core/include/detray/utils/consistency_checker.hpp, io/include/detray/io/common/geometry_reader.hpp, io/include/detray/io/frontend/detector_reader.hpp, tests/include/detray/test/detector_consistency.hpp, tests/include/detray/test/toy_detector_test.hpp, tests/tools/include/detray/validation/detector_material_scan.hpp, tests/tools/src/material_validation.cpp, tests/unit_tests/cpu/detectors/telescope_detector.cpp, tests/unit_tests/cpu/detectors/wire_chamber.cpp, tests/unit_tests/cpu/geometry/coordinates/cylindrical2D.cpp, tests/unit_tests/cpu/navigation/intersection/helix_intersector.cpp, tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp, utils/include/detray/detectors/build_telescope_detector.hpp, utils/include/detray/detectors/build_toy_detector.hpp
Remove usage of a transform from concentric cylinders and fix boundaries. This requires to use the normal for angle calculations, which will be done properly in #723. Plus some improved error printing and skipping empty material in the material scan.
=> fix: Remove transform from concentric cylinders and improved error reporting

core/include/detray/navigation/navigator.hpp
Only check "on surface" if the cache is not exhausted (in this case ```navgiation.next()``` is not valid). This should fix a bug in traccc where the navigator does not find any candidates in a fresh init, but does not abort because the status update reads random data
=> fix: navigation status update

core/include/detray/builders/cuboid_portal_generator.hpp, core/include/detray/geometry/shapes/annulus2D.hpp, core/include/detray/geometry/shapes/concentric_cylinder2D.hpp, core/include/detray/geometry/shapes/cuboid3D.hpp, core/include/detray/geometry/shapes/cylinder2D.hpp, core/include/detray/geometry/shapes/cylinder3D.hpp, core/include/detray/geometry/shapes/line.hpp, core/include/detray/geometry/shapes/rectangle2D.hpp, core/include/detray/geometry/shapes/ring2D.hpp, core/include/detray/geometry/shapes/single3D.hpp, core/include/detray/geometry/shapes/trapezoid2D.hpp, core/include/detray/geometry/surface.hpp, core/include/detray/materials/detail/relativistic_quantities.hpp, core/include/detray/materials/interaction.hpp, core/include/detray/materials/material_rod.hpp, core/include/detray/navigation/intersection/intersection.hpp, core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp, core/include/detray/navigation/intersection/ray_line_intersector.hpp, core/include/detray/navigation/intersection/ray_plane_intersector.hpp, core/include/detray/navigation/navigator.hpp, core/include/detray/propagator/actors/aborters.hpp, core/include/detray/propagator/constrained_step.hpp, core/include/detray/propagator/rk_stepper.ipp, core/include/detray/utils/invalid_values.hpp, core/include/detray/utils/quadratic_equation.hpp
Switched from using `sycl::abs` to `sycl::fabs` for floating point types. With oneAPI 2024.1.0 this became mandatory, as `sycl::abs` only works for integers according to the SYCL standard.
At the same time switched to `std::fabs` for all non-SYCL platforms as well, as using `fabs` is generally a good idea there as well. 🤔
And yes, we'll desperately need to introduce a oneAPI 2024.1.0 based CI test soon. Otherwise that build will break sooner than later...
=> oneAPI 2024.1.0 Support, main branch (2024.05.15.)

core/include/detray/definitions/detail/math.hpp, core/include/detray/navigation/intersection/helix_cylinder_intersector.hpp, core/include/detray/navigation/intersection/helix_line_intersector.hpp, core/include/detray/navigation/intersection/helix_plane_intersector.hpp, core/include/detray/navigation/intersection/intersection.hpp, core/include/detray/navigation/intersection/ray_concentric_cylinder_intersector.hpp, core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp, core/include/detray/navigation/intersection/ray_cylinder_portal_intersector.hpp, core/include/detray/navigation/intersection/ray_line_intersector.hpp, core/include/detray/navigation/intersection/ray_plane_intersector.hpp, core/include/detray/navigation/intersection/soa/ray_cylinder_intersector.hpp, core/include/detray/navigation/intersection/soa/ray_cylinder_portal_intersector.hpp, core/include/detray/navigation/intersection/soa/ray_line_intersector.hpp, core/include/detray/navigation/intersection/soa/ray_plane_intersector.hpp, core/include/detray/navigation/intersection_kernel.hpp, core/include/detray/navigation/intersector.hpp, core/include/detray/navigation/navigation_config.hpp, core/include/detray/navigation/navigator.hpp, core/include/detray/utils/inspectors.hpp, io/include/detray/io/csv/intersection2D.hpp, io/include/detray/io/csv/track_parameters.hpp, io/include/detray/io/utils/create_path.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/surface_grid.hpp, tests/integration_tests/cpu/detectors/telescope_detector_navigation.cpp, tests/tools/include/detray/options/propagation_options.hpp, tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp
Makes the scale factor on the mask tolerance configurable and adds the adaptive mask tolerance to the SoA intersectors. Fixes a few bugs in the navigator:
- candidate iteration includes the current candidate if the track is on a surface (this can lead to skipping a surface in rare cases)
- the object tracer only records elements if the state has changed since the last call. This avoids double counting of candidates and allows to test the telescope detector over a proper theta range without errors
- the mask tolerance scalor was raised, which improves the navigation validation on the ODD for low momenta (0.5 GeV)
- sets the equality operator of the intersection back to single precision, since the ray scan on ACTS detectors fails on adjacent portals otherwise due to a slight floating point …
=> fix: navigation and make mask tolerance scaling configurable

tests/include/detray/test/common/utils/navigation_validation_utils.hpp, tests/include/detray/test/cpu/navigation_validation.hpp, tests/include/detray/test/device/cuda/navigation_validation.cu, tests/include/detray/test/device/cuda/navigation_validation.hpp, tests/tools/src/cpu/detector_validation.cpp, tests/tools/src/cuda/detector_validation_cuda.cpp, tests/validation/python/impl/__init__.py, tests/validation/python/impl/plot_ray_scan.py, tests/validation/python/impl/plot_track_positions.py, tests/validation/python/navigation_validation.py, tests/validation/python/plotting/plot_helpers.py, tests/validation/python/plotting/pyplot_factory.py, utils/include/detray/simulation/event_generator/uniform_track_generator_config.hpp
Added a method to write the track positions and directions that were recorded whenever the navigation has reached a surface to csv. The csv file is read back into the python plotting tools where 2D track position and residual plots are prepared from them (e.g. host vs. device). I moved the csv IO functionality in python into the same files where the corresponding plotting functions are defined.
Also fixed the selection of the number of tracks to check in the validation tools and made sure that the python code is handling the data in double precision, so that the minute residuals between host and device code become visible at all (but only when removing the fast math option for CUDA and even then, it is quantized to multiples of the machine epsilon)
=> feat: Add additional track posistion and residual plots

core/include/detray/utils/grid/detail/axis.hpp
For reasons that I cannot fully explain, the default `multi_bin` constructor introduces a compiler error in C++20. This commit removes that constructor which seems to repair the situation.
=> Fix C++20 bug in axis constructor

core/include/detray/geometry/shapes/annulus2D.hpp
Here are a few unit tests affected by this problem:
- `detray_unit_test_cuda_array`
- `detray_unit_test_cuda_eigen`
and here is the error I was getting:
```
[ RUN      ] mask_store_cuda.mask_store
detray_unit_test_cuda_array: /home/tsulaia/detray/src/core/include/detray/geometry/shapes/annulus2D.hpp:121: auto detray::annulus2D::check_boundaries(const bounds_t<scalar_t, kDIM>&, const point_t&, scalar_t) const [with bounds_t = std::array; scalar_t = double; long unsigned int kDIM = 7; point_t = std::array<double, 3>; typename std::enable_if<(kDIM == detray::annulus2D::e_size), bool>::type <anonymous> = true]: Assertion `!detail::any_of(minR_tol >= scalar_t(0.f))' failed.
```
=> annulus2D.hpp: fixed typo that was leading to crashes in some unit tests

core/include/detray/navigation/intersection/helix_cylinder_intersector.hpp, core/include/detray/navigation/intersection/helix_line_intersector.hpp, core/include/detray/navigation/intersection/helix_plane_intersector.hpp, core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp, core/include/detray/navigation/intersection/ray_line_intersector.hpp, core/include/detray/navigation/intersection/ray_plane_intersector.hpp, tests/unit_tests/svgtools/trajectories.cpp
`tests/unit_tests/svgtools/trajectories.cpp`.
Normalized the dir vector before passing it to the constructor of helix
`core/include/detray/navigation/intersection/helix_*_intersector.hpp`
Fixed the calling of intersectors with one tolerance value
`core/include/detray/navigation/intersection/ray_*_intersector.hpp`
Removed the "Minimal mask tolerance needs to be smaller or equal maximal mask tolerance" assertion
=> Fixes for failing unit tests

tests/include/detray/test/common/utils/detector_scanner.hpp, tests/include/detray/test/common/utils/navigation_validation_utils.hpp, tests/include/detray/test/common/utils/svg_display.hpp, tests/include/detray/test/cpu/detector_scan.hpp, tests/include/detray/test/cpu/navigation_validation.hpp, tests/include/detray/test/device/cuda/navigation_validation.hpp, tests/validation/python/impl/__init__.py, tests/validation/python/impl/plot_navigation_validation.py, tests/validation/python/impl/plot_ray_scan.py, tests/validation/python/impl/plot_track_positions.py, tests/validation/python/navigation_validation.py, tests/validation/python/plotting/pyplot_factory.py
Instead of returning as soon as a difference in the intersection traces between truth and navigation is found, the validation now counts all differences, in case there were multiple surfaces missed. For every missed surface, a dummy record is inserted, so that the resulting track states that are written out have the same number of elements, allowing to plot residuals easily, where the missed surfaces appear as outlier values. The python scripts have been adapted to plot truth vs. navigation track position residuals, including optional outlier cuts. The reporting of errors and statistics of missed surfaces has been improved and the option to do a Gaussian fit has been added to the plotting of the residuals.
The *surface finding efficiency* is quoted as result now, which is defined as the …
=> ref: Count the number of missed surfaces in navigation validation

core/include/detray/geometry/detail/shape_utils.hpp, core/include/detray/geometry/shapes/annulus2D.hpp, core/include/detray/geometry/shapes/cylinder3D.hpp, tests/unit_tests/cpu/geometry/masks/annulus2D.cpp
Interpret the mask tolerance parameter in inside/outside check for phi angles as the opening angle that corresponds to a chord of the length of the tolerance. Since the phi tolerance is always small, the calculation can be done with a small angle approximation and is relatively cheap.
=> ref: Estimate phi tolerance from chord

tests/include/detray/test/common/utils/material_validation_utils.hpp, tests/include/detray/test/cpu/material_scan.hpp, tests/include/detray/test/cpu/material_validation.hpp, tests/include/detray/test/cpu/toy_detector_test.hpp, tests/integration_tests/cpu/detectors/toy_detector_navigation.cpp, tests/tools/src/cpu/generate_toy_detector.cpp, tests/validation/python/impl/plot_material_scan.py, tests/validation/python/material_validation.py, tests/validation/python/navigation_validation.py, tests/validation/python/options/__init__.py, tests/validation/python/options/track_generator_options.py, utils/include/detray/detectors/build_toy_detector.hpp
This PR decorates all portals in the toy detector with material maps, not just the volumes that contain sensitive surfaces and teaches the material scan to skip the exit portals the way the navigator would. In particular, the world portal is skipped now. 
Also activated the material map validation integration test for the toy detector in the CI, as this works correctly now and added a little bit of plotting.
=> ref: Add material maps to all portals in toy detector and harmonize with material scan

core/include/detray/navigation/intersection/helix_plane_intersector.hpp
Use the ray estimation for the initial value of path length of helix plane intersector. (as helix line intersector does)
=> Use ray esimation for initial value of helix plane intersector

core/include/detray/navigation/detail/helix.hpp, core/include/detray/navigation/detail/ray.hpp, io/include/detray/io/frontend/detector_writer_config.hpp, tests/include/detray/test/common/utils/detector_scanner.hpp, tests/include/detray/test/cpu/detector_scan.hpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp, tests/tools/include/detray/options/detector_io_options.hpp, tests/tools/include/detray/options/track_generator_options.hpp, tests/unit_tests/cpu/simulation/track_generators.cpp, tests/validation/python/impl/__init__.py, tests/validation/python/impl/plot_navigation_validation.py, tests/validation/python/impl/plot_track_params.py, tests/validation/python/navigation_validation.py, tests/validation/python/options/track_generator_options.py, tests/validation/python/plotting/pyplot_factory.py, tutorials/src/cpu/detector/detector_ray_scan.cpp, utils/include/detray/simulation/event_generator/random_numbers.hpp, utils/include/detray/simulation/event_generator/random_track_generator.hpp, utils/include/detray/simulation/event_generator/random_track_generator_config.hpp, utils/include/detray/simulation/event_generator/uniform_track_generator.hpp, utils/include/detray/simulation/event_generator/uniform_track_generator_config.hpp
Allow to randomize the charge sign in the track generators. For this, the random number generator wrapper was moved to its own header, so that it can be shared between the random and uniform track generators. The randomization can be switched on via the track generator options and the navigation trajectories (ray/helix) now returns their associated charge. Some changes to the IO options were reverted - should have no further effect besides being more intuitive.
Also adds plots for the distribution of the parameters of the tracks that are generated by the track generators and fixes the Gauss fits a little.
=> feat: Randomize charge in track generators and plot track parameter distributions

core/include/detray/builders/grid_factory.hpp, core/include/detray/builders/material_map_builder.hpp, core/include/detray/builders/material_map_factory.hpp, io/include/detray/io/common/material_map_reader.hpp, tests/integration_tests/cpu/builders/material_map_builder.cpp, tests/unit_tests/cpu/builders/material_map_builder.cpp
This PR allows to read in the map bounds and overwrite the mask boundaries. This gives a very nice result now between ACTS and detray material even for portal material.
=> feat: allow to read material map boundaries

tests/include/detray/test/common/utils/detector_scan_utils.hpp
The `check_connectivity` function in the detector scan utilities header makes use of the `difference_type` typedef on the iterator of a vector, but this is not defined by the standard, and I was running into compilation errors stemming from this. The correct solution to this is to use the `std::iterator_traits` class (because an iterator can also be a raw pointer which doesn't carry any type aliases) but since we are using a vector I simply went ahead and used the
`std::vector::difference_type` definition.
=> Fix non-conformant use of iterator type aliases

core/include/detray/builders/surface_factory.hpp, core/include/detray/geometry/mask.hpp, core/include/detray/geometry/shapes/annulus2D.hpp, core/include/detray/geometry/shapes/concentric_cylinder2D.hpp, core/include/detray/geometry/shapes/cuboid3D.hpp, core/include/detray/geometry/shapes/cylinder2D.hpp, core/include/detray/geometry/shapes/cylinder3D.hpp, core/include/detray/geometry/shapes/line.hpp, core/include/detray/geometry/shapes/rectangle2D.hpp, core/include/detray/geometry/shapes/ring2D.hpp, core/include/detray/geometry/shapes/single3D.hpp, core/include/detray/geometry/shapes/trapezoid2D.hpp, core/include/detray/geometry/shapes/unbounded.hpp, core/include/detray/geometry/shapes/unmasked.hpp, core/include/detray/utils/string_view_concat.hpp, io/include/detray/io/common/geometry_reader.hpp, io/include/detray/io/common/geometry_writer.hpp, io/include/detray/io/common/homogeneous_material_reader.hpp, io/include/detray/io/common/homogeneous_material_writer.hpp, io/include/detray/io/common/material_map_reader.hpp, io/include/detray/io/common/material_map_writer.hpp, io/include/detray/io/common/surface_grid_reader.hpp, io/include/detray/io/common/surface_grid_writer.hpp, io/include/detray/io/frontend/detail/io_metadata.hpp, io/include/detray/io/json/json_writer.hpp, tests/include/detray/test/cpu/material_validation.hpp, tests/include/detray/test/device/cuda/material_validation.hpp, tests/unit_tests/cpu/geometry/masks/unbounded.cpp, tutorials/include/detray/tutorial/my_square2D.hpp
You wouldn't guess it, but it's yet another case of NVCC not liking detray code. As usual, detray hasn't actually done anything wrong, but some code in detray is leading to segmentation faults in targets built from translation units compiled with NVCC.
The reason this happens is that detray make extensive use of names and tags in the form `inline static const std::string`. This is perfectly legal, but the mechanics of this mean that the compiler has to inject some code at the start of the program which takes the string literals and stores them in memory. This is because the compiler is not allowed to simply put the strings in the `.data` section of the object, they have to be properly constructed and they have to live in `.bss`. In the meanwhile, the `inline` keyword requires the linker …
=> Migrate static strings to `std::string_view`

core/include/detray/utils/bit_encoder.hpp
Fix `suggest parentheses around comparison in operand of '|' [-Werror=parentheses]` which occures when detray is included in ACTS (CI linux-nodeps centos8-lcg100-gcc10 fails)
=> fix: suggest parentheses around comparison in operand of '|' warning

extern/actsvg/CMakeLists.txt, plugins/svgtools/include/detray/plugins/svgtools/utils/surface_kernels.hpp, tests/tools/src/cpu/generate_telescope_detector.cpp
New actsvg version that should allow to display the material maps correctly. Also fixes a bug in the arrow generation for portal links on concentric cylinders and adds more options to tool that generates telescope detectors along helices
=> ref: Update to new actsvg version and fix some bugs

plugins/svgtools/include/detray/plugins/svgtools/conversion/intersection.hpp, plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp, tests/include/detray/test/common/detector_scan_config.hpp, tests/include/detray/test/cpu/detector_scan.hpp, tests/include/detray/test/cpu/navigation_validation.hpp, tests/include/detray/test/device/cuda/navigation_validation.hpp, tests/tools/include/detray/options/propagation_options.hpp, tests/tools/src/cpu/detector_validation.cpp, tests/tools/src/cpu/generate_toy_detector.cpp, tests/tools/src/cuda/detector_validation_cuda.cpp, tests/validation/python/impl/plot_navigation_validation.py, tests/validation/python/impl/plot_ray_scan.py, tests/validation/python/impl/plot_track_params.py, tests/validation/python/navigation_validation.py, tests/validation/python/plotting/pyplot_factory.py
Adds the momentum range to the data file names that are generated during the navigation validation, so that the validation can be run for different momenta automatically. Also cleans up the corresponding plots (font sizes etc.)
Fixes a bug, where in the svg the intersection positions on concentric cylinders were not displayed correctly after reading them back in from file, since the files only safe the bound coordinates. Therefore, the ```bound_to_global``` method is now used in the illustrator to get the correct positions, setting the first intersection always into the origin by convention (this is a dummy record that captures the initial track parameters).
=> ref: add momentum information to file names and finalize plots

tests/include/detray/test/common/material_validation_config.hpp, tests/include/detray/test/cpu/material_validation.hpp, tests/integration_tests/cpu/detectors/toy_detector_navigation.cpp, tests/integration_tests/cpu/detectors/wire_chamber_navigation.cpp, tests/integration_tests/device/cuda/toy_detector_navigation_validation.cpp, tests/integration_tests/device/cuda/wire_chamber_navigation_validation.cpp, tests/tools/src/cpu/material_validation.cpp, tests/tools/src/cuda/material_validation_cuda.cpp, tests/validation/python/impl/plot_material_scan.py, tests/validation/python/impl/plot_navigation_validation.py, tests/validation/python/impl/plot_track_params.py, tests/validation/python/material_validation.py, tests/validation/python/navigation_validation.py, tests/validation/python/plotting/pyplot_factory.py
Switches to realtive error checking for the material traces and cleans up material plots. Also adds a comparision plot between the material scan data and the navigaiton material traces. The large scatter plots are for now always returned as pngs
=> ref: Use relative error in material comparison and improve material plots

core/include/detray/geometry/detail/surface_kernels.hpp
Fixed typo in the call. This was throwing an error when I tried to get the material properties at a surface.
=> Fix typo in getting material

plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp
Actsvg can now display labels for the material svgs
=> ref: Add labels to the material svgs

CMakeLists.txt, plugins/CMakeLists.txt, tests/unit_tests/CMakeLists.txt
Updated the CMake flag DETRAY_SVG_DISPLAY to build SVG tools only when it is enabled. Previously, this option had no effect. Additionally, DETRAY_SVG_DISPLAY is now enabled by default.
=> fix: implement DETRAY_SVG_DISPLAY cmake option

core/include/detray/geometry/detail/surface_kernels.hpp, core/include/detray/geometry/detail/volume_kernels.hpp, core/include/detray/geometry/tracking_surface.hpp, core/include/detray/geometry/tracking_volume.hpp, core/include/detray/materials/material.hpp, core/include/detray/materials/material_map.hpp, core/include/detray/materials/material_rod.hpp, core/include/detray/materials/material_slab.hpp, core/include/detray/propagator/actors/pointwise_material_interactor.hpp, core/include/detray/utils/consistency_checker.hpp, core/include/detray/utils/type_traits.hpp, io/include/detray/io/common/detail/type_info.hpp, tests/include/detray/test/common/utils/material_validation_utils.hpp, tests/unit_tests/cpu/geometry/tracking_surface.cpp
The functor to get the material parameters was broken when a detector contains homogeneous volume material, since this returns the material parameters directly instead of as a material slab or rod.
In order to disentangle things better, this PR introduces new type traits to identify volume (material params and 3D maps) and surface material (slabs/rod and 2D maps).
=> fix: access to material parameters from tracking surface

core/include/detray/geometry/tracking_surface.hpp, core/include/detray/navigation/intersection/helix_cylinder_intersector.hpp, core/include/detray/navigation/intersection/helix_line_intersector.hpp, core/include/detray/navigation/intersection/helix_plane_intersector.hpp, core/include/detray/navigation/intersection/intersection.hpp, core/include/detray/navigation/intersection/ray_concentric_cylinder_intersector.hpp, core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp, core/include/detray/navigation/intersection/ray_line_intersector.hpp, core/include/detray/navigation/intersection/ray_plane_intersector.hpp, core/include/detray/navigation/intersection/soa/ray_cylinder_intersector.hpp, core/include/detray/navigation/intersection/soa/ray_line_intersector.hpp, core/include/detray/navigation/intersection/soa/ray_plane_intersector.hpp, core/include/detray/propagator/actors/pointwise_material_interactor.hpp, core/include/detray/utils/root_finding.hpp, io/include/detray/io/csv/intersection2D.hpp, tests/unit_tests/cpu/geometry/tracking_surface.cpp, tests/unit_tests/cpu/material/materials.cpp, tests/unit_tests/cpu/navigation/intersection/cylinder_intersector.cpp, tests/unit_tests/cpu/navigation/intersection/helix_intersector.cpp, tests/unit_tests/cpu/navigation/intersection/intersection2D.cpp, tests/unit_tests/cpu/navigation/intersection/line_intersector.cpp, tests/unit_tests/cpu/navigation/intersection/plane_intersector.cpp, utils/include/detray/simulation/random_scatterer.hpp
Removes the incidence angle from the intersection, since it is only needed when the track is actually on surface and the surface has material. Instead, it is now calculated using the tracking surface interface directly in the material interactor. Seems to bring *very* slight speedup
=> ref: Remove the incidence angle from the intersection

core/include/detray/builders/cylinder_portal_generator.hpp, core/include/detray/geometry/coordinates/line2D.hpp, core/include/detray/navigation/detail/helix.hpp, core/include/detray/navigation/intersection/helix_cylinder_intersector.hpp, core/include/detray/navigation/intersection/helix_line_intersector.hpp, core/include/detray/navigation/intersection/helix_plane_intersector.hpp, core/include/detray/navigation/intersection/ray_concentric_cylinder_intersector.hpp, core/include/detray/navigation/policies.hpp, core/include/detray/propagator/line_stepper.hpp, core/include/detray/tracks/bound_track_parameters.hpp, core/include/detray/tracks/free_track_parameters.hpp, core/include/detray/utils/inspectors.hpp, core/include/detray/utils/quadratic_equation.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp, tutorials/include/detray/tutorial/my_square2D.hpp, utils/include/detray/detectors/factories/barrel_generator.hpp
Using `std::abs` on floating point types is deprecated behaviour, and `std::fabs` should be used instead. This commit ensures that the correct function is used on floating point values.
=> Replace `math::abs` with `math::fabs` where needed

extern/algebra-plugins/CMakeLists.txt
This new version fixes some compiler warnings.
=> Update algebra-plugins to v0.25.0

extern/actsvg/CMakeLists.txt, extern/algebra-plugins/CMakeLists.txt, extern/benchmark/CMakeLists.txt, extern/covfie/CMakeLists.txt, extern/dfelibs/CMakeLists.txt, extern/googletest/CMakeLists.txt, extern/nlohmann_json/CMakeLists.txt, extern/vecmem/CMakeLists.txt
This commit allows us to mark dependencies as system libraries on CMake versions 3.25 and later, reducing the volume of compiler warnings.
=> Mark dependencies as system libraries

tests/integration_tests/device/sycl/propagator.sycl
The CI for #771 has been failing mysteriously, and I have found that this is actually due to the fact that the SYCL propagator tests are missing a configuration parameter limiting the eta range to [-3, 3] like the other propagator tests have. This commit adds this missing range and seems to fix the CI bug.
=> Add missing eta range in SYCL propagator test

.github/workflows/benchmarks.yml, README.md
Adding workflow for detray continous benchmark in conjuntion with #787. (Based on @paulgessinger 's suggestion)
Whenever a PR is merged, the CI triggers the workflow [detray-benchmark](https://gitlab.cern.ch/beyeo/detray-benchmark) to run the propagation benchmark and push the results with plots.
=> Add workflow for continous benchmark

core/include/detray/definitions/track_parametrization.hpp, core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/base_stepper.hpp, core/include/detray/propagator/propagator.hpp, core/include/detray/tracks/bound_track_parameters.hpp, core/include/detray/tracks/detail/track_helper.hpp, core/include/detray/tracks/free_track_parameters.hpp, core/include/detray/utils/curvilinear_frame.hpp, tests/integration_tests/cpu/propagator/propagator.cpp, tests/unit_tests/cpu/CMakeLists.txt, tests/unit_tests/cpu/tracks/bound_track_parameters.cpp, tests/unit_tests/cpu/tracks/free_track_parameters.cpp, tests/unit_tests/cpu/utils/curvilinear_frame.cpp
The covariance of free track parameter of steppers is removed.  
The free covariance is required when the state is constructed with free track parameter, however, constructing stepper state with free parameter covariance does not make sense to me. Covariance transport is also disabled when the stepper state is created with free vector.
=> Remove the covariance matrix from the free track parameters

core/include/detray/geometry/detail/surface_kernels.hpp, core/include/detray/geometry/mask.hpp, core/include/detray/geometry/tracking_surface.hpp, core/include/detray/navigation/detail/helix.hpp, core/include/detray/navigation/detail/ray.hpp, core/include/detray/navigation/intersection/bounding_box/cuboid_intersector.hpp, core/include/detray/navigation/intersection/ray_concentric_cylinder_intersector.hpp, core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp, core/include/detray/navigation/intersection/ray_cylinder_portal_intersector.hpp, core/include/detray/navigation/intersection/ray_line_intersector.hpp, core/include/detray/navigation/intersection/ray_plane_intersector.hpp, core/include/detray/propagator/actors/parameter_resetter.hpp, core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/detail/jacobian_engine.hpp, core/include/detray/tracks/detail/track_helper.hpp, core/include/detray/tracks/detail/transform_track_parameters.hpp, core/include/detray/tracks/free_track_parameters.hpp, core/include/detray/utils/curvilinear_frame.hpp, tests/integration_tests/cpu/propagator/covariance_transport.cpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp, tests/integration_tests/cpu/propagator/propagator.cpp, tests/unit_tests/cpu/propagator/jacobian_cartesian.cpp, tests/unit_tests/cpu/propagator/jacobian_cylindrical.cpp, tests/unit_tests/cpu/propagator/jacobian_line.cpp, tests/unit_tests/cpu/propagator/jacobian_polar.cpp, tests/unit_tests/cpu/propagator/rk_stepper.cpp, tests/unit_tests/cpu/tracks/free_track_parameters.cpp
The free vector and the free track parameters are pretty much the same now, so let's use the classes public interface to access the data. This leads to some code simplifications in the track helper and the single parameter access
Also fixed a bug, where the CUDA code would not compile due to missing initializers on the mask values.
=> ref: Remove distiction between free vector and free track parameters

core/include/detray/geometry/barcode.hpp, core/include/detray/geometry/detail/surface_descriptor.hpp, tests/benchmarks/cpu/intersect_surfaces.cpp, tests/benchmarks/cpu/intersectors.cpp, tests/include/detray/test/common/utils/planes_along_direction.hpp, tests/integration_tests/cpu/propagator/guided_navigator.cpp, tests/unit_tests/cpu/geometry/barcode.cpp, tests/unit_tests/cpu/navigation/brute_force_finder.cpp
Removes the transform index as a separate index in the surface descriptor and adds it to the barcode. If it turns out not to be needed in the SoA layout, it will eventually be removed altogether. 
Some of the benchmark code used to put the transform directly into the descriptor, which was now changed, so that the transforms are passed in a separate collection
=> ref: Move the transform index onto the barcode

CMakeLists.txt, core/include/detray/navigation/navigator.hpp
If the cache is exhausted, ```m_next``` is larger than ```m_last```, which in turn must be smaller than the cache size.
=> ref: Adapt the assertions in the navigator to cache exhaustion

core/include/detray/geometry/detail/surface_kernels.hpp, tests/unit_tests/cpu/geometry/tracking_surface.cpp
I'm guessing this function was missed as part of #756, but essentially without the proposed change you get a compiler error due to the attempted automatic conversion between a `string_view` (from the surface) and a `string` that the function is attempting to return.
This just swaps that, and updates a unit test to catch it.
If you remove the fix and build the tests, you should be able to see the initial error.
I assume this is a fairly isolated change, but my knowledge of detray is as a user rather than developer, so hopefully I've not missed anything.
=> Update surface kernel to accept string_view.

tests/include/detray/test/common/utils/material_validation_utils.hpp, tests/include/detray/test/common/utils/navigation_validation_utils.hpp, tests/include/detray/test/common/utils/step_tracer.hpp, tests/include/detray/test/cpu/material_validation.hpp, tests/include/detray/test/cpu/navigation_validation.hpp, tests/include/detray/test/device/cuda/material_validation.cu, tests/include/detray/test/device/cuda/material_validation.hpp, tests/include/detray/test/device/cuda/navigation_validation.cu, tests/include/detray/test/device/cuda/navigation_validation.hpp
Also record the material steps in the material tracer for host and device. For the device material tracer, the number of surfaces that are encountered per track is currently guessed, as this information is not available in that test.
The PR also adds the step tracer to the host-side ```record_propagation``` function, which now runs the object tracer, the step tracer and the material tracer. For the device-side propagation recording, the number of steps that each track takes has to be determined first, before the step tracer will be added there.
=> ref: Record the material steps in the material tracer

core/include/detray/propagator/rk_stepper.ipp
This PR makes dkn/dqop and dkn/dt neglect the mangetic field gradient terms with dB/dr, they are negligible compared to other terms.
It seems the plots from `jacobian_validation` do not make any noticeable difference.
=> Ignore some bfield gradient terms in RKN Jacobian calculation

.gitlab-ci.yml
Go back to old docker image source, and instead add multithreaded CUDA ci-bridge build.
=> ref: speedup device CI builds

core/include/detray/builders/grid_builder.hpp, core/include/detray/builders/grid_factory.hpp, core/include/detray/geometry/mask.hpp, core/include/detray/utils/curvilinear_frame.hpp, tests/include/detray/test/utils/prefill_detector.hpp, tests/unit_tests/cpu/core/mask_store.cpp, tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp, tests/unit_tests/device/cuda/mask_store_cuda.cpp, tests/unit_tests/svgtools/masks.cpp
Changes the default parameters in the grid builder infrastructure to circumvent a spurious null-dereference warning. Also mandates a certain number of value to initialize a mask, in order to remove is-uninitialized warnings (unsuccessfully). But it helped uncovering a few spots where trapezoid masks are not initialized corretly
=> fix: Remove compiler/linker warnings

core/include/detray/propagator/actors/parameter_resetter.hpp, core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/base_stepper.hpp
This also gives some boost in the event throughput
```
Main
CUDA unsync propagation/8   34369115636 ns   34355170928 ns            1 TracksPropagated=1.86289/s
CUDA unsync propagation/16     3289075 ns      3288918 ns          200 TracksPropagated=77.8371k/s
CUDA unsync propagation/32     4034031 ns      4033801 ns          173 TracksPropagated=253.855k/s
CUDA unsync propagation/64     5552317 ns      5552233 ns          124 TracksPropagated=737.721k/s
CUDA unsync propagation/128   12789134 ns     12789108 ns           54 TracksPropagated=1.28109M/s
CUDA unsync propagation/256   45228177 ns     45226861 ns           16 TracksPropagated=1.44905M/s
CUDA sync propagation/8        2092650 ns      2092419 ns          331 TracksPropagated=30.5866k/s
CUDA sync propagation/16       3308820 ns …
```
=> Remove the member variable of `jac_to_global` from base stepper

extern/vecmem/CMakeLists.txt
We don't actually need any features from vecmem, but vecmem determines how our SYCL code is compiled, and we need this version for C++20 to be used in SYCL code (and for #831 to pass).
=> Update vecmem to version 1.8.0

.github/workflows/builds.yml
Switch on multithreaded builds for the slower CI jobs
=> CI: switch on multithreading in the CI

core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/base_stepper.hpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp
The PR removes the _full_jacobian from the base stepper.
I had to split the parameter_transport operator into two functions to make it work with jacobian_validation test.
The performance is improved slightly:
Main
```
--------------------------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations UserCounters...
--------------------------------------------------------------------------------------
CUDA unsync propagation/8      2139250 ns      2139123 ns          266 TracksPropagated=29.9188k/s
CUDA unsync propagation/16     3162398 ns      3162309 ns          219 TracksPropagated=80.9535k/s
CUDA unsync propagation/32     3989859 ns      3989710 ns          174 TracksPropagated=256.66k/s
CUDA unsync …
```
=> Remove `_full_jacobian` from base stepper

core/include/detray/navigation/detail/helix.hpp, core/include/detray/navigation/detail/ray.hpp, core/include/detray/tracks/bound_track_parameters.hpp, core/include/detray/tracks/free_track_parameters.hpp, io/include/detray/io/csv/track_parameters.hpp, tests/include/detray/test/cpu/detector_scan.hpp, tests/include/detray/test/cpu/navigation_validation.hpp, tests/include/detray/test/device/cuda/navigation_validation.hpp, tests/include/detray/test/utils/detector_scanner.hpp, tests/include/detray/test/utils/inspectors.hpp, tests/include/detray/test/utils/navigation_validation_utils.hpp
Even though the track generator can be configured with any charge, the navigation validation can only be run with q=1 to avoid possible inconsistencies when the trace data is dumped into csv files. This has been fixed by passing the charge as an additional parameter. 
Additionally, the ```charge``` getters have been removed from the test trajectories (helix and ray), because it is actually unknown there and should not be guessed to be one.
=> fix: Allow different track charges in navigation validation

core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/base_stepper.hpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp
I found that full jacobian is required in smoother in Kalman Fitter :skull_and_crossbones: 
Roll back #832
=> Add back the full jacobian to the base stepper

.github/workflows/builds.yml
Run the host unit tests in debug build in the CI. The integration tests are still not run, as it would likely take quite long. Furthermore, the Eigen builds are excluded from this, since they result in a timeout of the CI
=> CI: Run debug unittests

.github/find_f64_ptx.py, .github/workflows/builds.yml, cmake/detray-compiler-options-cuda.cmake, cmake/detray-functions.cmake
This commit adds the same code that we use to detect rogue FP64 instructions in traccc to the detray CI.
=> Add FP64 compliance CI job

core/include/detray/propagator/propagator.hpp
Current condition of `if (propagation._heartbeat)` seems make propagate_sync() different from proapgate()
=> Make propagate() and propagate_sync() equal

.github/workflows/builds.yml, core/include/detray/propagator/detail/jacobian_polar.hpp, core/include/detray/propagator/rk_stepper.ipp
As usual, this is usually to do with literals that are missing the `.f` suffix.
=> Remove several unwanted FP64 operations

.github/workflows/checks.yml
This might still be useful for people who do not want to setup a local clang-format version matching the CI
=> ref: Reactivate clang-format artifacts in CI

core/include/detray/navigation/detail/ray.hpp, core/include/detray/navigation/navigator.hpp, core/include/detray/navigation/policies.hpp, core/include/detray/propagator/actors/aborters.hpp, core/include/detray/propagator/base_stepper.hpp, core/include/detray/propagator/line_stepper.hpp, core/include/detray/propagator/propagator.hpp, core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp, tests/include/detray/test/utils/inspectors.hpp, tests/include/detray/test/utils/simulation/random_scatterer.hpp, tests/include/detray/test/validation/step_tracer.hpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp, tests/integration_tests/cpu/propagator/propagator.cpp, tests/unit_tests/cpu/detectors/telescope_detector.cpp, tests/unit_tests/cpu/navigation/navigator.cpp, tests/unit_tests/cpu/propagator/line_stepper.cpp, tests/unit_tests/cpu/propagator/rk_stepper.cpp, tests/unit_tests/device/cuda/navigator_cuda.cpp, tests/unit_tests/device/cuda/navigator_cuda_kernel.cu, tests/unit_tests/device/cuda/navigator_cuda_kernel.hpp
Decouple the stepper and navigator so that they take only the bare minimum of information needed to fullfill their respective tasks and manipulating each others state becomes impossible. Like this, the interaction between the navigation and the track parameter transport is now visible directly in the propagator instead of being partially hidden in the implementation of the navigator and/or stepper.
Note: The random scatterer observes all material now and the step size scaling is always done with a the minimal and maximal cutoff
=> Ref: decouple stepper and navigator

core/include/detray/propagator/propagator.hpp
The current detray code exposes primarily a `propagate` method, but this has an unbounded loop in it. Because callers might want to implement custom load balancing on the stepping process, the current approach may be too coarse. This commit retains the existing `propagate` method but also adds three new component methods, `propagate_init`, `propagate_step`, and `propagate_is_complete` so that client code can more granularly implement their own, load-balanced propagation.
=> Split propagate function into client components

core/include/detray/navigation/policies.hpp, core/include/detray/propagator/actors/aborters.hpp, core/include/detray/propagator/actors/parameter_resetter.hpp, core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/actors/pointwise_material_interactor.hpp, core/include/detray/propagator/base_stepper.hpp, core/include/detray/propagator/line_stepper.hpp, core/include/detray/propagator/propagator.hpp, core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp, tests/include/detray/test/utils/inspectors.hpp, tests/include/detray/test/utils/simulation/random_scatterer.hpp, tests/include/detray/test/validation/material_validation_utils.hpp, tests/integration_tests/cpu/material/material_interaction.cpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp, tests/integration_tests/cpu/propagator/propagator.cpp, tests/unit_tests/cpu/detectors/telescope_detector.cpp, tests/unit_tests/cpu/propagator/covariance_transport.cpp, tests/unit_tests/cpu/propagator/rk_stepper.cpp
Apply better encapsulation to stepper states. This allows a centralized control over how the data in the state can be changed and allows to insert assertions more easily.
=> Ref: stepper state encapsulation

cmake/detray-config.cmake.in
Made the installed project look for [covfie](https://github.com/acts-project/covfie). Similar to https://github.com/acts-project/acts/pull/3779, I bumped into this issue as well while helping Neza with using [traccc](https://github.com/acts-project/traccc) in [Athena](https://gitlab.cern.ch/atlas/athena/-/tree/main/Projects/Athena).
At the same time removed the `DETRAY_BUILD_CUDA` flag, as it's not relevant for an installed version of the project. 🤔
=> Project Export Fix, main branch (2024.10.24.)

.github/workflows/benchmarks.yml
Only run benchmarking on the main repository. So that it wouldn't start every time I update the `main` branch of my fork. 🤔
The formalism is the same that I used for achieving the same with the Doxygen documentation generation in [vecmem](https://github.com/acts-project/vecmem):
https://github.com/acts-project/vecmem/blob/main/.github/workflows/pages.yml#L32
=> Benchmarking On Main Repo Only, main branch (2024.10.24.)

core/include/detray/utils/tuple.hpp
The current tuple definition is a bit barebones and does not allow assignment on `detray::tie` objects. This commit adds additional functionality to the detray tuple, including assingment.
=> Add more `detray::tuple` features

core/include/detray/navigation/navigation_config.hpp, core/include/detray/navigation/navigator.hpp, core/include/detray/propagator/line_stepper.hpp, core/include/detray/propagator/propagator.hpp, tests/include/detray/test/utils/inspectors.hpp, tests/integration_tests/cpu/detectors/telescope_detector_navigation.cpp, tests/integration_tests/cpu/material/material_interaction.cpp, tests/integration_tests/cpu/propagator/guided_navigator.cpp, tests/integration_tests/cpu/propagator/propagator.cpp, tests/integration_tests/device/cuda/propagator_cuda.cpp, tests/integration_tests/device/cuda/telescope_navigation_validation.cpp, tests/unit_tests/cpu/navigation/navigator.cpp, tests/unit_tests/cpu/propagator/covariance_transport.cpp, tests/unit_tests/cpu/propagator/line_stepper.cpp, tests/unit_tests/device/cuda/navigator_cuda.cpp, tests/unit_tests/device/cuda/navigator_cuda_kernel.cu, tests/unit_tests/device/cuda/navigator_cuda_kernel.hpp, tutorials/src/cpu/propagation/navigation_inspection.cpp
This PR updates the navigation config to the ODD/ITk defaults. This should help to use a more optimal configuration for the ODD and ITk without passing a specific configuration to detray. Not sure, if there is one configuration that will be optimal for all detectors, though, so the telescope detector needs to be configured explicitly now.
The configurations to the propagation also now have to be passed explicitly, which helps not passing the default configuration by mistake.
Edit: while debugging a navigation failure in the telescope with the new default configuration, I added "a last chance" navigation init with loose surface finding constraints that seems to also recover the odd B-field cases.
=> ref: Update the propagation config structs and improve navigation recovery due to extreme portal overstepping

io/include/detray/io/csv/track_parameters.hpp, tests/include/detray/test/validation/step_tracer.hpp
Fixes two assertions that were triggered by navigation validation tools:
- if the step stracer is set to record every step, make sure the barcode is only accessed when actually on surface
- since rays return zero for 'qop', make sure the free track parameter momentum is only written to file if it can be retrieved. Otherwise write the (normalized) direction to file
=> fix: Navigation assertions in validation tools

core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp, tests/include/detray/test/utils/inspectors.hpp
Currently, the Runge-Kutta stepper holds a lot of state which is used only internally. The size of this state is 164 bytes, of which only 140 bytes are needed after the step. Keeping the remaining state between steps is therefore taking up a lot of memory.
In this PR, I remove this internal state from the externally facing stepper state and turn it into an intermediate struct which is not stored persistently, saving 140 bytes on the size of the stepper state (and, with it, the propagator state).
=> Remove unneeded state from Runge-Kutta stepper

core/include/detray/navigation/navigator.hpp
This is to try to address the compiler crash that we've seen with @nribaric earlier this week, and which @flg saw this morning himself.
GCC 13.1 crashes while compiling [traccc's host CKF code](https://github.com/acts-project/traccc/blob/main/core/src/finding/find_tracks.hpp) when `detray::navigator<...>::state::m_candidates` is initialized explicitly with curly braces. 😕
I'm worried about this update though. 🤔 By removing the curly braces, do I eliminate some explicit initialization to the elements of the array? [std::array](https://en.cppreference.com/w/cpp/container/array) has no constructor. So this change should not change anything... right? The code is initializing the array elements to something somewhere else, right? (If the logic requires some initialization that is. If not, then …
=> GCC 13.1 Fix, main branch (2024.11.08.)

core/include/detray/navigation/policies.hpp, core/include/detray/propagator/actor_chain.hpp, core/include/detray/propagator/actors/aborters.hpp, core/include/detray/propagator/actors/parameter_resetter.hpp, core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/actors/pointwise_material_interactor.hpp, core/include/detray/propagator/base_stepper.hpp, core/include/detray/propagator/line_stepper.hpp, core/include/detray/propagator/propagator.hpp, core/include/detray/propagator/rk_stepper.hpp, core/include/detray/propagator/rk_stepper.ipp, tests/integration_tests/cpu/material/material_interaction.cpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp, tests/integration_tests/cpu/propagator/propagator.cpp, tests/unit_tests/cpu/propagator/rk_stepper.cpp
- Shift the update of the step size in the stepper, so that we go from a "previous step size" to a "next step size". 
- Remove the volume material pointer from the state and instead get it from the navigator hand it through to the functions that need it
- Remove the "path from surface" and reimplement it in the actors that use it 
- Remove the ``next_surface_aborter``, which is superseded by the `ckf_aborter` in traccc (need to move the test to traccc)
- Remove the previous surface index and instead use the surface link on the bound track parameters before they are updated
- Remove the stepping direction and calculate it on the fly
Also streamlines the parameter resetter, as the jacobians are already default initialized correctly and a separate kernel is not needed, since the relevant …
=> ref: Remove more state data from the steppers and streamline the parameter resetter

core/include/detray/tracks/bound_track_parameters.hpp
This correction was suggested by @niermann999 as a fix for a compile error with a recent SYCL compiler. And worked. This is mostly to remind detray and ACTS experts that this is something to look into. Maybe this needs to be applied elsewhere.
For info the compiler is:
```
$ clang++ -v
clang version 20.0.0git (https://github.com/intel/llvm e95b34bb2bcef2641d88ca2e09d628039ef269d7)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2025.0/bin
Build config: +assertions
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32 …
```
=> use fabs instead of abs in set_phi to be nice with sycl/clang20

core/include/detray/core/detail/container_buffers.hpp, extern/vecmem/CMakeLists.txt, tests/include/detray/test/device/cuda/material_validation.hpp, tests/include/detray/test/device/cuda/navigation_validation.hpp, tests/integration_tests/device/cuda/propagator_cuda_kernel.hpp, tests/integration_tests/device/sycl/propagator_sycl_kernel.hpp, tests/unit_tests/device/cuda/grids_grid2_cuda.cpp, tests/unit_tests/device/cuda/mask_store_cuda.cpp, tests/unit_tests/device/cuda/navigator_cuda.cpp, tests/unit_tests/device/cuda/utils_ranges_cuda.cpp
Update the project to [vecmem 1.13.0](https://github.com/acts-project/vecmem/releases/tag/v1.13.0). This is needed for the oneAPI 2025.0.0 compatibility updates to be added shortly.
=> VecMem Update, main branch (2024.11.29.)

core/include/detray/definitions/detail/math.hpp, core/include/detray/propagator/detail/jacobian_cartesian.hpp, core/include/detray/propagator/detail/jacobian_cylindrical.hpp, core/include/detray/propagator/detail/jacobian_line.hpp, core/include/detray/propagator/detail/jacobian_polar.hpp, io/include/detray/io/common/geometry_reader.hpp
This is made on top of #890, to allow building the code with oneAPI 2025.0.0.
It's mostly trivial fixes necessitated by the new LLVM/Clang version. With one `<CL/sycl.hpp>` -> `<sycl/sycl.hpp>` change in addition.
=> oneAPI 2025 Updates, main branch (2024.11.29.)

tests/benchmarks/cpu/benchmark_propagator.cpp, tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
Use random, but sorted tracks for benchmarks and copy the detector to device. I also changed the eta range to [-4, 4] and the momentum range to 1Gev - 100GeV
=> ref: More realistic toy detector benchmarks

cmake/detray-compiler-options-cuda.cmake
This allows us to get line information in profilers without having to disable optimizations in the code.
=> Enable line information in RelWithDebInfo

.pre-commit-config.yaml
This is a copy of https://github.com/acts-project/acts/pull/3928; long story short, if git doesn't properly detect that it is not in a TTY, it will hang pre-commit. Therefore, this explicitly disables paging.
=> Explicitly disable git pager in pre-commit

core/include/detray/utils/ranges/detail/iterator_functions.hpp
I was surprised while profiling the detray code to find that a surprisingly large amount of time is spent in the random access iterator advance function. This is somewhat inefficiently implemented as it is full of if statements. I have decided to simplify the function, which leads to a small but noticeable performance improvement of around 4% in the detray benchmarks.
=> Simplify random access iterator advancement

core/include/detray/propagator/actors/pointwise_material_interactor.hpp, tests/integration_tests/cpu/material/material_interaction.cpp, tests/integration_tests/cpu/propagator/backward_propagation.cpp, tests/unit_tests/cpu/simulation/scattering.cpp
Remove the navigation sign for process noise (Multiple scattering and Landau loss)
The added covariance matrix should always be positive.
Ref: https://ntrs.nasa.gov/api/citations/19940031131/downloads/19940031131.pdf
Note: One should not take "the sign of the process noise must be flipped" of the quote as the sign of MS covariance should be changed for backward propagation - The sign referred in the quote is an opposite thing:
=> Remove the Navigation Direction Sign for Process Noise

tests/include/detray/test/common/assert.hpp, tests/unit_tests/device/cuda/sf_finders_grid_cuda.cpp
Currently, we require exact equality on floating point 3D vectors, which is unreasonable. This commit changes the code such that the equality is instead defined with an epsilon value of 1E-6.
=> Use approximate equality checks for 3D point tests

cmake/detray-compiler-options-cuda.cmake
This might be controversial, but we're kneecapping the CUDA build by turning off FMA. I think it's high time to turn it back on. Also removes an inaccurate comment, as FMA doesn't have anything to do with fast math; FMA is well specified in IEEE 754-2008.
=> Reenable FMA in CUDA builds

README.md
Add instructions on how to run the validation and benchmarks tools to the README. Also does a little bit of cleanup/updating of the README and adds a few status badges for the project.
=> feat: Expand README

README.md, core/include/detray/propagator/propagation_config.hpp, core/include/detray/utils/type_list.hpp, tests/tools/python/impl/__init__.py, tests/tools/python/impl/plot_benchmark_results.py, tests/tools/python/plotting/pyplot_factory.py, tests/tools/python/propagation_benchmarks.py, tests/tools/src/cpu/propagation_benchmark.cpp, tests/tools/src/cuda/propagation_benchmark_cuda.cpp, tests/unit_tests/cpu/utils/type_list.cpp
Add python scripts to automatically run the propagation benchmarks and produce different plots from the results
=> feat: benchmark scripts

README.md, core/include/detray/materials/detail/relativistic_quantities.hpp, core/include/detray/navigation/navigator.hpp, core/include/detray/propagator/actors/pointwise_material_interactor.hpp, tests/include/detray/test/cpu/material_scan.hpp, tests/include/detray/test/utils/inspectors.hpp, tests/include/detray/test/validation/detector_scanner.hpp, tests/unit_tests/cpu/utils/grids/populators.cpp, tests/unit_tests/device/cuda/utils_ranges_cuda.cpp
Fixes a couple of assertions:
- A couple of out-of-bounds assertions (material scan, populator test, inspector, detector scanner, ranges cuda test)
- don't pass zero standard deviation to `std::normal_distribution`
=> fix: several assertions

README.md, tests/tools/python/impl/plot_benchmark_results.py, tests/tools/python/propagation_benchmarks.py, tests/tools/src/cpu/propagation_benchmark.cpp, tests/tools/src/cuda/propagation_benchmark_cuda.cpp
This way the benchmark can be run e.g. from a bash script of manually first, calling the plotting script in a second step (the plotting has a lot of dependencies and may not work everywhere). This mainly changes how the files to be plotted are registered in the python tool and that some additional data needs to be added to the benchmarks context. This will be used to e.g. distinguish the different algebra plugins and to set the plot labels correctly.
Also removed the 'interleave' option again, as that makes mostly sense for microbenchmarks and would need an additional sorting step to work correctly
=> ref: Make plotting script work without running the benchmarks from python first

tests/benchmarks/include/detray/benchmarks/cpu/propagation_benchmark.hpp, tests/benchmarks/include/detray/benchmarks/propagation_benchmark_utils.hpp, tests/include/detray/test/utils/simulation/event_generator/random_numbers.hpp, tests/tools/python/impl/__init__.py, tests/tools/python/impl/plot_benchmark_results.py, tests/tools/python/impl/plot_track_params.py, tests/tools/python/plotting/plot_helpers.py, tests/tools/python/plotting/pyplot_factory.py, tests/tools/python/propagation_benchmarks.py, tests/tools/src/cpu/CMakeLists.txt, tests/tools/src/cpu/propagation_scaling.cpp
Add a job that benchmarks CPU weak and strong scaling and makes plots from it across different algebra plugins. I also checked the throughput and realized that this was computed incorrectly by google benchmark in mulitthreaded benchmarks, unless we configure it to measure wall clock time internally. Contains a small fix for the track generator standard deviation that somehow did not make it into a previous PR.
=> feat: plot cpu scaling

CMakeLists.txt, tests/CMakeLists.txt, tests/include/detray/test/device/cuda/material_validation.hpp, tests/tools/CMakeLists.txt, tests/tools/src/cpu/CMakeLists.txt, tests/tools/src/cuda/CMakeLists.txt
Grant more fine grained control of how the CLI tools are built, e.g. if only benchmarks are required, don't build the validation tools and vice versa. Also allows to build the CLI validation tools without building unit and integration CI tests. 
This will be helpful in order to set up the benchmarks across different hardware platforms with minimal dependencies.
=> ref: CLI tools cmake config

core/include/detray/utils/type_list.hpp, tests/unit_tests/cpu/utils/type_list.cpp
Don't use std::sentinel_t in type printing, since the two iterators that std::string can be constructed from need to have the same type. Unfortunately, the detray cuda CI builds are running gcc 13.x, which did not catch this, and the gitlab CUDA CI, which is using gcc 11.4 and could catch this, is not compiling the detector reader but only unit and integration tests
=> fix: Type printing

core/include/detray/core/detail/surface_lookup.hpp
I recently ran into another issue with invalid surface identifiers in traccc, and I found that adding assertions to the surface lookup made it easier to debug. I therefore propose we keep these assertions in detray.
=> Add some assertions to the surface lookup

core/include/detray/definitions/pdg_particle.hpp
This commit reserves PDG particle 0 to denote invalid particles, in accordance with the numbering scheme used in ACTS.
=> Add PDG particle 0 to model errors

core/include/detray/utils/grid/detail/bin_storage.hpp, core/include/detray/utils/grid/detail/bin_view.hpp, core/include/detray/utils/ranges/cartesian_product.hpp, core/include/detray/utils/ranges/enumerate.hpp, core/include/detray/utils/ranges/iota.hpp, core/include/detray/utils/ranges/pick.hpp
Fix a compilation error by providing explicit iterator value types to the tuple that is returned from the cartesian product range.
=> fix: Use explicit types in cartesian product dereferencing

core/include/detray/navigation/volume_graph.hpp, core/include/detray/utils/find_bound.hpp, core/include/detray/utils/grid/detail/axis_binning.hpp, core/include/detray/utils/grid/detail/bin_storage.hpp, core/include/detray/utils/grid/detail/bin_view.hpp, core/include/detray/utils/ranges/cartesian_product.hpp, core/include/detray/utils/ranges/detail/iterator_functions.hpp, core/include/detray/utils/ranges/enumerate.hpp, core/include/detray/utils/ranges/join.hpp, core/include/detray/utils/ranges/pick.hpp, core/include/detray/utils/ranges/ranges.hpp, core/include/detray/utils/ranges/static_join.hpp, tests/include/detray/test/validation/detector_scan_utils.hpp
In c++20, there are new type aliases for iterator member types, which are both more succinct and safer to use
=> ref: New iterator type alias

core/include/detray/builders/surface_factory.hpp
Work around bug in the CUDA 12.8 compiler frontend, so that it would accept this piece of code. 😉 Even if the current version of the code is technically better...
=> CUDA 12.8 Compatibility, main branch (2025.02.18.)

core/include/detray/navigation/navigation_config.hpp, core/include/detray/navigation/navigator.hpp
From the study of https://github.com/acts-project/traccc/pull/869
Also this seems working better with traccc tests when I just use default propagation config.
In case of initializing the candidate search at the new volume or beginning of the propagation, the path tolerance is used instead of overstep tolerance. Currently, there is a bug that track goes backward if it finds surface in opposite direction when `navigator::init` is called at the very beginning of propagation
For example, in the telescope geometry whose envelope size is less than 1 mm, if I start the propagation at the first module, the track will just go back to the portal and terminate the propagation.
=> Change default overstep tolerance to -1 mm

core/include/detray/propagator/actor_chain.hpp, core/include/detray/propagator/base_actor.hpp, core/include/detray/propagator/propagator.hpp, core/include/detray/utils/tuple_helpers.hpp, tests/benchmarks/cpu/propagation.cpp, tests/benchmarks/cuda/propagation.cpp, tests/benchmarks/include/detray/benchmarks/cpu/propagation_benchmark.hpp, tests/include/detray/test/device/cuda/material_validation.cu, tests/include/detray/test/device/propagator_test.hpp, tests/include/detray/test/utils/simulation/random_scatterer.hpp, tests/include/detray/test/validation/material_validation_utils.hpp, tests/integration_tests/cpu/material/material_interaction.cpp, tests/integration_tests/cpu/propagator/backward_propagation.cpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp, tests/integration_tests/cpu/propagator/propagator.cpp, tests/integration_tests/device/cuda/propagator_cuda_kernel.cu, tests/integration_tests/device/sycl/propagator_kernel.sycl, tests/tools/src/cpu/propagation_benchmark.cpp, tests/tools/src/cpu/propagation_scaling.cpp, tests/tools/src/cuda/propagation_benchmark_cuda.cpp, tests/unit_tests/cpu/propagator/covariance_transport.cpp, tutorials/src/device/cuda/propagation_kernel.cu
This PR ensures that the local state tuple type in the actor chain also contains the states of all observing actors in a flattened tuple. At the same time, it makes sure that empty default states are not included and therefore also do not need to be passed to the propagator. Consequently, the empty states were removed everywhere now.
In the propagator the actor state tuple type is auto deduced, so that we do not depend on the order of actors in the chain anymore (this will simplify the KF in traccc).
=> fix: state tuple type and remove empty states

core/include/detray/builders/detail/bin_association.hpp, tests/include/detray/test/utils/detectors/build_toy_detector.hpp
Fix some nullpointer dereferencing warnings in the bin association and toy detector builder
=> fix: a few compiler warnings

CMakeLists.txt, core/include/detray/navigation/direct_navigator.hpp, core/include/detray/navigation/intersection/ray_cylinder_intersector.hpp, core/include/detray/navigation/intersection/ray_cylinder_portal_intersector.hpp, core/include/detray/navigation/navigator.hpp, core/include/detray/propagator/actors.hpp, core/include/detray/propagator/actors/barcode_sequencer.hpp, core/include/detray/propagator/propagator.hpp, tests/integration_tests/cpu/material/material_interaction.cpp, tests/integration_tests/cpu/propagator/backward_propagation.cpp, tests/integration_tests/cpu/propagator/propagator.cpp, tests/unit_tests/cpu/propagator/covariance_transport.cpp
This PR implements direct navigator.
The direct navigator runs on the input surface sequence which include all types of surfaces (passive, sensitive and portals)
The input sequence can be collected from previous run of propagator using `barcode_sequencer` actor
It is also designed to work with both forward and backward directions.
The PR also fixes the bug that `path` is not written in the cylinder intersections when `path < overstep tolerance`, which occasionally killed the propagation with direct navigator and small overstep tolerance.
Also This PR sets the volume in the propagator constructor with bound parameter inputs.
=> Implementing direct navigator

tests/include/detray/test/cpu/navigation_validation.hpp, tests/include/detray/test/device/cuda/navigation_validation.hpp, tests/include/detray/test/validation/navigation_validation_utils.hpp, tests/include/detray/test/validation/svg_display.hpp
Fix a couple of bugs:
- don't check for swapped portals on the last record (out of bounds exception)
- don't count the initial intersection record into the total number of surfaces (it exists only to capture the initial track state)
- iterate over all elements of the larger intersection trace, since the smaller intersection trace will be filled with dummy elements until it has the same length
Apart from that, it allows to count the total and missed number of surfaces per surface type now. This can help identifying if a problem lies e.g. with the portal finding or the acceleration structures.
=> Fix: Calculation of surface finding efficiency per type

core/include/detray/navigation/intersection/helix_line_intersector.hpp, core/include/detray/tracks/helix.hpp, tests/include/detray/test/cpu/detector_scan.hpp, tests/include/detray/test/cpu/navigation_validation.hpp, tests/include/detray/test/device/cuda/navigation_validation.hpp, tests/integration_tests/cpu/propagator/covariance_transport.cpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp, tests/integration_tests/cpu/propagator/propagator.cpp, tests/tools/src/cpu/generate_telescope_detector.cpp, tests/unit_tests/cpu/detectors/telescope_detector.cpp, tests/unit_tests/cpu/navigation/intersection/helix_intersector.cpp, tests/unit_tests/cpu/navigation/intersection/helix_trajectory.cpp, tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp, tests/unit_tests/cpu/propagator/rk_stepper.cpp, tests/unit_tests/cpu/simulation/detector_scanner.cpp, tests/unit_tests/cpu/simulation/track_generators.cpp, tests/unit_tests/svgtools/trajectories.cpp, tests/unit_tests/svgtools/web.cpp, tutorials/src/cpu/detector/build_predefined_detectors.cpp
Adds a constructor that samples the B field direction from covfie and constructs a helix around. This way, a helix can be constructed directly from a constant covfie field
=> ref: Allow to construct helices from all b field types

core/include/detray/navigation/intersection/ray_line_intersector.hpp, tests/benchmarks/cpu/intersect_surfaces.cpp, tests/benchmarks/cpu/intersectors.cpp
While adding the Fastor backend to `detray`, I found some spelling mistakes in some of the benchmark names, which I fixed.
In `core/include/detray/navigation/intersection/ray_line_intersector.hpp`, there is a line which uses `auto` for type deduction, which was giving me problems with Fastor, because `auto` was resolving to an expression template and then causing compilation errors further down the line. I changed it to an explicit type (`vector3_type`) to force evaluation.
This shouldn't be too controversial, as it works for all math backends (including Fastor), and makes the intent of the line clearer.
The Fastor PR is going to be big, so that's why I wanted to make this separate, smaller PR first.
=> Fixed spelling and opted for explicit typing

core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/base_stepper.hpp, tests/integration_tests/cpu/propagator/jacobian_validation.cpp
Redo #832 again as full jacobian won't be required after acts-project/traccc#926
```
Running ./bin/detray_benchmark_cuda_propagation_array
Run on (32 X 3000 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x16)
L1 Instruction 32 KiB (x16)
L2 Unified 512 KiB (x16)
L3 Unified 16384 KiB (x8)
Load Average: 2.05, 2.06, 1.23
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                    Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------------------- …
```
=> Remove full jacobian from stepper

README.md, cmake/detray-compiler-options-cpp.cmake, cmake/detray-compiler-options-cuda.cmake, cmake/detray-compiler-options-sycl.cmake
Due to the poor design of CMake's FetchContent module, detray's compilation flags are leaking into its parents projects. In particular, some important flags like the CUDA architecture flags are being overwritten by detray. In order to prevent that problem, this PR ensures that detray's build system only adds compiler flags to the global CMake variables if it is the top level project.
=> Prevent CMake flags from propagating to parent

core/include/detray/propagator/actors/parameter_transporter.hpp
Go from evaluating 6x8 matrices to evaluating 8x6 matrices. Since our matrices are stored column wise, it is easier to fill larger vector registers this way (each column fits into an avx register in single precision)
~Edit: Also adds the precision for printing matrices when using the streaming operators in conjunction with google test error outputs (which seem to manipulate the stream state?)~
=> feat: improve vectorization by changing the order of evaluation

core/include/detray/navigation/detail/print_state.hpp, core/include/detray/navigation/navigator.hpp, tests/include/detray/test/utils/inspectors.hpp
Fix a few bugs in the print inspector and make navigation state printing available outside the inspector. This way it can be printed with `std::cout` during host side debugging
=> Fix navigation print inspector

tests/include/detray/test/utils/perigee_stopper.hpp
Allow to stop the navigation after reverting the direction. Currently still uses step size constraints, that will be fixed in a future PR
=> feat: Add perigee stopper

tests/include/detray/test/utils/simulation/random_scatterer.hpp
Update the track momentum and trigger re-navigation only when the surface has material with non-zero thickness.
=> ref: update random scatter only when material is non-zero

core/include/detray/navigation/direct_navigator.hpp, core/include/detray/navigation/navigator.hpp, core/include/detray/propagator/actors/aborters.hpp, tests/include/detray/test/utils/inspectors.hpp, tests/include/detray/test/validation/navigation_validation_utils.hpp
Allow to pass additional messages to the navigator abort function that contain the reason for the failure. This will make it easier to debug, because it can be seen right away from where `abort` was called and why. The reason for the error is also preserved in the print inspector, which makes it easier to print it to the user in tests outside the debug file.
=> feat: abort messages

tests/unit_tests/cpu/navigation/intersection/line_intersector.cpp
The gcc 14.2 null-pointer dereference warning seems to be _very_ good, and so it started to shout about this line intersector test which accesses intersections in a vector without first checking the size of the vector. Adding the size check makes the warning go away.
=> Fix potential null dereference warning in tests

tests/include/detray/test/utils/simulation/event_generator/random_numbers.hpp
This *should* work now, since the measurement map in traccc was fixed
=> fix: Remove hotfix from random numbers

README.md, core/include/detray/builders/cuboid_portal_generator.hpp, core/include/detray/builders/cylinder_portal_generator.hpp, core/include/detray/builders/surface_factory.hpp, core/include/detray/builders/volume_builder.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp, plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp, tests/include/detray/test/common/factories/barrel_generator.hpp, tests/include/detray/test/common/factories/endcap_generator.hpp, tests/include/detray/test/common/factories/telescope_generator.hpp, tests/include/detray/test/common/factories/wire_layer_generator.hpp, tests/include/detray/test/cpu/toy_detector_test.hpp, tests/include/detray/test/validation/detector_scanner.hpp, tests/integration_tests/cpu/builders/material_map_builder.cpp, tutorials/include/detray/tutorial/square_surface_generator.hpp
During surface construction, the material link was not set such that `is_invalid` would be true for a surface with no material. This lead to an incorrect material access in the SVG illustrator when trying to display surface material. Also added some additional checks in the illustrator for too large volume and surface indices that can be requested by the user.
=> fix: out of bounds error in detector display tool

core/include/detray/builders/material_map_generator.hpp, plugins/svgtools/include/detray/plugins/svgtools/conversion/surface_material.hpp, plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp, tests/include/detray/test/common/build_toy_detector.hpp, tests/include/detray/test/cpu/material_validation.hpp, tests/include/detray/test/cpu/toy_detector_test.hpp, tests/integration_tests/cpu/detectors/toy_detector_navigation.cpp
Fixes the bin index range for material maps in the SVG display and ensures that the material thickness in material maps that are translated in z scales with regard to the origin instead of their midpoint. This changes the material of the toy detector slightly, including more bins for the now fused disc maps, so that the test need to be adapted.
=> fix: Material maps display and scale toy material maps

core/include/detray/geometry/detail/tracking_surface_kernels.hpp, core/include/detray/geometry/tracking_surface.hpp, core/include/detray/propagator/actors/parameter_transporter.hpp, core/include/detray/propagator/detail/jacobian_engine.hpp, core/include/detray/utils/curvilinear_frame.hpp, tests/integration_tests/cpu/propagator/covariance_transport.cpp, tests/unit_tests/cpu/propagator/jacobian_cartesian.cpp, tests/unit_tests/cpu/propagator/jacobian_cylindrical.cpp, tests/unit_tests/cpu/propagator/jacobian_line.cpp, tests/unit_tests/cpu/propagator/jacobian_polar.cpp
Currently, the covariance transport uses the Jacobian engine which is templated on the frame type. While this makes the code easier to read and write, it requires the compiler to duplicate a lot of code for each of the frame types, and this duplicated code counts as multiple branches for the sake of GPU execution. Thus, this templating increases the amount of thread divergence.
This commit refactors the Jacobian engine into smaller parts, some of which are templated on the frame type and some of which are not. Client code and then take a more fine-grained approach to branching and improve divergence.
=> Reduce thread divergence in covariance transport

core/include/detray/core/detail/indexing.hpp, core/include/detray/utils/bit_encoder.hpp, tests/include/detray/test/cpu/toy_detector_test.hpp, tests/unit_tests/cpu/core/indexing.cpp
Increase the bits for the index range back to 64, because otherwise overflows can happen in the material maps, where the grid collections might have to index a couple of 100 000 bins. Also added an assertion that will catch this in the future.
=> fix: index range size

plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp, plugins/svgtools/include/detray/plugins/svgtools/meta/proto/eta_lines.hpp, tests/tools/python/impl/plot_track_params.py, tests/tools/src/cpu/detector_display.cpp
Allow the direct configuration of the axes length and font size in the detector display. Also removes the eta=5 line, which overlaps with the z-axis
=> feat: Configurable axes in detector display

tests/tools/src/cpu/propagation_scaling.cpp
Choose  a track sample size that is divisible by the number of threads
=> ref: Adapt number of track samples in scaling benchmark

core/include/detray/utils/consistency_checker.hpp, tests/include/detray/test/common/event_generator/uniform_track_generator_config.hpp, tests/tools/src/cpu/detector_display.cpp, tests/tools/src/cuda/material_validation_cuda.cpp
Fix the `datadir` option also for the CUDA material validation to make the material validation python script work. Also fixes a few typos
=> Fix: data dir option for cuda material validation

core/include/detray/navigation/navigator.hpp, core/include/detray/propagator/propagator.hpp
This commit flattens the propagation loop structure with the primary goal of reducing the number of different call sites to the navigation update method. Currently. we update the navigator in three different places and this is expensive due to divergence. This commit puts all of those calls into one place in a loop, mirroring the same functional structure that was present before.
I measure a significant performance improvement due to this in traccc, and it also greatly reduces the size of the kernels.
=> Flatten propagation loop structure

tests/integration_tests/cpu/propagator/propagator.cpp
Remove a print statement from a tight loop that clutters the integration test output
=> ref: Remove verbose print

core/include/detray/builders/homogeneous_material_factory.hpp
Previously, the homogeneous material writer would unconditionally overwrite material in surfaces which already have e.g. material grids. This is now checked and the surface is skipped.
=> fix: don't override material in homogeneous material factory

.github/workflows/builds.yml
Some benchmark builds are currently disabled in the CI and only the build used for the continuous benchmark is tested. This PR switches all benchmark builds on and fixes resulting errors
=> fix: Switch on all benchmark build variations in the CI

plugins/algebra/CMakeLists.txt, tests/CMakeLists.txt, tests/benchmarks/include/detray/benchmarks/cpu/CMakeLists.txt, tests/benchmarks/include/detray/benchmarks/device/cuda/CMakeLists.txt, tests/include/detray/test/cpu/CMakeLists.txt, tests/include/detray/test/device/CMakeLists.txt, tests/include/detray/test/device/cuda/CMakeLists.txt, tests/integration_tests/device/cuda/CMakeLists.txt, tests/tools/CMakeLists.txt, tests/tools/src/cuda/CMakeLists.txt
Link the cuda propagation integration test against the `test_device` component and add more status messages
=> fix: CUDA integration test linking and make cmake more verbose

core/include/detray/definitions/detail/hip_definitions.hpp, tests/benchmarks/include/detray/benchmarks/device/hip/propagation_benchmark.hip, tests/tools/python/propagation_benchmarks.py
Add the HIP AMD and NVIDIA benchmark options to the python benchmark script. Also fixes a few compiler warnings for the benchmarks and adjusts the warp size, which is not always 32 on AMD devices
=> feat: add HIP backends to python benchmark script and fix a few warnings
