- core/include/geometry/detector.hpp
- core/include/grids/grid2.hpp
- core/include/grids/populator.hpp
- tests/unit_tests/core/CMakeLists.txt
- tests/unit_tests/core/grids_grid2.cpp
- tests/unit_tests/core/grids_populator.cpp
This PR adds populators for grids, the final ingredient for making a first grid setup.
> feat: adding populators

- core/include/grids/grid2.hpp
- core/include/grids/populator.hpp
- tests/unit_tests/core/grids_grid2.cpp
- tests/unit_tests/core/grids_populator.cpp
Thi PR adds finally the 2D grid & its unit tests
> feat: adding 2d grid

- core/include/core/detector.hpp
- core/include/tools/local_object_finder.hpp
- tests/common/include/tests/common/test_detector.hpp
- tests/unit_tests/core/CMakeLists.txt
- tests/unit_tests/core/grids_axis.cpp
- tests/unit_tests/core/grids_grid2.cpp
- tests/unit_tests/core/utils_local_object_finder.cpp
This adds local object finding capability to the core repository & adds an appropriate unit test.
> feat: adding infrastructure for local object finder

- core/include/core/detector.hpp
- core/include/grids/axis.hpp
- core/include/grids/grid2.hpp
- core/include/tools/local_object_finder.hpp
- tests/common/include/tests/common/single_layer_detector.hpp
- tests/common/include/tests/common/test_cylinder_intersection.inl
- tests/common/include/tests/common/test_single_layer_detector.inl
- tests/common/include/tests/common/test_surfaces.hpp
This PR introduces the first single layer with local object finder.
It also includes a test that all surfaces are found in comparison to a heuristic module that does trial and error.
> feat: single layer detector

- tests/common/include/tests/common/test_single_layer_detector.inl
> fix: switch csv writing for single layer detector off

- core/include/masks/annulus2.hpp
- core/include/masks/cylinder3.hpp
- core/include/masks/rectangle2.hpp
- core/include/masks/ring2.hpp
- core/include/masks/single3.hpp
- core/include/masks/trapezoid2.hpp
- core/include/masks/unmasked.hpp
- core/include/tools/concentric_cylinder_intersector.hpp
- core/include/tools/cylinder_intersector.hpp
- core/include/tools/planar_intersector.hpp
- tests/common/include/tests/common/benchmark_masks.inl
- tests/common/include/tests/common/masks_annulus2.inl
- tests/common/include/tests/common/masks_cylinder3.inl
- tests/common/include/tests/common/masks_rectangle2.inl
- tests/common/include/tests/common/masks_ring2.inl
- tests/common/include/tests/common/masks_trapezoid2.inl
- tests/common/include/tests/common/masks_unmasked.inl
This PR adds mask_specific tolerance definitions and allows interjectors to set them.
> feat: adding mask-specific tolerances to masks and intersectors

- core/include/grids/grid2.hpp
- tests/common/include/tests/common/test_single_layer_components.inl
This PR includes a special treatment for grids where the `store_type` and the `base_type` are equal.
It speeds up layers navigation with single grid entry access.
> feat: speed improve bare equals store grid access

- apps/common/include/apps/common/display_volumes_rz.inl
- core/include/core/proto_detector.hpp
- core/include/grids/axis.hpp
- core/include/grids/grid2.hpp
- core/include/grids/serializer2.hpp
- display/include/view/draw.hpp
- display/include/view/generators.hpp
- display/include/view/views.hpp
- tests/benchmarks/CMakeLists.txt
- tests/benchmarks/core/CMakeLists.txt
- tests/benchmarks/core/benchmark_grids.cpp
- tests/common/include/tests/common/io_read_detector.inl
- tests/common/include/tests/common/test_single_layer_components.inl
- tests/common/include/tests/common/test_surfaces.hpp
- tests/unit_tests/core/grids_axis.cpp
- tests/unit_tests/core/grids_grid2.cpp
- tests/unit_tests/core/grids_serializer.cpp
- tests/unit_tests/core/utils_local_object_finder.cpp
This PR adds the possibility to use irregular grids and adds a unit test and benchmark tests for grids.
> feat:  introduce irregular grid

- apps/common/include/apps/common/display_volumes_rz.inl
- core/include/core/proto_detector.hpp
- core/include/core/transform_store.hpp
- core/include/grids/axis.hpp
- core/include/grids/grid2.hpp
- io/csv/include/io/csv_io.hpp
This PR out-detects volume boundaries and creates the volume search map for full-2pi closed detectors.
> feat: teaching the volumes to know another

- core/include/core/proto_detector.hpp
- tests/benchmarks/CMakeLists.txt
- tests/benchmarks/eigen/CMakeLists.txt
- tests/benchmarks/eigen/eigen_find_volume.cpp
- tests/common/include/tests/common/benchmark_find_volume.inl
This PR adds a new benchmark test for searching the start volume.
> feat: add volume search benchmark

- core/include/core/detector.hpp
- core/include/core/transform_store.hpp
- core/include/core/volume_connector.hpp
- core/include/masks/cylinder3.hpp
- core/include/masks/single3.hpp
- core/include/tools/cylinder_intersector.hpp
- core/include/tools/intersection_kernel.hpp
- core/include/tools/local_object_finder.hpp
- core/include/tools/navigator.hpp
- core/include/utils/enumerate.hpp
- io/csv/include/io/csv_io.hpp
- tests/common/include/tests/common/benchmark_intersect_all.inl
- tests/common/include/tests/common/benchmark_intersect_surfaces.inl
- tests/common/include/tests/common/core_detector.inl
- tests/common/include/tests/common/masks_single3.inl
- tests/common/include/tests/common/tools_cylinder_intersection.inl
- tests/common/include/tests/common/tools_navigator.inl
This PR harmonises `surfaces` and `portals` within a detector in order to use the same intersection kernel.
> feat: harmonize surfaces and portals

- core/include/core/detector.hpp
- core/include/core/intersection.hpp
- core/include/core/volume_connector.hpp
- core/include/masks/annulus2.hpp
- core/include/masks/cylinder3.hpp
- core/include/masks/rectangle2.hpp
- core/include/masks/ring2.hpp
- core/include/masks/single3.hpp
- core/include/masks/trapezoid2.hpp
- core/include/masks/unmasked.hpp
- core/include/tools/cylinder_intersector.hpp
- core/include/tools/intersection_kernel.hpp
- core/include/tools/navigator.hpp
- io/csv/include/io/csv_io.hpp
- tests/common/include/tests/common/tools_intersection_kernel.inl
- tests/common/include/tests/common/tools_navigator.inl
This PR adds more functionality for the navigator, it steps through the first volume.
> feat: further progress in navigator behavior

- core/include/core/volume_connector.hpp
- core/include/tools/concentric_cylinder_intersector.hpp
- core/include/tools/cylinder_intersector.hpp
- core/include/tools/navigator.hpp
- core/include/tools/planar_intersector.hpp
- tests/benchmarks/core/benchmark_grids.cpp
- tests/common/include/tests/common/benchmark_intersect_all.inl
- tests/common/include/tests/common/benchmark_intersect_surfaces.inl
- tests/common/include/tests/common/test_surfaces.hpp
- tests/common/include/tests/common/tools_navigator.inl
- tests/unit_tests/core/grids_grid2.cpp
First unit tested navigator with successful walk through a few volumes and surfaces.
> feat: first sort of navigator

- core/include/tools/line_stepper.hpp
- core/include/utils/c_step.hpp
- tests/common/include/tests/common/tools_line_stepper.inl
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/array/array_line_stepper.cpp
- tests/unit_tests/eigen/eigen_line_stepper.cpp
A very simple `line_steppe` implementation.
> feat: adding simple line_stepper

- core/include/core/volume_connector.hpp
- core/include/grids/grid2.hpp
- core/include/tools/cylinder_intersector.hpp
- core/include/tools/intersection_kernel.hpp
- core/include/tools/line_stepper.hpp
- core/include/tools/navigator.hpp
- core/include/tools/propagator.hpp
- display/include/view/draw.hpp
- tests/common/include/tests/common/benchmark_intersect_all.inl
- tests/common/include/tests/common/io_read_detector.inl
- tests/common/include/tests/common/tools_line_stepper.inl
- tests/common/include/tests/common/tools_navigator.inl
- tests/common/include/tests/common/tools_propagator.inl
- tests/unit_tests/CMakeLists.txt
- tests/unit_tests/array/array_propagator.cpp
- tests/unit_tests/eigen/eigen_propagator.cpp
A first version of a very rudimentary propagator.
> feat:  introduce propagator

- apps/src/eigen/eigen_display_volumes_rz.cpp
This PR fixes the apps directory wrt the external math library.
> fix: apps for external algebra

- core/include/grids/axis.hpp
- core/include/grids/grid2.hpp
- core/include/tools/local_object_finder.hpp
- tests/benchmarks/core/benchmark_grids.cpp
- tests/common/include/tests/common/benchmark_find_volume.inl
- tests/common/include/tests/common/test_surfaces.hpp
- tests/unit_tests/core/grids_axis.cpp
- tests/unit_tests/core/grids_grid2.cpp
This PR adds binned and scalar range zones for the grid2 and the axes.
> feat: added binned/scalar range to grid and zone

- core/include/core/detector.hpp
- core/include/core/volume_connector.hpp
- core/include/grids/axis.hpp
- core/include/grids/grid2.hpp
- core/include/grids/populator.hpp
- core/include/grids/serializer2.hpp
- core/include/masks/annulus2.hpp
- core/include/masks/cylinder3.hpp
- core/include/masks/rectangle2.hpp
- core/include/masks/ring2.hpp
- core/include/masks/single3.hpp
- core/include/masks/trapezoid2.hpp
- core/include/tools/concentric_cylinder_intersector.hpp
- core/include/tools/line_stepper.hpp
- core/include/tools/local_object_finder.hpp
- core/include/tools/navigator.hpp
- core/include/utils/c_step.hpp
- core/include/utils/enumerate.hpp
- core/include/utils/quadratic_equation.hpp
- tests/benchmarks/core/benchmark_grids.cpp
- tests/common/include/tests/common/benchmark_intersect_surfaces.inl
- tests/common/include/tests/common/test_surfaces.hpp
- tests/common/include/tests/common/tools_intersection_kernel.inl
- tests/unit_tests/core/grids_axis.cpp
- tests/unit_tests/core/grids_grid2.cpp
- tests/unit_tests/core/grids_serializer.cpp
- tests/unit_tests/core/utils_local_object_finder.cpp
This PR adds container templates to all of the core package
> Feat use template types

- apps/common/include/apps/common/display_layers.inl
- apps/common/include/apps/common/display_volumes_rz.inl
- core/include/core/volume_connector.hpp
- core/include/tools/local_object_finder.hpp
- display/include/view/draw.hpp
- io/csv/include/io/csv_io.hpp
- io/csv/include/io/csv_io_types.hpp
- tests/common/include/tests/common/benchmark_find_volume.inl
- tests/common/include/tests/common/benchmark_intersect_all.inl
- tests/common/include/tests/common/io_read_detector.inl
- tests/common/include/tests/common/tools_navigator.inl
- tests/common/include/tests/common/tools_propagator.inl
This PR prepares the reading from CSV and using custom container types.
> feat: prepare detector reading with vecmem

- apps/common/include/apps/common/display_layers.inl
- display/include/view/draw.hpp
- display/include/view/views.hpp
This adds a z_phi view to the display package.
> feat: add z_phi view

- apps/common/include/apps/common/display_bin_association.inl
- apps/common/include/apps/common/display_layers.inl
- apps/src/eigen/CMakeLists.txt
- apps/src/eigen/eigen_display_bin_association.cpp
- core/include/grids/associator.hpp
- core/include/grids/axis.hpp
- core/include/utils/generators.hpp
- display/include/style/styles.hpp
- display/include/view/draw.hpp
This PR introduces the first bin-association algorithm for r/phi disks.
> feat: introduce bin association for disks

- apps/common/include/apps/common/display_bin_association.inl
- apps/common/include/apps/common/display_layers.inl
- core/include/grids/associator.hpp
- display/include/view/draw.hpp
This PR introduces phi wrapping in the display and (eventually) z-phi bin association.
> feat: z phi association

- apps/common/include/apps/common/display_layers.inl
- core/include/core/surface_base.hpp
- io/csv/include/io/csv_io.hpp
This is mostly cleanest in the surface_base class.
> chore: few fixes in surface_base

- .github/workflows/builds.yml
Remove the benchmark push until #100 is resolved. This solves the CI problem for the ubuntu build.
> fix: comment benchmark push

- tests/unit_tests/core/CMakeLists.txt
- tests/unit_tests/core/thrust_tuple.cpp
Added a trivial example of using [Thrust](https://github.com/NVIDIA/thrust) in C++ code. Hopefully helping code development with this a little...
> Thrust C++ Example, main branch (2021.11.04.)

- CMakeLists.txt
Update the project to version to `0.2`. Now that release [v0.1.0](https://github.com/acts-project/detray/releases/tag/v0.1.0) has been created. :wink:
> Project Version Update, main branch (2021.11.08.)

- CMakeLists.txt
Update the project to version to 0.3
> Project Version update

- core/include/detray/core/detector.hpp
- core/include/detray/grids/axis.hpp
- core/include/detray/grids/grid2.hpp
- io/csv/include/detray/io/csv_io.hpp
- tests/benchmarks/core/benchmark_grids.cpp
- tests/common/include/tests/common/core_detector.inl
- tests/common/include/tests/common/tools/test_surfaces.hpp
- tests/unit_tests/core/grids_axis.cpp
- tests/unit_tests/core/grids_grid2.cpp
- tests/unit_tests/core/grids_serializer.cpp
- tests/unit_tests/core/utils_local_object_finder.cpp
- tests/unit_tests/cuda/grids_grid2_cuda.cpp
- tests/unit_tests/cuda/grids_grid2_cuda_kernel.cu
- tests/unit_tests/cuda/grids_grid2_cuda_kernel.hpp
yeah we need it for `irregular` axis type that contains vector member variables...
**Update on Dec 1st** 
I added one additional unit test for irregular axis in `grids_grid2_cuda.cpp`
@niermann999 would you review it?
> Add `axis_data` for device

- core/include/detray/core/detector.hpp
- core/include/detray/core/track.hpp
- core/include/detray/geometry/surface_base.hpp
- core/include/detray/grids/populator.hpp
- core/include/detray/masks/single3.hpp
- core/include/detray/tools/bin_association.hpp
- core/include/detray/tools/concentric_cylinder_intersector.hpp
- core/include/detray/tools/geometry_graph.hpp
- core/include/detray/tools/local_object_finder.hpp
- core/include/detray/utils/generators.hpp
- io/csv/include/detray/io/csv_io.hpp
- tests/common/include/tests/common/check_geometry_navigation.inl
- tests/common/include/tests/common/check_geometry_scan.inl
- tests/common/include/tests/common/geometry_graph.inl
- tests/common/include/tests/common/test_toy_geometry.inl
- tests/common/include/tests/common/tools/create_toy_geometry.hpp
- tests/common/include/tests/common/tools/hash_tree.hpp
- tests/common/include/tests/common/tools/ray_gun.hpp
- tests/common/include/tests/common/tools/ray_scan_utils.hpp
- tests/common/include/tests/common/tools/test_surfaces.hpp
- tests/common/include/tests/common/tools_intersection_kernel.inl
- tests/unit_tests/cuda/detector_cuda.cpp
- tests/unit_tests/cuda/detector_cuda_kernel.cu
- tests/unit_tests/cuda/detector_cuda_kernel.hpp
- tests/unit_tests/cuda/grids_grid2_cuda.cpp
Remove warnings to handle #131
> Remove warnings

- tests/common/include/tests/common/tools/create_toy_geometry.hpp
- tests/unit_tests/cuda/grids_grid2_cuda_kernel.cu
@niermann999 Do you have a specific reason in using `double` in `create_toy_geometry.hpp`? Otherwise, let's change them to `scalar`
> change double to scalar in create_toy_geometry.hpp

- CMakeLists.txt
Updated the project version after creating the [v0.3.0](https://github.com/acts-project/detray/releases/tag/v0.3.0) release.
> Project Version Update, main branch (2022.01.21.)

- .github/workflows/builds.yml
> update CI cuda to 11.5.0

- core/include/detray/core/mask_store.hpp
Removing unnecessary lines in mask store data
> remove unnecessary lines in mask store data

- extern/vecmem/CMakeLists.txt
Update VecMem to address the issue in acts-project/vecmem#159
> Update VecMem to v0.9.0

- core/include/detray/definitions/cuda_defs.hpp
- extern/vecmem/CMakeLists.txt
- tests/unit_tests/cuda/CMakeLists.txt
- tests/unit_tests/cuda/detector_cuda.cpp
- tests/unit_tests/cuda/detector_cuda_kernel.cu
- tests/unit_tests/cuda/detector_cuda_kernel.hpp
- tests/unit_tests/cuda/utils_enumerate_cuda.cpp
- tests/unit_tests/cuda/utils_enumerate_cuda_kernel.cu
- tests/unit_tests/cuda/utils_enumerate_cuda_kernel.hpp
This PR tests the functions defined in `enumerate.hpp`.
> Add CUDA unit tests for enumeration

- core/include/detray/tools/navigator.hpp
- tests/common/include/tests/common/tools_propagator.inl
- tests/unit_tests/cuda/navigator_cuda.cpp
- tests/unit_tests/cuda/navigator_cuda_kernel.cu
- tests/unit_tests/cuda/navigator_cuda_kernel.hpp
As we discussed in the meeting, I replace the normal detector object with pointer
> Use pointer for detector in navigator class

- CMakeLists.txt
Updated the project version to `0.5`, now that I tagged https://github.com/acts-project/detray/releases/tag/v0.4.0. :wink:
> Project Version Update, main branch (2022.02.09.)

- core/include/detray/core/detector.hpp
- core/include/detray/tools/base_stepper.hpp
- core/include/detray/tools/navigator.hpp
- core/include/detray/tools/propagator.hpp
- core/include/detray/tools/rk_stepper.hpp
- tests/common/include/tests/common/check_geometry_navigation.inl
- tests/common/include/tests/common/tools_navigator.inl
- tests/common/include/tests/common/tools_propagator.inl
- tests/unit_tests/cuda/CMakeLists.txt
- tests/unit_tests/cuda/navigator_cuda.cpp
- tests/unit_tests/cuda/navigator_cuda_kernel.cu
- tests/unit_tests/cuda/navigator_cuda_kernel.hpp
- tests/unit_tests/cuda/propagator_cuda.cpp
- tests/unit_tests/cuda/propagator_cuda_kernel.cu
- tests/unit_tests/cuda/propagator_cuda_kernel.hpp
I need to add cuda unit test and benchmark test but early comments will be welcomed.
> Propagator with RK stepper

- core/include/detray/core/detector.hpp
- core/include/detray/core/transform_store.hpp
- core/include/detray/definitions/detail/accessor.hpp
- core/include/detray/geometry/volume.hpp
- core/include/detray/tools/concentric_cylinder_intersector.hpp
- core/include/detray/tools/cylinder_intersector.hpp
- core/include/detray/tools/intersection_kernel.hpp
- core/include/detray/tools/navigator.hpp
- core/include/detray/tools/volume_graph.hpp
- core/include/detray/utils/enumerate.hpp
- tests/benchmarks/core/benchmark_grids.cpp
- tests/common/include/tests/common/benchmark_intersect_surfaces.inl
- tests/common/include/tests/common/core_detector.inl
- tests/common/include/tests/common/core_transform_store.inl
- tests/common/include/tests/common/masks_single3.inl
- tests/common/include/tests/common/masks_unmasked.inl
- tests/common/include/tests/common/test_core.inl
- tests/common/include/tests/common/test_defs.hpp
- tests/common/include/tests/common/tools/helix_gun.hpp
- tests/common/include/tests/common/tools/ray_scan_utils.hpp
- tests/common/include/tests/common/tools/test_surfaces.hpp
- tests/common/include/tests/common/tools_cylinder_intersection.inl
- tests/common/include/tests/common/tools_intersection_kernel.inl
- tests/common/include/tests/common/tools_planar_intersection.inl
- tests/common/include/tests/common/tools_track.inl
> chore: clean clang warnings

- core/include/detray/tools/track.hpp
- tests/common/include/tests/common/tools/helix_gun.hpp
- tests/common/include/tests/common/tools_helix_gun.inl
- tests/common/include/tests/common/tools_rk_stepper.inl
- tests/common/include/tests/common/tools_track.inl
This PR fixes a bug in `helix_gun` that it doesn't work with general value of b field.
Also I make it work for the momentum parallel with b field and add a unit test for that.
> Fix a bug in `helix_gun`

- tests/common/include/tests/common/tools_propagator.inl
@niermann999 I made `tools_propagator.inl` do the same thing with `propagator_cuda.cpp` so that you can test the propagator easily with general magnetic field.
When you test #220, I suggest adding more b-field cases in `INSTANTIATE_TEST_SUITE_P`.
> detailed propagation unit test

- extern/algebra-plugins/CMakeLists.txt
Let's go with new version of algebra plugins
> Update algebra-plugins to v0.8.0

- core/include/detray/core/detector.hpp
- core/include/detray/geometry/volume.hpp
- core/include/detray/geometry/volume_connector.hpp
- io/csv/include/detray/io/csv_io.hpp
- tests/common/include/tests/common/geometry_volume.inl
This PR aims to add a `scalar_type` template parameter for the volume class
(https://github.com/acts-project/detray/issues/246)
> templatize the scalar type in volume class

- CMakeLists.txt
> Project Version Update, main branch (2022.06.08.)

- CMakeLists.txt
Update project version to 0.10.0
> Update project version to 0.10.0

- CMakeLists.txt
- extern/actsvg/CMakeLists.txt
- extern/actsvg/README.md
This PR simply adds the ACTSVG plugin, it depends on #288
> feat: add svg display

- CMakeLists.txt
Updated the project version to `0.12` following the https://github.com/acts-project/detray/releases/tag/v0.11.0 release.
> Project Version Update, main branch (2022.09.15.)

- tests/common/include/tests/common/tools/detector_metadata.hpp
@asalzburger Could you check if it is desirable to use polar coordinate for annulus and disk masks?
> Use polar cooridnate for annulus and disk

- tests/common/include/tests/common/tools/event_writer.hpp
I forgot to write the measurement variance :/
> Write Measurement Variance in Event Writer

- .vscode/settings.json
- core/include/detray/core/detector.hpp
- core/include/detray/core/detector_kernel.hpp
- tests/common/include/tests/common/check_simulation.inl
> Add global to local function in detector

- core/include/detray/core/detector.hpp
- core/include/detray/core/detector_kernel.hpp
- core/include/detray/propagator/actors/parameter_resetter.hpp
- core/include/detray/propagator/actors/parameter_transporter.hpp
- core/include/detray/propagator/actors/pointwise_material_interactor.hpp
- core/include/detray/propagator/base_stepper.hpp
- core/include/detray/propagator/line_stepper.hpp
- tests/common/include/tests/common/tools_propagator.inl
Streamlining some functor calls
> ref: multistore call interface

- core/include/detray/utils/statistics.hpp
- core/include/detray/utils/type_traits.hpp
- tests/common/include/tests/common/check_simulation.inl
- tests/common/include/tests/common/material_interaction.inl
- tests/common/include/tests/common/tools/track_generators.hpp
- tests/common/include/tests/common/tools_track_generators.inl
Implements a track generator that uses random numbers to generate track momentum directions.
> feat: random track state generator

- extern/vecmem/CMakeLists.txt
- tests/unit_tests/cuda/detector_cuda_kernel.cu
- tests/unit_tests/cuda/grids_grid2_cuda.cpp
> Update VecMem Version

- core/CMakeLists.txt
- core/include/detray/tools/bin_fillers.hpp
- core/include/detray/tools/grid_builder.hpp
Add new bin filler that can put bin elements directly in the grid by their local bin index and moved the bin fillers to their own file
> feat: bin idx filler

- cmake/detray-compiler-options-cpp.cmake
- core/include/detray/grids/axis.hpp
- core/include/detray/propagator/navigator.hpp
- core/include/detray/surface_finders/grid/axis.hpp
- core/include/detray/surface_finders/grid/detail/axis_helpers.hpp
- core/include/detray/surface_finders/grid/grid_collection.hpp
- core/include/detray/tools/bin_association.hpp
- core/include/detray/tools/generators.hpp
- extern/algebra-plugins/CMakeLists.txt
- tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
- tests/common/include/tests/common/check_simulation.inl
- tests/common/include/tests/common/material_interaction.inl
- tests/common/include/tests/common/materials.inl
- tests/simulation/run_simulation.cpp
- tests/unit_tests/cuda/transform_store_cuda.cpp
- utils/include/detray/detectors/create_toy_geometry.hpp
- utils/include/detray/simulation/event_writer.hpp
- utils/include/detray/simulation/measurement_smearer.hpp
- utils/include/detray/simulation/random_scatterer.hpp
- utils/include/detray/simulation/simulator.hpp
It seems that new mac version does not allow implicit integer type conversions anymore
> Remove implicit int type conversion

- core/include/detray/masks/unmasked.hpp
- core/include/detray/propagator/actors/aborters.hpp
- core/include/detray/propagator/navigator.hpp
- tests/common/include/tests/common/path_correction.inl
Implement ```target_aborter``` and adapt pathcorrection unittest. Fix interface of navigator state
> feat: target aborter

- tests/benchmarks/cuda/CMakeLists.txt
- tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
Since #404 will likely take a while to finish, this PR just adds openMP support to the CPU benhcmarks
> feat: openMP support to CPU benchmark

- tests/common/include/tests/common/tools/intersectors/helix_cylinder_intersector.hpp
- tests/common/include/tests/common/tools/intersectors/helix_plane_intersector.hpp
- tests/common/include/tests/common/tools_helix_intersectors.inl
- tests/unit_tests/cpu/array/CMakeLists.txt
- tests/unit_tests/cpu/array/array_helix_intersectors.cpp
- tests/unit_tests/cpu/eigen/CMakeLists.txt
- tests/unit_tests/cpu/eigen/eigen_helix_intersectors.cpp
- tests/unit_tests/cpu/smatrix/CMakeLists.txt
- tests/unit_tests/cpu/smatrix/smatrix_helix_intersectors.cpp
- tests/unit_tests/cpu/vc/CMakeLists.txt
- tests/unit_tests/cpu/vc/vc_array_helix_intersectors.cpp
Need to add unit tests for this :p
> Correct path of helix intersector

- tests/common/include/tests/common/test_toy_geometry.inl
- tests/common/include/tests/common/tools_navigator.inl
- utils/CMakeLists.txt
- utils/include/detray/detectors/create_telescope_detector.hpp
- utils/include/detray/detectors/create_toy_geometry.hpp
- utils/include/detray/simulation/event_generator/random_track_generator.hpp
- utils/include/detray/simulation/event_generator/uniform_track_generator.hpp
- utils/include/detray/simulation/event_writer.hpp
- utils/include/detray/simulation/measurement_smearer.hpp
- utils/include/detray/simulation/random_scatterer.hpp
As a continuation from #431 and #434, made all utility headers work out of the box.
I promise that this will be the last (kind of) boring update for a while. The next steps, refactoring the benchmarks and unit tests, will be a lot more rewarding. :smile: (I believe you'll all like how that code will now be possible to be simplified...)
> detray::utils Refactor, main branch (2023.04.05.)

- CMakeLists.txt
Looks like I have been forgetting to update the project version
> Update Project Version to v0.30.0

- core/include/detray/propagator/actors/pointwise_material_interactor.hpp
This PR adds `update()` function in pointwise material interactor which is called in actor operator. The motivation is to use this `update()` function in traccc CKF without creating a `propagator_state_t`
> Refactor the operator of pointwise material interactor

- tests/common/include/tests/common/tools/intersectors/helix_line_intersector.hpp
- tests/common/include/tests/common/tools_helix_intersectors.inl
- tests/common/include/tests/common/tools_helix_trajectory.inl
This PR adds a helix line intersector
> Add helix line intersector

- core/include/detray/masks/annulus2D.hpp
- core/include/detray/masks/cylinder2D.hpp
- core/include/detray/masks/line.hpp
- core/include/detray/masks/rectangle2D.hpp
- core/include/detray/masks/ring2D.hpp
- core/include/detray/masks/single3D.hpp
- core/include/detray/masks/trapezoid2D.hpp
- core/include/detray/masks/unbounded.hpp
- core/include/detray/masks/unmasked.hpp
- core/include/detray/propagator/rk_stepper.hpp
Looks like `to_measurement()` is not being used
> Remove the unused function

- core/include/detray/core/detail/detector_kernel.hpp
- core/include/detray/core/detector.hpp
Adding a detector kernel for free<->bound vector transformation; Needed for CKF in traccc
> Add free<->bound vector kernel

- core/include/detray/core/detector.hpp
> Const qualifier for free<->bound transform funtions

- core/include/detray/geometry/detector_volume.hpp
Split the surface visiting and neighborhood visiting functionality of the volume from the surface store unrolling so that it can be reused in both cases.
> grid: refactor voume neighborhood call

- core/include/detray/geometry/surface.hpp
To allow const detector types in traccc...
> Avoid double const type in surface interface

- core/include/detray/tools/detector_builder.hpp
- io/include/detray/io/common/detector_reader.hpp
Add a constant default bfield to detector in the detector reader. Hotfix until bfield reader becomes available
> feat: Default constant bfield in detector reader

- tests/unit_tests/cpu/check_geometry_navigation.cpp
- utils/include/detray/detectors/create_wire_chamber.hpp
Current 500 * mm z size can be too small with large nubmer of layers.
> Add an option for z size of drift chamber

- core/include/detray/propagator/navigator.hpp
- core/include/detray/propagator/propagator.hpp
- tests/unit_tests/cpu/test_telescope_detector.cpp
- tests/unit_tests/cpu/tools_navigator.cpp
- tests/unit_tests/device/cuda/navigator_cuda_kernel.hpp
I am trying to use a larger mask_tolerance for kalman fitting - not to miss the surface
> Set mask tolerance configurable in propagator

- CMakeLists.txt
> Update Project Version to v0.39.0

- extern/algebra-plugins/CMakeLists.txt
- tests/validation/CMakeLists.txt
> Update algebra plugin to v0.20.0

- extern/algebra-plugins/CMakeLists.txt
> Update algbera plugin version

- core/include/detray/coordinates/cartesian2.hpp
- core/include/detray/coordinates/coordinate_base.hpp
- core/include/detray/coordinates/cylindrical2.hpp
- core/include/detray/coordinates/line2.hpp
- core/include/detray/coordinates/polar2.hpp
- core/include/detray/masks/annulus2D.hpp
- core/include/detray/masks/cylinder2D.hpp
- core/include/detray/masks/line.hpp
- core/include/detray/masks/masks.hpp
- core/include/detray/masks/rectangle2D.hpp
- core/include/detray/masks/ring2D.hpp
- core/include/detray/masks/single3D.hpp
- core/include/detray/masks/trapezoid2D.hpp
- core/include/detray/masks/unbounded.hpp
- tests/unit_tests/cpu/masks_annulus2D.cpp
- tests/unit_tests/cpu/projection_matrix.cpp
- tests/validation/src/simulation_validation.cpp
- tutorials/include/detray/tutorial/my_square2D.hpp
- utils/include/detray/simulation/measurement_smearer.hpp
Remove the template parameter of normal ordering in mask types.
> Refactor Measurement Ordering

- tests/simulation/run_simulation.cpp
- tests/validation/src/simulation_validation.cpp
- utils/include/detray/simulation/measurement_smearer.hpp
- utils/include/detray/simulation/simulator.hpp
- utils/include/detray/simulation/smearing_writer.hpp
This PR changes simulator template parameter (`smearer_t` -> `writer_t`)
I am thinking of making a digitization writer type in traccc and use it with simulator
> Refactor Simulator Template Parameter

- core/include/detray/tracks/bound_track_parameters.hpp
- core/include/detray/tracks/detail/track_helper.hpp
- core/include/detray/tracks/free_track_parameters.hpp
- tests/unit_tests/cpu/tools_track.cpp
> Add pT function for bound track parameters

- tests/validation/python/validation/json_schema/homogeneous_material.py
Add material parametrization as required field to the homogeneous material schema
> fix: material json schema

- core/include/detray/masks/annulus2D.hpp
- core/include/detray/masks/masks.hpp
- plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
- plugins/svgtools/include/detray/plugins/svgtools/utils/surface_kernels.hpp
- tests/unit_tests/svgtools/masks.cpp
- tests/validation/src/detector_display.cpp
Fix the vertices used for the svg display of the annulus shape (It seems like actsvg is expecting the vertices in local cartesian coordinates)
> fix: annulus svg

- core/include/detray/tracks/bound_track_parameters.hpp
- core/include/detray/tracks/detail/track_helper.hpp
- core/include/detray/tracks/free_track_parameters.hpp
- tests/unit_tests/cpu/tools_track.cpp
> Define pz funtions

- utils/include/detray/simulation/random_scatterer.hpp
I don't know why this could be compiled in detray
> Add material getter in random scatterer

- plugins/svgtools/include/detray/plugins/svgtools/conversion/detector.hpp
- plugins/svgtools/include/detray/plugins/svgtools/conversion/grid.hpp
- plugins/svgtools/include/detray/plugins/svgtools/conversion/intersection.hpp
- plugins/svgtools/include/detray/plugins/svgtools/conversion/landmark.hpp
- plugins/svgtools/include/detray/plugins/svgtools/conversion/portal.hpp
- plugins/svgtools/include/detray/plugins/svgtools/conversion/surface.hpp
- plugins/svgtools/include/detray/plugins/svgtools/conversion/trajectory.hpp
- plugins/svgtools/include/detray/plugins/svgtools/conversion/volume.hpp
- plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
- plugins/svgtools/include/detray/plugins/svgtools/styling/styling.hpp
- tests/unit_tests/svgtools/grids.cpp
- tests/unit_tests/svgtools/groups.cpp
- tests/unit_tests/svgtools/surfaces.cpp
- tests/unit_tests/svgtools/trajectories.cpp
- tests/unit_tests/svgtools/volumes.cpp
- tests/unit_tests/svgtools/web.cpp
- tests/validation/include/detray/validation/detail/svg_display.hpp
- tests/validation/src/detector_display.cpp
Implement actsvg sheets to show grids in zphi view, including surface connections to bins
> feat: display connected grids in svg

- tests/unit_tests/cpu/tools_helix_trajectory.cpp
Add a helix test for postivie charge
> Add a helix test for positive charge

- core/include/detray/utils/matrix_helper.hpp
- tests/unit_tests/cpu/tools_matrix_helper.cpp
This PR adds a cholesky decomposition, temporarily in detray.
> Add a cholesky decomposition

- core/include/detray/materials/predefined_materials.hpp
- tests/unit_tests/cpu/energy_loss.cpp
Add Iron and Cesium iodide in the predefined materials
> Add Fe and CsI

- utils/include/detray/simulation/event_generator/random_track_generator.hpp
Add a seed in the random track generator
> Add a seed in the random track generator

- core/include/detray/tools/telescope_generator.hpp
Set local_x of telescope planes as the curvilinear vector with resepct to local_z
> Set local_x of telescope planes as the curvilinear vector with resepct to local_z

- core/include/detray/core/detail/container_views.hpp
- core/include/detray/surface_finders/grid/detail/bin_storage.hpp
- core/include/detray/surface_finders/grid/detail/grid_bins.hpp
- core/include/detray/surface_finders/grid/grid.hpp
- core/include/detray/surface_finders/grid/grid_collection.hpp
- core/include/detray/surface_finders/grid/populators.hpp
- core/include/detray/utils/ranges/join.hpp
- core/include/detray/utils/ranges/ranges.hpp
- core/include/detray/utils/ranges/subrange.hpp
- tests/unit_tests/core/tuple_helpers.cpp
- tests/unit_tests/cpu/grid_grid.cpp
- tests/unit_tests/cpu/grid_grid_collection.cpp
- tests/unit_tests/device/cuda/container_cuda_kernel.hpp
- tests/unit_tests/device/cuda/mask_store_cuda_kernel.hpp
- tests/unit_tests/device/cuda/sf_finders_grid_cuda.cpp
- tests/unit_tests/device/cuda/sf_finders_grid_cuda_kernel.cu
- tests/unit_tests/device/cuda/sf_finders_grid_cuda_kernel.hpp
Adds a bin backend storage type that can handle dynamic bin capacities as well as indexed grids
> feat: dynamic grid capacity and indexed grids

- core/include/detray/utils/axis_rotation.hpp
- tests/unit_tests/cpu/axis_rotation.cpp
Add more comments and test for axis rotation
> Add more comments and test for axis rotation

- tests/unit_tests/utils/landau_sampling.cpp
> Fix the overflow in the landau sampling test

- core/include/detray/propagator/rk_stepper.ipp
Fix bugs in dr_n/dt calculation
> Fix bugs in dr_n/dt calculation

- core/include/detray/propagator/rk_stepper.ipp
- tests/validation/root/covariance_validation.C
- tests/validation/root/jacobian_comparison.C
- tests/validation/root/rk_tolerance_comparison.C
- tests/validation/shell/run_jacobian_validation.sh
- tests/validation/src/jacobian_validation.cpp
- Fix bugs
- Highly recommended to use ROOT v6.30+ for running the macros.
- Implemented Ridders' algorithm for better numerical differentiation
- Added a plot for mean step size as a function of the error tolerance
> Fix jacobian validation scripts

- core/include/detray/materials/detail/relativistic_quantities.hpp
- core/include/detray/materials/interaction.hpp
- core/include/detray/propagator/actors/pointwise_material_interactor.hpp
- core/include/detray/propagator/rk_stepper.hpp
- core/include/detray/propagator/rk_stepper.ipp
- tests/integration_tests/cpu/material/material_interaction.cpp
- tests/unit_tests/cpu/material/energy_loss.cpp
- tests/unit_tests/cpu/material/stopping_power_derivative.cpp
- Significantly reduce the computation for derivatives
- Rename functions more consistently
> Rework interaction

- core/include/detray/materials/detail/relativistic_quantities.hpp
- core/include/detray/materials/interaction.hpp
- tests/unit_tests/cpu/material/stopping_power_derivative.cpp
Just trying to make things less error-prone
> Use material argument instead of scalars

- .gitignore
ROOT scripts generates too many files when executed
> Ignore root script byproducts

- .gitignore
- core/include/detray/propagator/rk_stepper.hpp
- core/include/detray/propagator/rk_stepper.ipp
- tests/include/detray/test/utils/particle_gun.hpp
- tests/integration_tests/cpu/propagator/jacobian_validation.cpp
- tests/scripts/run_jacobian_validation.sh
- tests/validation/root/rk_tolerance_comparison.C
PR comes with the following changes:
- Fix the gitignore
- Let `dtds` and `dqopds` return non-Nan value when there was no any step
- Add `algorithm` in particle gun header
- Improve the jacobian validation scripts
> Fix bug in the stepper and improve the validation scripts

- tests/integration_tests/cpu/propagator/jacobian_validation.cpp
- tests/validation/root/covariance_validation.C
- tests/validation/root/jacobian_comparison.C
- tests/validation/root/rk_tolerance_comparison.C
A minor update in the validation scripts and bug fix
> Update the jacobian validation parameter

- tests/integration_tests/cpu/propagator/jacobian_validation.cpp
> Add detector length in root validation file

- tests/integration_tests/cpu/propagator/jacobian_validation.cpp
#687 reminds me that I was not using the same rotation angle for two geometries
> Use the same rotation angle for rectangular and wire

- tests/validation/root/covariance_validation.C
I will just merge it once CI is done
> Adjust text location which is important

- tests/validation/root/covariance_validation.C
- tests/validation/root/rk_tolerance_comparison.C
> Adjust the text alignment

- tests/integration_tests/cpu/propagator/jacobian_validation.cpp
- tests/validation/root/jacobian_comparison.C
- tests/validation/root/rk_tolerance_comparison.C
> Disable random shift of surface

- tests/validation/root/covariance_validation.C
- tests/validation/root/jacobian_comparison.C
- tests/validation/root/rk_tolerance_comparison.C
Prbably the last nitpick change before bumping to new tag...
> Adjust text

- tests/integration_tests/cpu/propagator/jacobian_validation.cpp
Mostly finished before the 50th iteration
> Record the number of iterations from Ridders algorithm

- utils/include/detray/detectors/factories/telescope_generator.hpp
> Switch the rotation direction for wire telescope detector

- tests/integration_tests/cpu/propagator/jacobian_validation.cpp
- utils/include/detray/detectors/build_telescope_detector.hpp
I had to remove the warning message from no materials and zero thickness, which I think should be allowed
> Write Euler angles and remove module materials in Jacobian validation

- tests/integration_tests/cpu/propagator/jacobian_validation.cpp
- tests/validation/root/covariance_validation.C
- tests/validation/root/jacobian_comparison.C
- tests/validation/root/rk_tolerance_comparison.C
> State name of field and material in the plots

- tests/integration_tests/cpu/propagator/jacobian_validation.cpp
- tests/validation/root/covariance_validation.C
- tests/validation/root/jacobian_comparison.C
Removing unused codes in the validation scripts
> Clean up the validation scripts

- core/include/detray/builders/detector_builder.hpp
- io/include/detray/io/common/detail/grid_reader.hpp
- io/include/detray/io/common/homogeneous_material_reader.hpp
- io/include/detray/io/common/material_map_reader.hpp
Make sure that a volume builder exists, before decorating it
> ref:Some additional checks during detector building

- tests/tools/python/file_checker.py
Small fix in the json schema python file
> fix: json file checker

- tests/unit_tests/cpu/navigation/intersection/helix_trajectory.cpp
> Add a test for helix radius

- extern/actsvg/CMakeLists.txt
This new release fixes a few compiler errors.
> Update actsvg version to v0.4.45

- core/include/detray/grids/axis.hpp
- tests/unit_tests/cpu/navigation/intersection/helix_trajectory.cpp
- tests/unit_tests/cpu/propagator/jacobian_polar.cpp
- tests/unit_tests/cpu/utils/bounding_volume.cpp
- tests/unit_tests/cpu/utils/grids/grid_collection.cpp
Fairly basic changes, but they stop the compiler complaining.
> Fix a few more floating point conversion errors

- utils/include/detray/simulation/random_scatterer.hpp
> fix: Update surface material selection in random scatterer

- .github/ci_setup.sh
- .github/workflows/builds.yml
- .gitlab-ci.yml
- CMakeLists.txt
- core/include/detray/navigation/detail/helix.hpp
- plugins/algebra/smatrix/include/detray/plugins/algebra/smatrix_definitions.hpp
As ACTS has moved on to C++20, we can too.
> Raise minimum C++ version to 20

- core/include/detray/definitions/pdg_particle.hpp
- core/include/detray/definitions/units.hpp
- core/include/detray/materials/detail/relativistic_quantities.hpp
- core/include/detray/materials/interaction.hpp
- core/include/detray/propagator/actors/pointwise_material_interactor.hpp
- core/include/detray/propagator/base_stepper.hpp
- core/include/detray/propagator/propagator.hpp
- core/include/detray/propagator/rk_stepper.ipp
- core/include/detray/tracks/bound_track_parameters.hpp
- core/include/detray/tracks/detail/track_helper.hpp
- core/include/detray/tracks/free_track_parameters.hpp
- io/include/detray/io/csv/track_parameters.hpp
- tests/include/detray/test/cpu/detector_scan.hpp
- tests/include/detray/test/cpu/navigation_validation.hpp
- tests/include/detray/test/device/cuda/navigation_validation.hpp
- tests/integration_tests/cpu/material/material_interaction.cpp
- tests/integration_tests/cpu/propagator/jacobian_validation.cpp
- tests/unit_tests/cpu/CMakeLists.txt
- tests/unit_tests/cpu/core/pdg_particle.cpp
- tests/unit_tests/cpu/material/energy_loss.cpp
- tests/unit_tests/cpu/material/stopping_power_derivative.cpp
- tests/unit_tests/cpu/simulation/track_generators.cpp
- tests/unit_tests/cpu/tracks/bound_track_parameters.cpp
- tests/unit_tests/cpu/tracks/free_track_parameters.cpp
- utils/include/detray/simulation/random_scatterer.hpp
Added pdg particles and use them in the propagator properly.
Also `charge()` is dropped from the track parameter classes which was assuming that charge is -1 or 1.
> Define pdg particles and refactor charge in tracks

- tests/benchmarks/cpu/CMakeLists.txt
- tests/benchmarks/cpu/benchmark_propagator.cpp
- tests/benchmarks/cuda/benchmark_propagator_cuda.cpp
- tests/scripts/run_benchmarks.sh
@niermann999 mentioned that she will split the cpu and cuda benchmark in the near future, but I also need them to be split soon for the benchmark monitoring.
> Split CPU and CUDA propagation benchmark

- core/include/detray/tracks/bound_track_parameters.hpp
- core/include/detray/tracks/free_track_parameters.hpp
Remove assert for negative times
> ref: Remove assert for negative times

- CMakeLists.txt
> ref: cmake version number

- README.md
> Do not specify the figure size for continuous benchmark

- CMakeLists.txt
- detectors/CMakeLists.txt
- tests/CMakeLists.txt
A few things to make the new detray version work in traccc
> ref: Cmake fixes for traccc

- core/include/detray/navigation/navigator.hpp
This commit adds a few minor assertions that helped me while debugging an issue in traccc.
> Add a few new navigator assertions

- CMakeLists.txt
- core/include/detray/navigation/navigator.hpp
Allow end of world in navigator assertions
> fix: navigation assertion

- core/include/detray/propagator/rk_stepper.ipp
To remove unnecessary variables
> Calculate the field gradients only at three points

- .github/workflows/builds.yml
- .github/workflows/checks.yml
This PR removes the use of the artifact uploading action, and updates the checkout action to v4.
> Fix several outdated Github actions

- core/include/detray/core/detail/tuple_container.hpp
The tuple container previously produced some truly esoteric compiler warnings, including some compile-time recursion depth errors. This commit refactors the function a bit to ensure that the errors are bounded in size and easier to read.
> Improve warnings in tuple container visitor

- core/include/detray/definitions/detail/algorithms.hpp
- core/include/detray/navigation/accelerators/brute_force_finder.hpp
- core/include/detray/utils/find_bound.hpp
- core/include/detray/utils/grid/detail/bin_storage.hpp
- core/include/detray/utils/grid/detail/bin_view.hpp
- core/include/detray/utils/ranges/cartesian_product.hpp
- core/include/detray/utils/ranges/detail/iterator_functions.hpp
- core/include/detray/utils/ranges/enumerate.hpp
- core/include/detray/utils/ranges/iota.hpp
- core/include/detray/utils/ranges/join.hpp
- core/include/detray/utils/ranges/pick.hpp
- core/include/detray/utils/ranges/ranges.hpp
- core/include/detray/utils/ranges/static_join.hpp
- core/include/detray/utils/ranges/subrange.hpp
- core/include/detray/utils/sort.hpp
- plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
- tests/include/detray/test/utils/statistics.hpp
- tests/unit_tests/cpu/utils/grids/grid.cpp
- tests/unit_tests/cpu/utils/ranges.cpp
Add concepts for ranges and iterator categories. In order to fullfill the stadard library iterator concepts, some operators needed to be added or tweaked on the detray custom iterators
> feat: ranges concepts

- .gitlab-ci.yml
Use the gpu machine for the build to see if that avoids the test failure
> fix: Build SYCL tests on same machine as the test are run on and reactivate tests

- core/include/detray/builders/cylinder_portal_generator.hpp
- core/include/detray/builders/detail/bin_association.hpp
- core/include/detray/core/detail/single_store.hpp
- core/include/detray/core/detector.hpp
- core/include/detray/geometry/tracking_volume.hpp
- core/include/detray/navigation/intersection_kernel.hpp
- core/include/detray/utils/grid/grid.hpp
- io/include/detray/io/common/geometry_writer.hpp
- tests/integration_tests/cpu/builders/homogeneous_material_builder.cpp
- tests/integration_tests/cpu/builders/volume_builder.cpp
- tests/integration_tests/cpu/propagator/jacobian_validation.cpp
- tests/unit_tests/cpu/builders/detector_builder.cpp
- tests/unit_tests/cpu/core/containers.cpp
- tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp
- tests/unit_tests/device/cuda/container_cuda.cpp
Replaced all calls to `single_store::operator[]()` with calls to `single_store::at()`
> Dropped elementwise access to single_store

- core/include/detray/core/detail/container_buffers.hpp
Stopped the `detray::concepts::detail::get_buffer` struct from using concepts itself, as GCC 12 is not able to understand the code like that. Which is fair enough, as it took us with @stephenswat a hot minute to understand the intention of this code as well. 🤔
This is of course undoing a recent upgrade from @niermann999, but using concepts in the "trait resolution" was anyway sort of a funky thing in my mind. Using SFINAE with this trait should probably be better supported by the compilers.
@beomki-yeo, this is the issue that affects the build of [traccc](https://github.com/acts-project/traccc) with GCC 12. 😉
> GCC 12 Build Fix, main branch (2024.10.22.)

- .github/workflows/builds.yml
This resolves the internal compiler error in #871.
> Update CUDA version in CI to 12.6

- .github/workflows/checks.yml
- tests/tools/python/file_checker.py
- tests/tools/python/impl/__init__.py
- tests/tools/python/impl/plot_material_scan.py
- tests/tools/python/impl/plot_navigation_validation.py
- tests/tools/python/impl/plot_ray_scan.py
- tests/tools/python/impl/plot_track_params.py
- tests/tools/python/json_schema/__init__.py
- tests/tools/python/json_schema/geometry.py
- tests/tools/python/json_schema/homogeneous_material.py
- tests/tools/python/json_schema/material_maps.py
- tests/tools/python/json_schema/surface_grids.py
- tests/tools/python/material_validation.py
- tests/tools/python/navigation_validation.py
- tests/tools/python/options/__init__.py
- tests/tools/python/options/common_options.py
- tests/tools/python/options/detector_io_options.py
- tests/tools/python/options/plotting_options.py
- tests/tools/python/options/propagation_options.py
- tests/tools/python/options/track_generator_options.py
- tests/tools/python/plotting/__init__.py
- tests/tools/python/plotting/plot_helpers.py
- tests/tools/python/plotting/pyplot_factory.py
Add the github action of black (https://black.readthedocs.io/en/stable/integrations/github_actions.html) to the CI to check the formatting of the python files in tests/tools/python
> feat: add python formatting as a CI job

- core/include/detray/propagator/actor_chain.hpp
- core/include/detray/propagator/actors/parameter_resetter.hpp
- core/include/detray/propagator/actors/parameter_transporter.hpp
- core/include/detray/propagator/base_actor.hpp
Adapt actor chain for empty state and to produce actor state tuple if states are default constructible
> ref: Allow empty states in actor chain and construct state tuple

- CMakeLists.txt
Update project version to `0.83.0`. 
I need #891 in [traccc](https://github.com/acts-project/traccc), so I'll make a new release/tag once this is pushed in.
> Project Version Update, main branch (2024.11.29.)

- extern/benchmark/CMakeLists.txt
Update google benchmark to latest version 1.9.1
> feat: Update google benchmark

- core/include/detray/builders/detail/bin_association.hpp
- tests/unit_tests/cpu/geometry/tracking_surface.cpp
- tests/unit_tests/cpu/navigation/intersection/intersection_kernel.cpp
Fix a few warnings that appear with gcc 14
> Fix: a few warnings about uninitialized values

- CMakeLists.txt
Update Project Version to 0.93.0
> Update Project Version to 0.93.0

- core/include/detray/propagator/actors/barcode_sequencer.hpp
This will be used to add a new error code in traccc fitting
> Check overflow in barcode sequencer

- CMakeLists.txt
> Update Project Version

- tests/include/detray/test/validation/navigation_validation_utils.hpp
Fix an error during the counting of the number of missed candidates at a given step and make sure that the assertion that all missed candidates were counted does not trigger for swapped portals.
Also adds a recounting of the inserted dummy records to check the number of missed surfaces independently and passes a meaningful boolean result from the function.
> fix: counting error and failed assertion

- tests/include/detray/test/validation/material_validation_utils.hpp
Fix double accounting of material steps in trace and add comparison function between two material traces
> feat: Material trace comparison

- core/include/detray/propagator/rk_stepper.ipp
Check the minimum step size as absolute value, in case it is negative during backward propagation
> fix: Observe minimum step size

- tests/include/detray/test/common/navigation_validation_config.hpp
- tests/include/detray/test/validation/navigation_validation_utils.hpp
Fix a default value and the configuration. Also discover and display the counting errors correctly
> fix: navigation validation tools

- core/include/detray/navigation/navigator.hpp
- tests/unit_tests/cpu/navigation/navigator.cpp
When switching navigation direction on the last portal, don't exit backwards
> feat: Allow backward navigation from portal

- core/include/detray/propagator/actors/aborters.hpp
Add cuda qualifiers to momentum aborter
> fix: Momentum aborter

- CMakeLists.txt
> ref: Bump version number to 0.97.0

- CMakeLists.txt
Update version number to 0.98.0
> ref: Update version number

- tests/tools/python/impl/plot_track_params.py
Remove the statistics block from some plots, where these make no sense
> ref: Remove stats from some plots

- core/include/detray/core/detector.hpp
- core/include/detray/geometry/tracking_volume.hpp
- core/include/detray/navigation/accelerators/brute_force_finder.hpp
- core/include/detray/utils/consistency_checker.hpp
- core/include/detray/utils/grid/detail/axis.hpp
- core/include/detray/utils/grid/grid.hpp
- core/include/detray/utils/print_detector.hpp
- io/include/detray/io/frontend/detector_reader.hpp
- plugins/svgtools/include/detray/plugins/svgtools/illustrator.hpp
- tests/include/detray/test/cpu/material_scan.hpp
Add a function to print the detector for debugging.
> feat: printable detector

- tests/tools/python/impl/plot_benchmark_results.py
- tests/tools/python/impl/plot_detector_scan.py
- tests/tools/python/plotting/pyplot_factory.py
- tests/tools/python/propagation_benchmarks.py
- tests/tools/src/cpu/propagation_scaling.cpp
Add a vertical line with the number of physical cores to the scaling plot and add new measurement points to the benchmarks for common number of cores.
> feat: Add number of physical cores to scaling plots

- tests/tools/src/cpu/detector_display.cpp
Make the material gradient box position adjustable to avtsvg x-axis size
> feat: adjustable gradient box position

- CMakeLists.txt
This commit increments the version number to v0.101.0 to prepare for a new release.
> Update version number to v0.101.0

- CMakeLists.txt
- cmake/detray-compiler-options-hip.cmake
- core/include/detray/definitions/detail/hip_definitions.hpp
- tests/unit_tests/device/hip/CMakeLists.txt
- tests/unit_tests/device/hip/detector_hip.cpp
- tests/unit_tests/device/hip/detector_hip_kernel.hip
Add a few fixes to get the NVIDIA HIP compilation running for the HIP unittests
> Fix: NVIDIA HIP compilation

- core/include/detray/core/detail/indexing.hpp
- core/include/detray/geometry/barcode.hpp
- core/include/detray/navigation/navigator.hpp
- core/include/detray/utils/bit_encoder.hpp
- core/include/detray/utils/consistency_checker.hpp
- io/include/detray/io/backend/geometry_reader.hpp
> chore: Wether -> whether

- tests/include/detray/test/validation/navigation_validation_utils.hpp
A number of small fixes in the navigation validation utils:
- Do not set the initial stddevs to zero in a debug build (triggers invalid bound parameter assertion)
- distinguish swapped portals from swapped sensitive surfaces in the intersection trace (this can happen if the mask tolerances are very large and the surfaces overlap)
- Improve error output
> fix: navigation validation utils

- core/include/detray/propagator/actors/parameter_transporter.hpp
In #1066 I accidentally broke the Jacobian computation by using the current surface rather than the previous surface for the bound-to-free Jacobian. This commit rectifies this issue.
> Fix bound-to-free Jacobian using wrong surface

- core/include/detray/builders/detector_builder.hpp
- core/include/detray/builders/grid_builder.hpp
- core/include/detray/builders/homogeneous_material_builder.hpp
- core/include/detray/builders/homogeneous_material_factory.hpp
- core/include/detray/builders/material_map_builder.hpp
- core/include/detray/builders/material_map_factory.hpp
- core/include/detray/builders/surface_factory.hpp
- core/include/detray/builders/volume_builder.hpp
- core/include/detray/propagator/propagator.hpp
- core/include/detray/utils/grid/detail/axis.hpp
- core/include/detray/utils/grid/grid.hpp
- core/include/detray/utils/print_detector.hpp
- io/include/detray/io/backend/detail/grid_reader.hpp
- io/include/detray/io/backend/geometry_reader.hpp
- io/include/detray/io/backend/homogeneous_material_reader.hpp
- io/include/detray/io/backend/material_map_reader.hpp
- io/include/detray/io/backend/surface_grid_reader.hpp
- io/include/detray/io/frontend/detector_reader.hpp
- tests/include/detray/test/common/build_telescope_detector.hpp
- tests/include/detray/test/common/build_toy_detector.hpp
- tests/include/detray/test/common/build_wire_chamber.hpp
- tests/include/detray/test/cpu/navigation_validation.hpp
- tests/include/detray/test/device/cuda/navigation_validation.hpp
- tests/include/detray/test/validation/navigation_validation_utils.hpp
- tests/tools/python/impl/detector_data_conversion.py
Refactors more of the logging output and fixes the python file converters to be able to handle json files that come in the merged layout, but did not actually merge any portals, yet. This allows to use the script on the current G200 ITk files
> fix: Some more logging and file converter pythons script
